- src/commands/sourcemaps/api.ts
- src/commands/sourcemaps/interfaces.ts
- src/commands/sourcemaps/upload.ts
- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-test.ts
- src/helpers/__tests__/utils.test.ts
- src/helpers/utils.ts
This PR moves API request constructor to one common helper to ease authentication (now commands only need to fetch api/app keys as they need and pass it to the request constructor)
> [api] factorize API authentication

- package.json
- src/commands/lambda/__tests__/function.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/tags.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/function.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/tags.ts
- tsconfig.json
This is part of a larger effort to track serverless usage. When a lambda function is provisioned and instrumented with this CLI tool, we want to get data on that and understand how many functions our customers have instrumented with different tools. We tag lambdas already with our macro version, and our serverless plugin version. So, this follows the same pattern to understand which versions are being.
When a lambda function is being processed, if the lambda has the version tag and it's the same as the current version we don't update at all. But, if no tag is found or a different version exists then we update with the new version tag.
> [serverless] Tag lambdas with ci packege version

- package.json
-  [serverless] Tag lambdas with ci package version https://github.com/DataDog/datadog-ci/pull/91
> Publish `v0.6.0`

- .github/CODEOWNERS
The entire team is responsible for the CLI command so let's make sure the team is assigned, rather than the first contributors to this tool.
> Changed codeowners of datadog-ci command.

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/utils.ts
Sometimes the backend may return 5xx errors on which we want to retry. So this PR adds a retry mechanism on all requests performed by the synthetics command to retry every 500 milliseconds if the status code of the response is in the 5xx class - three times at most
> [synthetics] add retry machanism on synthetics command requests

- package.json
This PR bumps the package to version 0.8.0, releasing:
* [trace] New `trace command` for wrapping your bash commands (**note**: this command is not ready for production environments yet).
> Bump to 0.8.0

- .github/workflows/publish.yml
Fix publish script
Use env setup instead of `yarn config set npmAuthToken`
> Fix Publish Script

- .github/workflows/ci.yml
- .github/workflows/e2e/test.dependencies.json
- src/commands/dependencies/README.md
- src/commands/dependencies/__tests__/fixtures/dependencies.json
- src/commands/dependencies/__tests__/upload.test.ts
- src/commands/dependencies/renderer.ts
- src/commands/dependencies/upload.ts
Add retry logic for dependencies upload to avoid breaking client's CI jobs because random issues in our API
I implemented it by copy-pasting code from the synthetics test command
> PROF-2265 - Dependencies upload retry

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/renderer.ts
This PR adds support for overridden config in results rendering for synthetics tests. (only for the start URL as other config parameters are not rendered in results)
> [synthetics] add support for overridden config in result rendering

- src/commands/synthetics/api.ts
- src/helpers/utils.ts
It allows ignoring *_PROXY environment variables, and leverages this in synthetics command.
It does so by setting the `proxy: false` config in axios when building the axios instance. (cf. https://github.com/axios/axios/pull/691)
No unit tests were added to test this behavior as it would require setting an HTTP server and was deemed too heavy.
> [synthetics][SW-598] ignore *_PROXY environment variables

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
Gracefully handle non-parsable start urls of synthetics tests.
The parsing is now in a `try/catch` block and variables replacing is done on a "best-effort" basis.
> [synthetics] gracefully handle non-parsable start urls

- src/commands/synthetics/renderer.ts
[SW-628](https://datadoghq.atlassian.net/browse/SW-628)
Use default `General Error` error name for `Unknown error`.
> [Synthetics][SW-638] Replace `Unknown error` with `General Error` in results output

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
Fix variable substitution by allowing variables with an empty content.
> [synthetics] fix start url variable substitution

- package.json
This PR bumps the package to version 0.8.5, releasing:
- [[sourcemaps] Add simple e2e test for sourcemaps upload](https://github.com/DataDog/datadog-ci/pull/121)
- [Fix Naming of Commit SHA](https://github.com/DataDog/datadog-ci/pull/107)
- [[synthetics\]\[SW-635] Don't display unhealthy results URLs](https://github.com/DataDog/datadog-ci/pull/122)
- [[synthetics][SW-638] Replace `Unknown error` with `General Error` in results output](https://github.com/DataDog/datadog-ci/pull/124)
- [[synthetics] Fix start url variable substitution](https://github.com/DataDog/datadog-ci/pull/125)
[SW-635]: https://datadoghq.atlassian.net/browse/SW-635
> Publish v0.8.5

- package.json
- yarn.lock
This PR upgrades dependencies containing known vulnerabilities:
- `yargs-parser` (https://github.com/advisories/GHSA-p9pc-299p-vxgp) by upgrading `jest`, `ts-jest` and  `typescript`
- `ini` (https://github.com/advisories/GHSA-qqgx-2p2h-9c37) by using yarn resolutions to bump to its patched update
- `kind-of` (https://github.com/advisories/GHSA-6c8f-qphg-qjgp) by using yarn resolutions to bump to its patched update
> [yarn] upgrade vulnerable dependencies

- src/commands/sourcemaps/README.md
- src/commands/sourcemaps/__tests__/upload.test.ts
- src/commands/sourcemaps/renderer.ts
- src/commands/sourcemaps/upload.ts
Update the `--minified-path-prefix` flag usage.
The backend will now be able to match against the path portion of unminified URLs instead of just the full URL.
> Change the sourcemap URL matching

- package.json
This PR releases https://github.com/DataDog/datadog-ci/pull/131 which updates the `--minified-path-prefix` flag usage in the sourcemaps upload command.
> Publish v0.9.0

- src/commands/lambda/README.md
Update Lambda instrumentation command readme based on recent customer feedback.
- Clarify that only Python and Node.js Lambda functions are supported.
- Update sample commands
- Update arguments' descriptions
> Update Lambda instrumentation command readme

- src/commands/sourcemaps/api.ts
[Update of axios](https://github.com/DataDog/datadog-ci/pull/138) did introduce this change:
https://github.com/axios/axios/pull/2781
It broke upload of sourcemaps for requests larger than 10MB.
This PR intends to fix it.
> Fix sourcemaps upload size limit.

- package.json
This PR bumps version to 0.9.2, releasing:
[sourcemaps] Fix max size of uploaded sourcemaps
> Publish v0.9.2

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/run-test.ts
When triggering tests with `--public-id`, the global config is ignored and tests are run with their original configuration.
Build `publicIdsTriggers` with global override configuration as config for each test instead of `{}`.
> [Synthetics][SW-797] Fix config override for tests run by public ID

- package.json
Release v0.9.4 which fixes global configuration override for Synthetics tests when launched via public ID: https://github.com/DataDog/datadog-ci/pull/147
> Publish v0.9.4

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/renderer.ts
- src/commands/synthetics/utils.ts
[SW-843](https://datadoghq.atlassian.net/browse/SW-843)
Update test trigger payload with necessary info for CI results batches.
- Add `pollingTimeout` to forwarded config overrides.
- Remove `metadata` from all tests' payload and only send it in payload root.
- Always send strictest `executionRule` in test config, stop overriding it in test `options.ci`.
- Send `skipped` tests (will now be skipped in backend only) evenfor batches of skipped-only tests.
Also appends `(non-blocking)` to non blocking tests trigger message.
> [Synthetics][SW-843] Update test trigger payload for CI results batches

- package.json
Publish v0.10.0.
This version introduce support for Synthetics batch CI tests results (https://github.com/DataDog/datadog-ci/pull/150).
> Publish v0.10.0

- src/commands/sourcemaps/__tests__/git.test.ts
- src/commands/sourcemaps/__tests__/upload.test.ts
- src/commands/sourcemaps/git.ts
- src/commands/sourcemaps/upload.ts
Improve the performance of the sourcemap upload command with git support.
- Replace the nested loop with one loop + hash map lookups
- Encapsulate the whole tracked files matching logic into a single class for more clarity
- Use `fs.readFileSync` directly instead of "promisifying" `fs.readFile`
- Change the output of successful uploads to also include the time spent building payloads
Leverage hash maps to reduce the time complexity of the algorithm.
> Git support: improve performance

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
Parse `startUrl` for `browser` and `http` tests
> [synthetics] do not parse url if type or subtype is not correct

- .github/workflows/ci.yml
In order to detect outdated yarn lockfile in the repository, this PR adds the `immutable` flag to `yarn install`.
> [ci] use immutable installs to detect outdated yarn.lock

- package.json
- yarn.lock
Uses [datadog-metrics 0.9.0](https://www.npmjs.com/package/datadog-metrics/v/0.9.0) instead of Datadog's fork. https://github.com/dbader/node-datadog-metrics/pull/50 has been merged, including the changes that we wanted. There is no need to have a dependency though git anymore, which is causing security concerns for some customers.
> Use latest datatog-metrics instead of Git dependency

- package.json
New `0.10.5-alpha` release with the changes of https://github.com/DataDog/datadog-ci/pull/161
> New alpha release v0.10.5-alpha

- .github/workflows/ci.yml
- package.json
- testEnvironment.js
- yarn.lock
Keep up to date with `dd-trace` releases. It also includes some minor fixes for the `jest` instrumentation. 
* Bump `dd-trace` to `0.31.0`.
* Disable tracing for local development, as it forces you to have the Datadog Agent running in your machine.
> [ci-app] Bump dd-trace and Disable Tracing for Local Dev

- package.json
Add synthetics-tunnel work (in https://github.com/DataDog/datadog-ci/pull/169 as WIP until properly tested) to the alpha release channel
> v0.10.6-alpha

- src/commands/synthetics/__tests__/tunnel.test.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/tunnel.ts
- src/commands/synthetics/websocket.ts
The tunnel uses a websocket connection to encapsulate streams to datadog's infrastructure. This PR updates the tunnel to use the proxy defined by the proxy configuration of datadog-ci if there is one.
It passes the proxy options to the WebSocketWithReconnection object which then creates an agent and feeds it to the `ws` library. As `proxy-agent` typings are not up-to-date compared to latest nodes one, there is a `as unknown as Agent` cast before passing it to `ws`.
> Mrousse/sw 910/add proxy support tunnel

- package.json
Release version 0.10.7-alpha of the package with an improved support for the tunnel feature of the synthetics command.
> [ci] bump to version 0.10.7-alpha

- src/commands/synthetics/api.ts
- src/commands/synthetics/tunnel.ts
This PR updates the format used for the public ids to be triggered to be compatible with the backend.
It also updates the condition used to authorize access to the tunnel.
> [synthetics] update tunnel trigger format

- package.json
Release version 0.10.8-alpha of the package with an improved support for the tunnel feature of the synthetics command.
> Bump to version 0.10.8-alpha

- src/commands/trace/command.ts
- src/helpers/tags.ts
Be able to distinguish spans created by the CLI tool vs the ones created from "native" instrumentation (like Jenkins and Gitlab)
* Add `_dd.ci.level`, `_dd.ci.build_level` and `span.type` tags to the created spans.
> [ci-app] Add `ci.level` and `ci.build_level` Tags to Created Spans 

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
On tunnel initialization, the list of ids of the tests to trigger is sent to the backend which will send a 404 if one of the test is missing.
This PR fixes this by splitting the code to fetch the test configs and to trigger the tests into two functions, between which the tunnel is initialized.
> [synthetics] filter out missing test tunnel

- package.json
Create version 0.10.9 in the alpha channel to push fixes to synthetics tunnel feature.
> Release 0.10.9-alpha

- package.json
This PR releases v0.10.10 in alpha channel to pass tunnel configuration when triggering synthetics tests with tunnel feature.
> Release 0.10.10 alpha

- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/renderer.ts
Rendering of Multistep API results was not handled and made `datadog-ci` crash. This PR adds a simplistic interface definition as well as a specific description for multistep tests counting the number of requests it is composed of.
Closes: #177
> [synthetics] fix result rendering for multistep API tests

- package.json
- src/commands/synthetics/__tests__/tunnel.test.ts
- src/commands/synthetics/tunnel.ts
- src/commands/synthetics/websocket.ts
- yarn.lock
This PR does:
- bump `yamux-js` to version `0.0.4` to benefit from latest bug fixes preventing performing tunneled tests with files >100KB
- modify the websocket handler to be able to obtain the first message sent over the connection. Before this PR, we had a race-condition where the first message was already sent but the client did not register the event listener yet and the `once` (cf. [code](https://github.com/DataDog/datadog-ci/blob/9eae78e9d07ffca6c4a51145486a0e156455137d/src/commands/synthetics/tunnel.ts#L226)) callback was never called.
> [synthetics] improve tunnel connection and bump yamux-js

- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/renderer.ts
When using tunnel to run tests the location of the effective datacenter is currently shown, this PR changes this behavior to show `Tunneled` instead so the user knows the test went performed using the tunnel feature.
> [synthetics] update renderer to display tunneled location

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
Support new `defaultStepTimeout` option for Browser tests configuration overrides.
Add `defaultStepTimeout` to CI override options.
> [Synthetics][SW-952] Add override option `defaultStepTimeout` for Browser tests

- package.json
- src/commands/sourcemaps/upload.ts
Alpha release of https://github.com/DataDog/datadog-ci/pull/189
> [Alpha release] Use posix version of normalize when working with sourcemaps file paths.

- src/commands/sourcemaps/upload.ts
Using the "standard" version of normalize default to the current system.
We expect to have `/` in the path and not `\` to make it match with the URL.
Forcing the use of posix version seems to fix the issue. Tested on a Windows VM.
> Use posix version of normalize when working with sourcemaps file paths.

- package.json
- yarn.lock
Yamux 0.0.6 brings an improved protocol support with tracked window size which is required to improve synthetics tunnel support.
> [synthetics] bump yamux dependency

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/renderer.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
Improve visibility of tests not found by highlighting them and displaying them at the end of triggered tests list.
Add tests summary at the end of tests execution.
- Store "Test not found" error messages and display them at the end of `getTestsToTrigger()` with warn highlighting.
- Update `formatBackendErrors()` to render single errors inline.
Before:
After:
- Add tests execution summary with passed, failed, skipped and not found counts.
> [Synthetics] Add Tests Summary after execution, Better tests not found highlight

- package.json
Bump alpha channel to version 0.10.13-alpha with latest master merged in it
> [alpha] bump to version 0.10.13-alpha

- package.json
- testEnvironment.js
- yarn.lock
* Keep up with latest features in https://github.com/DataDog/dd-trace-js/releases/tag/v0.32.0.
* Bump `dd-trace` to `0.32.0`
> [ci-app] Bump `dd-trace`

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/run-test.ts
I need to run multiple suites in parallel, so we can reduce the number of tests per run.
But I still want to use a global configuration file.
Add a `--files`, `-f` parameter so you can override the glob pattern used by the global configuration file.
This way, I can run multiple suites using the same configuration on each run.
I also renamed the function `getTestsToTrigger` in the class, it was quite confusing to have two different functions using the same name in the same file.
> [synthetics] Add --files parameter

- src/commands/sourcemaps/README.md
- src/commands/sourcemaps/upload.ts
- Merge master in the alpha channel
- Keep git support enabled by default in the alpha channel
> Enable git support by default in the alpha channel

- src/commands/junit/README.md
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
We'd like to be able to select single XML files and not just folders.
* Allow single XML selection.
> [ci-app] Allow Single File Selection in `junit upload`

- package.json
- src/helpers/__tests__/ci-env/appveyor.json
- src/helpers/__tests__/ci-env/azurepipelines.json
- src/helpers/__tests__/ci-env/bitbucket.json
- src/helpers/__tests__/ci-env/bitrise.json
- src/helpers/__tests__/ci-env/buildkite.json
- src/helpers/__tests__/ci-env/circleci.json
- src/helpers/__tests__/ci-env/github.json
- src/helpers/__tests__/ci-env/gitlab.json
- src/helpers/__tests__/ci-env/jenkins.json
- src/helpers/__tests__/ci-env/travisci.json
- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
Improve support for CI providers and make sure we follow the spec.
* Add JSON files for each CI provider to assert we are extracting metadata correctly. This is based on the CI Spec in https://github.com/DataDog/datadog-ci-spec/tree/main/spec_tests. 
* Create tests for each file: https://github.com/DataDog/datadog-ci/pull/219/files#diff-bdab68b0d54fe06587bd7486f7b20e4da6d3ec0127f20806fa0096546de554e6R144-R148 
* Add support for remaining CI providers in `src/helpers/ci.ts`.
Additionally I've added this repository to our spec tests in https://github.com/DataDog/datadog-ci-spec/pull/95. 
The GHA in https://github.com/DataDog/datadog-ci-spec/blob/main/.github/workflows/spec_tests.yml checks whether the projects that are reading from CI providers' environment are homogeneous.
> [ci-app] Add More CIs and Improve Testing

- src/commands/sourcemaps/upload.ts
Include the human-readable message for the http error in the console, like this:
```
❌ Failed upload sourcemap for [src/commands/sourcemaps/__tests__/fixtures/too-big/file.js.map]: Request failed with status code 413 (Request Entity Too Large)
Command summary:
❌ Some sourcemaps have not been uploaded correctly.
Details about the 1 found sourcemap:
* 1 sourcemap failed to upload
```
> [sourcemaps] Display human-readable error message for http errors.

- src/commands/dependencies/__tests__/upload.test.ts
- src/commands/dependencies/metrics.ts
- src/commands/dependencies/upload.ts
Port changes from https://github.com/DataDog/datadog-ci/pull/225 to dependencies command.
> [dependencies] metrics flushing fix.

- src/commands/sourcemaps/renderer.ts
- src/commands/sourcemaps/upload.ts
Before that, command crashed because of git repository data attachment.
An improvement to this PR could be to fail the sourcemap if we cannot
decode it for git attachment, since it means it will be useless anyway.
> [sourcemaps] Avoid command crash when sourcemap is empty. 

- package.json
- yarn.lock
Bump aws-sdk, datadog-metrics and dd-trace to remove vulnerabilities in nested dependencies.
> [dependencies] bump aws-sdk, datadog-metrics and dd-trace

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
This PR provide the environment variable `HASH` filled with the hash part of the test url.
easier to review with white-space changes hidden: https://github.com/DataDog/datadog-ci/pull/239/files?diff=split&w=1
> [SW-1103] provide HASH env variable for url override

- package.json
This PR publishes the `datadog-ci` packet in version v0.11.11
🔖
> Publish v0.11.11

- src/commands/junit/__tests__/api.test.ts
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/api.ts
- src/commands/junit/renderer.ts
Use a function to make sure the file name we use to be stored in S3 is safe.
Also, improve rendered message when using a single file.
* Create `getSafeFileName`. 
* Render a slightly different name if the input is a single file.
> [ci-app] JUnit XML Upload – Use Safe File Names

- src/commands/sourcemaps/README.md
- src/commands/sourcemaps/upload.ts
This PR enables linktogit by default in the stable channel. It is already enabled in the alpha channel.
> Enable linktogit in the stable channel

- package.json
- yarn.lock
This would allow us to dogfood the latest features/bugfixes: 
* Better `git` metadata: https://github.com/DataDog/dd-trace-js/pull/1360
* Handle `jest` Timeouts: https://github.com/DataDog/dd-trace-js/pull/1361
* Parameterized tests: https://github.com/DataDog/dd-trace-js/pull/1345
> [ci-app] Bump `dd-trace` 

- src/helpers/__tests__/ci-env/circleci.json
- src/helpers/ci.ts
- src/helpers/interfaces.ts
- src/helpers/tags.ts
Update circle ci env vars extraction spec to have unique pipeline urls instead of repeating them in each job within a pipeline. 
* Update `ci.pipeline.url`
* Add `ci.job.name`
* Add `ci.job.id`
* Remove `ci.pipeline.number`
> [ci-app] Update CircleCI Env Var Tests

- src/commands/synthetics/tunnel.ts
The default value of `highWaterMark` used for tunneled  SSH stream buffers causes large network requests (> 2MB) to hang, increasing the stream buffer capacity prevent tunneled tests from failing due to never loading resources.
Relevant end-to-end tunnel tests will be present in datadog-ci tunneled Synthetics tests for the worker.
Increase the stream buffer size through  `highWaterMark` from the 32kb default to 255kb.
> [alpha][Synthetics] Tunnel: increase SSH stream `highWaterMark`

- src/helpers/__tests__/ci-env/circleci.json
- src/helpers/ci.ts
- src/helpers/interfaces.ts
- src/helpers/tags.ts
In https://github.com/DataDog/datadog-ci/pull/253 I added ci.job.id, but we didn't want it: it is only available in CircleCI and we are not using it anywhere, so it makes no sense to keep it.
* Remove `ci.job.id`
> [ci-app] Remove `ci.job.id` from CircleCI Env Var Extraction

- src/commands/synthetics/tunnel.ts
This PR denies traffic forwarding to the socket when an error occurs and it hasn't been accepted yet, this prevents hanging on DNS errors due to unresolvable hosts.
Reject forwarding on `error` or `close` when it hasn't been initiated yet and log a custom error message on unresolvable host error.
> [Synthetics] Tunnel: Reject SSH forwarding on socket error

- src/commands/synthetics/tunnel.ts
Only display `[Tunnel] Proxy opened for test ...` log once per test instead on every proxy connection to reduce output spam for browser tests.
> [Synthetics] Tunnel: Reduce `Proxy opened` log verbosity

- src/commands/synthetics/tunnel.ts
Running a dozen tunneled browser tests can easily exceed the default backlog size of 256 streams, resetting connections.
This PR increase the maximum size of the backlog.
Increase yamux backlog size from default of `256` to `2048`.
> [Synthetics] Tunnel: Increase yamux backlog size

- src/commands/synthetics/tunnel.ts
Merge tunnel fixes from `alpha` branch:
- https://github.com/DataDog/datadog-ci/pull/257: Increase SSH stream `highWaterMark`
- https://github.com/DataDog/datadog-ci/pull/261: Reject SSH forwarding on socket error
- https://github.com/DataDog/datadog-ci/pull/268: Increase yamux backlog size
> [Synthetics] Tunnel: Fix socket error forwarding and buffer/backlog sizes

- package.json
Ships this PR in the alpha channel: https://github.com/DataDog/datadog-ci/pull/264
The version was not incremented for the previous pre-release which is why it goes from `0.13.3-alpha` to `0.13.5-alpha` and why the `0.13.4-alpha` npm publish failed:
https://github.com/DataDog/datadog-ci/runs/2847174362?check_suite_focus=true
> New version 0.13.5-alpha

- src/commands/junit/api.ts
⚠️ **Do not merge**: Backend is not yet ready for this. 
* Compress `.xml` files before uploading them.
* Pipe file reading stream to `'zlib'`.
> [ci-app] Compress JUnit XML Report Files

- src/commands/sourcemaps/README.md
The api host is inferred from `DATADOG_SITE`.
https://github.com/DataDog/datadog-ci/blob/master/src/commands/sourcemaps/metrics.ts#L11:L11
https://github.com/DataDog/datadog-ci/blob/master/src/commands/sourcemaps/utils.ts#L23:L23
Remove the mention from the unused `DATADOG_API_HOST` from the readme.
> Remove mention of DATADOG_API_HOST

- src/commands/lambda/constants.ts
Allow customers to instrument functions that use the Node 14 runtime.
> Add support for Node 14.x Lambda runtime

- src/commands/lambda/README.md
- src/commands/lambda/__tests__/function.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/function.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/interfaces.ts
Allows users to set the `DD_LOG_LEVEL` environment variable of their Lambda functions by passing `--logLevel debug` to the `lambda instrument` command. This option is useful for seeing extra output from the Datadog Lambda Library and/or Lambda Extension for debugging purposes.
I also made some improvements to the README and reorganized the `calculateUpdateRequest()` function somewhat to be more readable.
> Add `--logLevel` option to `lambda instrument`

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-test.ts
- src/helpers/__tests__/utils.test.ts
- src/helpers/utils.ts
- Add `defaultConfig` to resolve the config one time and only use one source of truth (`this.config`)  
-  add `defaultConfig` function
> [command-synthetics] add defaultConfig and resolveConfig

- src/commands/sourcemaps/git.ts
The function `stripCredentials` which removes eventual HTTP auth credentials within URLs was not called.
It now is applied on the remote URL gathered.
> Sourcemaps Upload: use strip credentials on remote

- src/commands/junit/upload.ts
Using the junit command with a non-US1 endpoint isn't straightforward: the command will fail with a 403 error without any more context, and the CLI help doesn't mention anything about the DATADOG_SITE env var.
Added a new example that shows how to send data to EU1
> [ci-app] Improve help for non-US1 use cases

- src/commands/junit/README.md
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
It seems weird that you can only configure the api key and env through environment variables. This PR changes this.
* Add `--apiKey` input to `junit`.
* Add `--env` input to `junit`.
> [ci-app] Add `--env` Input to `junit` Command.

- src/commands/junit/README.md
- src/commands/junit/upload.ts
- src/commands/junit/utils.ts
It seems the env var used for referring to the datadog site is `DD_SITE` (at least more often than `DATADOG_SITE`, e.g. https://docs.datadoghq.com/getting_started/agent/#configuration).
Same can be said about `DD_API_KEY`.
This PR adds support for `DD_SITE` and `DD_API_KEY`
> [ci-app] Support `DD_SITE` and `DD_API_KEY`

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
Match tests variables definition rule to allow whitespace between variable name and brackets.
Update variable template regex.
> [synthetics] Allow spaces between variable brackets

- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
Add a log to warn when reserved namespace for `startUrl` template variables are present in environment variables. 
This is to explicitly communicate the behavior of overriding them with parsed URL parts.
Log this message when reserved names are detected in environment variables:
```
Detected HASH, DOMAIN environment variables. HASH, DOMAIN are Datadog reserved variables used to parse your original test URL, read more about it on our documentation https://docs.datadoghq.com/synthetics/ci/?tab=apitest#start-url. If you want to override your startUrl parameter using environment variables, use different namespaces.
```
> [synthetics] Add warning on reserved environment variable names

- LICENSE-3rdparty.csv
- package.json
- src/commands/junit/__tests__/fixtures/invalid.xml
- src/commands/junit/__tests__/fixtures/java-report.xml
- src/commands/junit/__tests__/fixtures/subfolder/js-report.xml
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/renderer.ts
- src/commands/junit/upload.ts
- yarn.lock
Validate jUnit XML before uploading:
* We skip uploading useless files.
* We signal to the user that they're doing something wrong.
* Add new dependency `fast-xml-parser`.
* Check that the file is valid XML by using `fast-xml-parser`.
* Check that the root of the XML includes a `testsuite` tag.
> [ci-app] Simple JUnit XML Validation

- README.md
Especially in the case of `dsyms upload`, our users won't have `package.json` or an NPM project.
They basically need `datadog-ci` as a CLI tool.
They can install `datadog-ci` globally via `npm` or `yarn`.
This can be obvious for JS devs but I think mentioning that in Readme can help iOS devs a lot.
> Global installation added to Readme

- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/function.ts
- feat: Honor lambda state in instrument method
- feat: double escape quotes to pass snapshots
This PR verifies that the function can be updated, which according to this [post](https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/) is when the `State` is `Active` and `LastUpdateStatus` is `Successful.
When we fetch the function configuration, this is attribute is returned. Because this command is likely ran in CI, immediately after updating a function, we will try 3 extra times if the first state is not valid, with exponential backoff between attempts.
I believe _all_ function configurations return `State` and `LastUpdateStatus`, but I've included a guard clause in cause. To be removed 1 Oct 2021, as per comment and schedule.
> Honor lambda states (optional now, rolled out everywhere in September)

- src/commands/lambda/constants.ts
Add support for the Python 3.9 runtime for the Lambda instrument command.
> [lambda] Add Python 3.9 runtime support

- src/commands/commit/README.md
- src/commands/sourcemaps/README.md
Update the readme of the sourcemap upload command so the [link errors with source code feature](https://docs.datadoghq.com/real_user_monitoring/error_tracking/browser_errors/#link-errors-with-your-source-code) feature is more documented and less confusing to users.
The commit upload command readme was updated as well.
> Update README with more details on git usage

- package.json
- src/commands/synthetics/tunnel.ts
- yarn.lock
Reduce remote server connections timeout and end associated tunneled connections when they occur to improve remote server timeouts handling.
- Upgrade `ssh2` to v1.3.0
- Reduce remote socket timeout to 30s
- Replace `pipe` with `pipeline` for packet forwarding and multiplexer
- Revert to rejecting forwarding on DNS errors
> [alpha][Synthetics] Tunnel: Improve connections timeout handling

- package.json
Release `0.16.2-alpha`
- https://github.com/DataDog/datadog-ci/pull/336
> [alpha] `0.16.2`

- package.json
- src/commands/synthetics/tunnel.ts
- yarn.lock
Reduce remote server connections timeout and end associated tunneled connections when they occur to improve remote server timeouts handling.
- Upgrade `ssh2` to v1.3.0
- Reduce remote socket timeout to 40s
- Replace `pipe` with `pipeline` for packet forwarding and multiplexer
- Revert to rejecting forwarding on DNS errors
> [Synthetics] Improve Tunnelled connections timeout handling

- src/helpers/__tests__/utils.test.ts
- src/helpers/utils.ts
With this change, proxy conf set by HTTPS_PROXY should be handled correctly for any call sent through getRequestBuilder(), unless support of env var is explicitly disabled in the options of getRequestBuilder.
In that sense, the semantic of the option disableEnvironmentVariables has slightly changed. Before this commit, `disableEnvironmentVariables:true` meant HTTPS_PROXY support was disabled, and `disableEnvironmentVariables:false` meant HTTPS_PROXY support was enabled but bugged.
Now the option disableEnvironmentVariables is still used to disable HTTPS_PROXY support, except that when HTTPS_PROXY support is enabled, it works as expected, leveraging the proxy-from-env library (through proxy-agent library).
We always set an httpsAgent and an httpAgent to proxy-agent's `ProxyAgent`.
The `new …
> Fixes support of proxies through HTTPS_PROXY env var.

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
- Display critical errors and timedout in summary to improve readability
> [synthetics-command] display critical errors and timedout in summary

- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- Fix assertion failure and unhealthy runs render
- Update result rendering to support `failure` field in results, or fallback to deprecated `errorMessage` and `errorCode`
Only render `result.error` if `result.failure` and `result.errorMessage` are not defined.
Read errors from `result.failure` before falling back to `result.errorMessage`
> [Synthetics] Use `result.failure` field, Fix run errors reporting

- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/mock-configs/no-functions.json
- src/commands/lambda/instrument.ts
CLI not working with the following configuration file.
```
{
"lambda": {
"layerVersion": 60,
"extensionVersion": 10,
"functions": ["arn:aws:lambda:ap-southeast-1:601427279990:function:tian-test-ci-extension"],
"region": "ap-southeast-1"
}
}
```
There was a condition that checked if the functions array was empty, but if you specified a config file, it won't bother to check the config functions array.
Adding a ternary conditional to specify the functions array.
> Fix datadog-ci not working with configuration file

- .github/CODEOWNERS
It removes `@m-rousse` from the `src/commands` folder CODEOWNERS as it is not relevant anymore to be notified for all commands PRs.
> [codeowners] @m-rousse from commands codeowners

- src/commands/lambda/__tests__/function.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/function.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/interfaces.ts
To demonstrate the full capabilities of Datadog serverless monitoring, we should provide options for customers to easily tag their applications, like --service, --env, --version and --extra-tags.
If the customer misses one of --service, --env, --version tags, we should print out a message to encourage users to set them up.
Add four commands as described above, modified some tests to comply with new feature, and created unit tests for the feature.
> Datadog CLI sets default for unified service tagging

- package.json
- yarn.lock
Upgrade to latest version of `yamux-js` [updating `on('error')` events](https://github.com/th-ch/yamux-js/blob/cffa837d3f5861d6b5a4bf1f6d9c722e11587448/changelog.md#010) to fix issue with ssh2 error listeners expecting an `Error` object.
Upgrade `yamux-js` from 0.0.6 to 0.1.0.
> [Synthetics] Upgrade `yamux-js` to 0.1.0

- src/commands/dsyms/__tests__/utils.test.ts
- src/commands/dsyms/renderer.ts
- src/commands/dsyms/upload.ts
- src/commands/dsyms/utils.ts
In the case of invalid dSYM files, dwarfdump can throw.
This resulted in breaking the execution.
Now we continue running by skipping that particular dsym files.
> RUMM-1608 Dsym upload: if dwarfdump throws, error is caught

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-test.ts
This feature was requested by front-end teams to spread tests over DCs 
- Add `DATADOG_LOCATIONS` env variable (not SYNTHETICS_LOCATIONS because it is not consistent with the rest)
> [synthetics-command] Add DATADOG_LOCATIONS env variable to override locations

- src/commands/lambda/README.md
The documentation online parses `--` into its pure form `–`, therefore, users might be prone to understand it as `-`, which could cause problems while using the CLI.
Update the documentation by adding ``` ` ``` before and after every command.
No test required.
> [lambda] Minor documentation update

- src/commands/synthetics/reporters/default.ts
[SW-1456](https://datadoghq.atlassian.net/browse/SW-1456)
- added ci query parameter to the result URL of a healthy test result to link to the result page
> added a ci query param to the result url of tests

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/reporters/junit.ts
When trying to create a jUnit report in a directory, it's not working if the directory in question doesn't exist.
Also, when reporting errors, new steps where overwriting over previous steps.
- First create the directory.
- Push errors instead of overwriting the full array.
Published in `0.17.2-alpha`
> [s8s] Create junit report even in directory

- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
Currently, the jUnit report doesn't consider timeouts as errors in its reporting.
- Type errors
- Catch timeouts as errors in the reporting
> [s8s] Fix jUnit report with Timeout errors

- src/helpers/__tests__/ci-env/gitlab.json
- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
More context in the spec update: https://github.com/DataDog/datadog-ci-spec/pull/144
* Use `CI_COMMIT_REF_NAME` for branch instead of `CI_COMMIT_BRANCH`
> [ci-app] Fix Gitlab Branch Extraction

- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/reporters/junit.ts
We should not report step's error as an `<error>` if the step is `allowFailure=true` because, the test may be reported as failing, when it's not.
Add a new `<allowed_error>` to the report, so we keep reporting them, without marking the test as failing.
> [s8s] Add allowed_error to the report

- src/commands/sourcemaps/README.md
Update the readme to match the flag https://github.com/DataDog/datadog-ci/blob/master/src/commands/sourcemaps/upload.ts#L321
> Fix sourcemap README.md

- src/commands/junit/upload.ts
- src/commands/trace/interfaces.ts
- src/commands/trace/trace.ts
- src/helpers/__tests__/retry.test.ts
- src/helpers/retry.ts
- src/helpers/upload.ts
- Adds error messages and exit code to the payload for custom spans
- Adds retries to HTTP intake for the trace command
The upload code in the utils package has been refactored into a retry package to have a common retry policy among commands. The trace command as well as the source code integration commands and the junit commands are now using this common retry logic.
> [ci-app] Capture error message

- src/commands/lambda/README.md
This PR adds a section about the source code integration flag to the README.
> SLS-1540: Add source code integration comments

- src/commands/sourcemaps/README.md
This is an attempt at improving the documentation, so that it's easier to understand the goal of the `--project-path` argument.
- Rework the wording
- Add a sub-section to the _Link errors with your source code_ section to mention the `--project-path` argument, with an usage example
> [sourcemaps] Rework wording and add example for --project-path

- package.json
- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/__tests__/functions/instrument.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/functions/instrument.ts
- src/commands/lambda/functions/uninstrument.ts
- yarn.lock
Refer to [SLS-1390](https://datadoghq.atlassian.net/browse/SLS-1390)
Refactor `getLayerArn` and `getExtensionArn` to support this feature, and move them into `commons.ts`.
Moved tests to their corresponding file, and added some more according to the feature.
> [lambda] support ARM layers

- src/commands/lambda/README.md
Adds the documentation for the [DataDog/datadog-ci#420](https://github.com/DataDog/datadog-ci/pull/420/).
Done in a separate PR to avoid docs being ahead of releases.
Modifying the readme for this repo.
Also, updated examples for the keys to a more standardized one, as set [here](https://docs.datadoghq.com/getting_started/database_monitoring/#install-the-example-application).
> [lambda][docs] Add docs for Secrets Manager

- src/commands/lambda/__tests__/functions/instrument.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/functions/instrument.ts
Add `us5.datadoghq.com` to the supported sites array.  Since it wasn't there.
Moving the sites' array to `constants.ts` and add `us5.datadoghq.com`. 
Also fixed test to comply with the supported sites.
> [lambda] Add `us5.datadoghq.com` support

- README.md
Command has been released and is used here: https://docs.datadoghq.com/integrations/guide/source-code-integration.
> Add git-metadata command to main README

- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/instrument.ts
Currently, we were just accepting string booleans for `mergeXrayTraces`, `flushMetricsToLogs`, and `tracing`. If the user specified a boolean in the config file for such fields, it would crash because there is no `.toLowerCase()` method for booleans. 
Coerce booleans to avoid an error when user specifies a value of type `boolean|string` for `mergeXrayTraces`, `flushMetricsToLogs`, and `tracing`.
Created a function to coerce booleans: `coerceBoolean`.
Add tests and fix current ones.
> [lambda] Coerce boolean for `mergeXrayTraces`, `flushMetricsToLogs`, and `tracing`

- src/commands/lambda/__tests__/functions/instrument.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/functions/instrument.ts
The variable `DD_FLUSH_TO_LOGS` was being set to true as fallback, but we didn't skip it if the Extension Layer was being used, this was unexpected behavior.
Skip adding the Environment Variable `DD_FLUSH_TO_LOGS` when the Extension Layer is being used. 
Remove the variable from the tuple array in which it was set, add a condition to see if the user is adding the Extension Layer.
Added a test and updated existing ones.
> [lambda] Skip DD_FLUSH_TO_LOGS when Extension Layer is being used

- src/commands/git-metadata/upload.ts
If no git metadata is available we should consider the command run as a
failure.
Fixes #426
> [git-metadata] Upload returns 1 when no git metadata available.

- src/commands/git-metadata/upload.ts
Switches the `git-metadata` command to the v2 endpoint.
Previously done for the `sourcemaps` command: https://github.com/DataDog/datadog-ci/pull/314/files
> [git-metadata] switch to v2 endpoint

- src/commands/lambda/README.md
Add proper documentation for uninstrument command, it is separate from its PR in order to merge once released. Refer to [DataDog/datadog-ci#374](https://github.com/DataDog/datadog-ci/pull/374)
Modifying the `readme.md` of the lambda command folder.
> [lambda][docs] Add documentation for uninstrument command

- src/commands/junit/upload.ts
- src/commands/trace/api.ts
- src/helpers/__tests__/ci.test.ts
- src/helpers/__tests__/user-provided-git.test.ts
- src/helpers/ci.ts
- src/helpers/user-provided-git.ts
Rename `getXXXMetadata` to `getXXXSpanTags` to enhance readability because we mixed Metadata (structured) and SpanTags (unstructured) .
> [ci] rename getXXXMetadata to getXXXSpanTags

- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/uninstrument.ts
Standardized how errors are displayed and handled within the lambda-ci commands. 
[SLS-1907](https://datadoghq.atlassian.net/browse/SLS-1907)
- Previously, Errors were displayed in one of the following two ways:
- [Error] Error Message (where the [Error] tag is displayed in red)
- Error Message
- Standardized all error messages in the instrument and uninstrument commands to be a red [Error] tag, followed by the error message itself.
> [lambda] Standardize lambda-ci error messages/handling

- README.md
- src/commands/junit/README.md
- src/commands/trace/README.md
Link to `trace` and `junit` commands from the main README. They were hidden but they are production ready now, so they shouldn't be.
> Update README for ci-visibility Commands

- src/helpers/git.ts
* Stick with the correct format.
* Change `git` Committer/Author Dates format to ISO 8601
We simply use `%aI` and `%cI` to get strict ISO 8601 format: 
https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-emaIem
> [ci-visibility] Change git Committer/Author Dates format to ISO 8601

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
We are deprecating the "URL variables" mechanism (using `PROTOCOL`, `DOMAIN`, etc.) in favor of `startUrlSubstitutionRegex` which is a more powerful mechanism and which is compatible with variables predefined in the start URL). Another alternative can also be to use variables in the original definition of a test and to override those variables when triggering those tests with `datadog-ci`.
> Deprecate URL variables in favor of `startUrlSubstitutionRegex`

- src/commands/git-metadata/__tests__/git.test.ts
- src/commands/git-metadata/__tests__/library.test.ts
- src/commands/git-metadata/git.ts
- src/commands/git-metadata/index.ts
- src/commands/git-metadata/library.ts
- src/commands/git-metadata/sci.ts
- src/commands/git-metadata/upload.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/instrument.ts
- src/commands/synthetics/crypto.ts
- src/index.ts
- yarn.lock
This PR adds a few custom functions for uploading git-metadata and allowing use in a library instead of as a CLI. Serverless needs this functionality to use as part of other deployment-related libraries, such as datadog-cdk-constructs, datadog-serverless-plugin, etc.
This PR duplicates and simplifies some functionality. I didn't want to refactor the datadog-ci code because I did not want to break datadog-ci for our users, so I re-used some of the code and made changes to it so that it could be used as a library instead of CLI. The majority of this work was making parameters arguments to functions instead of getting them from the environment. We also want it to silently fail in the case that `git` was not installed (as `git` is not a requirement for our deployment tools). In that case, it …
> Add git-metadata to exports for datadog-ci

- .github/PULL_REQUEST_TEMPLATE.md
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
Provide new `trigger_app` metadata to Synthetics test batches.
- Add a new `trigger_app` to Synthetics tests batch Metadata only, defaulting to `npm_package`
- Expose `setCiTriggerApp()` to allow integrations to provide custom values
- Update `PULL_REQUEST_TEMPLATE.md` with reminder check for Github Action releases (↓)
> [Synthetics] Add `trigger_app` property to batch metadata

- README.md
We still need to release and test this internally before promoting it to customers.
Remove note about standalone binary from README.
> Standalone binary for `datadog-ci`: Remove from readme

- src/commands/lambda/README.md
The datadog ci was updated to support additional runtimes. The current readme says that only Node and Python are supported which is no longer accurate.
Updated readme to include .NET, Go, Java and Ruby
> [Serverless] Update list of supported runtimes for lambda commands

- package.json
Since https://github.com/DataDog/datadog-ci/pull/476, `@types/datadog-metrics`' `BufferedMetricsLogger` is now indirectly exported by `datadog-ci` ts definitions.
<details>
<summary>Import chain</summary>
https://github.com/DataDog/datadog-ci/blob/bb286e649a8784e5381b0cdba1ff987ad0391115/src/helpers/apikey.ts#L3 https://github.com/DataDog/datadog-ci/blob/bb286e649a8784e5381b0cdba1ff987ad0391115/src/helpers/apikey.ts#L14-L20 https://github.com/DataDog/datadog-ci/blob/1c00c9ea0cb0838fd540ad3e6531ea004f23876d/src/commands/git-metadata/library.ts#L19-L20 https://github.com/DataDog/datadog-ci/blob/0e735fe57eb7a010f1ed3ec9c83bc5d7a9bff5f5/src/index.ts#L1
-----
</details>
However since `@types/datadog-metrics` is not defined in the project `dependencies`, any build of a Typescript project …
> [dep] Move `@types/datadog-metrics` to project dependencies

- .github/workflows/ci.yml
- .github/workflows/release.yml
- LICENSE-3rdparty.csv
- package.json
- standalone-e2e/standalone-binary.test.ts
- yarn.lock
It seems `nexe` requires the app to be packaged before bundling the executable. That means using `ncc` or `rollup` (more context on https://github.com/nexe/nexe/issues/717#issuecomment-724725113). The reason why we didn't catch this testing is that the tests were run in the project folder. The binary created by `nexe` required the javascript files of the project. This made it fail miserably when tested outside. 
`pkg` on the other hand seems to work out of the box without extra configuration or the need to use a bundler like `ncc` or `rollup`. 
Tested in https://github.com/DataDog/datadog-api-client-python/pull/869 and https://github.com/DataDog/dd-trace-js/pull/1894
* Use `pkg` instead of `nexe`.
* Make sure standalone binary tests *do not* require local files (by removing them before …
> Standalone Binary: Use `pkg` instead of `nexe`

- src/commands/lambda/__tests__/functions/instrument.test.ts
- src/commands/lambda/__tests__/functions/uninstrument.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/prompt.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/prompt.ts
- src/commands/lambda/uninstrument.ts
1. Log the actual error when max retries exceeded when pulling the list of Lambda functions
2. Decouple the interactive mode prompt for AWS region and credentials into separate asks. Because it's possible that one is configured while the other not.
3. In the interactive mode, always ask the user to specify (or confirm the default) aws region.
The original issue is that when running the `lambda instrument -i` in interactive mode, the default AWS region configured by the users may not always be correctly detected by the ci. Even when region not detected, the ci continues and throws a max retries error (now it logs the actual error msg). We can fix this by improving the logic to detect the default region, but I realized that a better fix is to **always** ask the user to specify the AWS …
> [lambda instrument] Always ask for region in interactive mode

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/command.ts
- src/commands/synthetics/errors.ts
- src/commands/synthetics/index.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
Improve Synthetics command output to make suite of action clearer, update `failOnCriticalErrors` to also fail on any client errors (config/connection errors, and HTTP response errors except "Test not found" which never result in a critical error).
- Change `CriticalError` scope.
`CriticalError` are errors triggering a non-0 command exit when `failOnCriticalErrors` is set, they were scoped to `5xx` server responses only and now include all unexpected errors during tests fetch / trigger / result polling / tunnel setup (with the exception of `404` on tests not found, that will never fail the command).
- Add a message when `failOnCriticalErrors` is `false` and a critical error occured to exit command with 1, add option to the readme.
- Replace test fetched messages to make it clearer that the …
> [Synthetics] Update `failOnCriticalErrors`, Improve command output

- .github/workflows/ci.yml
- .github/workflows/release.yml
- standalone-e2e/standalone-binary.test.ts
Jobs in https://github.com/DataDog/datadog-ci/actions/runs/1997744883 are failing because the path of the executable for the standalone binary tests is wrong. I fix it with this PR.
Change `STANDALONE_BINARY` so that it is actually the correct name.
> Fix Release Script

- .github/workflows/release.yml
Macos release is broken in the latest release: https://github.com/DataDog/datadog-ci/runs/5641538045?check_suite_focus=true. There was a typo in the release script.
I uploaded the binary manually to fix this specific release, but this PR should make fix it permanently. 
Fix release script.
> Fix standalone binary darwin release

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/utils.ts
Move trigger app from metadata to request headers.
Also fixes the extra line break before `Waiting for results` if no tests are skipped.
Deprecate passing `trigger_app` through a batch `metadata` property in favor of passing it as a request `X-Trigger-App` header (trigger endpoint only).
> [Synthetics] Pass `trigger_app` as request header

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/command.ts
- src/commands/synthetics/errors.ts
- src/commands/synthetics/run-test.ts
Display a specific error message for invalid credential on fetch/trigger test endpoints.
```
ERROR: authorization error
Credentials refused, make sure `apiKey`, `appKey` and `datadogSite` are correct.
```
Throw new `AUTHENTICATION_ERROR` critical error on 403 responses with appropriate message.
> [Synthetics] Detect authentication errors on fetch/trigger test endpoints

- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/functions/commons.ts
https://datadoghq.atlassian.net/browse/SLS-2109
`datadog-ci lambda instrument -i` didnt check for aws credentials in `~/.aws/credentials` and only looked for [environment variables](https://docs.datadoghq.com/serverless/installation/python/?tab=datadogcli#:~:text=gov.com%0Aexport-,AWS_ACCESS_KEY_ID,-%3D%22%3CACCESS%20KEY%20ID) before prompting the user to enter their credentials.
Add some functionality to check for aws creds in `~/.aws/credentials` by calling aws-sdk's config.credentials. One downside is config.credentials returns an object like: 
As you can see it exposes aws_access_key_id but the secret key is never returned in an object. I don't think this is a security concern since the secret key isn't the one being returned to that object but I figured I would bring it up if there …
> Check for aws credentials in ~/.aws/credentials as well as environment variables in interactive mode

- src/commands/junit/README.md
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/api.ts
- src/commands/junit/interfaces.ts
- src/commands/junit/upload.ts
This is a new flag to opt in to send logs from junit XML imports. We need a way to opt in as logs have an additional cost.
There is a new internal tag `_dd.junitxml_logs` that is already being read in the backend.
> [CIAPP-3830] Add internal tag to junit upload to enable logs collection

- .github/CODEOWNERS
Update repository codeowner to `@DataDog/datadog-ci` team.
> [github] Set `@DataDog/datadog-ci` as repo codeowners

- src/commands/synthetics/reporters/junit.ts
Export junit report TS type. Will be useful to import in web-ui for type safety of report handling
> [synthetics] Export XMLJSON type from junit reporter

- src/commands/synthetics/README.md
Fix wrong documentation of `failOnCriticalErrors` as a test level config, update it to reflect its actual usage as a command level flag or a global config option.
> [Synthetics] Fix documented usage `failOnCriticalErrors` in README

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
Use `DATADOG_SYNTHETICS_CI_TRIGGER_APP` env var for `trigger_app` to allow third party integrations to specify it when not using the datadog-ci API.
Default `triggerApp` to `DATADOG_SYNTHETICS_CI_TRIGGER_APP`, can still be overridden through `setCiTriggerApp()`.
> [Synthetics] Use environment variable value for `trigger_app` when present

- package.json
- yarn.lock
Updated `ssh2` to 1.9.0 which updates `cpu-features` to 0.0.4. That addresses #514.
Upstream dependency no longer crashes on M1.
> Updated ssh2 to 1.9.0. Fixes #514.

- src/commands/junit/__tests__/upload.test.ts
- src/helpers/tags.ts
Fixes #521. Currently tags with values that contain `:` aren't properly split.
Instead of splitting on `:` which ignores anything after the second occurrence of `:`, we find the first instance of `:` and set the key to be everything before it and the value to be everything after it.
> Updating tag split

- .github/CODEOWNERS
The `synthetics` command is owned by Synthetics Worker, no need to have me specifically notified.
> [codeowners] remove m-rousse from codeowners

- src/commands/synthetics/utils.ts
- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
This PR adds truncation of the git commit message that is retrieved when triggering synthetics tests through datadog-ci.
This fixes an issue where CI invocations of the command when done with a git commit message of over 1500 chars could make the API call fail with a 400 error.
This PR adds an optional argument to the helper used to retrieve CI metadata to pass per-tag size limit.
> [synthetics] truncate git commit message length to 500 chars

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/errors.ts
- src/commands/synthetics/run-test.ts
This PR improves the display of critical errors by adding the `error.message` into the `CriticalError`.
A new optional message property is added to the `CriticalError` constructor. It is optional because we don't always have an `error.message` to pass to the constructor, and for such errors we [directly log a message in the reporter](https://github.com/DataDog/datadog-ci/blob/67e99c912f525bbd1556fd8ca3d6411674e171a9/src/commands/synthetics/command.ts#L186-L214).
> [s8s] Fix critical error message display

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/command.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
Preliminary PR to prepare the batch endpoint. A review commit by commit is advised.
This PR is split into 4 commits:
1. Stop typing `APIHelper` and infer from actual typings
2. Stop passing `failOnCriticalErrors` and `failOnTimeout` everywhere to get the "status" of a result. This is done by adding a property `.passed` at the root level of the result object, that takes into account those two parameters.
3. Simplify `waitForResults` output and handling of results afterwards:
- return a flat list of results
- clearly separate `PollResult` (what's returned by the API) from a new object `Result` which the object we built internally that contains all the fields necessary from the start. Also type `Result.result` as `ServerResult` to indicate the part of `Result` that is directly given by the …
> Code refactoring to prepare batch endpoint

- package.json
- yarn.lock
This PR bumps axios to version 0.21.4 to fix https://github.com/DataDog/datadog-ci/issues/549
> [deps] bump axios to 0.21.4

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/run-test.ts
Currently, when a test is triggered with the `--public-id` (or `-p`) flag, only the locations set in the `global` config of the `datadog-ci.json` file are taken into account. The locations set with the env variable `DATADOG_SYNTHETICS_LOCATIONS` are ignored.
This PR fixes this issue:
* If locations are defined with the env variable, they are used.
* Otherwise, the locations from the `global` config are used.
When creating the config for tests triggered by public-id, we override the `locations` property defined in the `global` config with the `locations` from the `config`, which were retrieved from the `DATADOG_SYNTHETICS_LOCATIONS` env variable in the `command -> resolveConfig` method.
> [synthetics] Use locations env var for tests triggered with -p flag

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/command.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
Improve datadog-ci Synthetics command output.
- Don't display skipped steps following critical failed step in Browser test results (replace with `⇢ | X skipped steps`)
- Display batch URL above summary
- Stop displaying override count on skipped tests
> [Synthetics] Update command output: Add batch URL, ignore skipped step

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/utils.ts
Stop supporting deprecated `errorMessage` & fix late result failure display.
- Stop supporting `errorCode` & `errorMessage` in favor of relying exclusively on `failure` object
- Fix failed results received after timing out still displaying their original failure, the original failure is now discarded
> [Synthetics] Remove support for deprecated `errorMessage`

- src/commands/synthetics/__tests__/fixtures.ts
Update test fixture after merge (remove deprecated `error` property)
> [Synthetics] Update typing in test fixture

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/reporters/default.ts
Fix display of timed out results for browser tests by reporting the `failure` for results with `stepDetails`
> [Synthetics] Fix Browser result timeout display in timed out tests

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
If the command reaches `pollingTimeout` (`hasExceededMaxPollingDate = true`), all result are currently force-failed and marked as timed out due to this condition:
https://github.com/DataDog/datadog-ci/blob/2097278e942f571d8ae8f79635b7f5f795283b88/src/commands/synthetics/utils.ts#L342
This PR adds a check on `resultInBatch.timed_out !== false` to ensure results marked as timed out were not received when the batch was last polled. Tests needed to be updated to not set `timed_out: false`.
Also removes the extra 5s wait on last poll in `waitForResults()` by switching `wait` and `processBatch` so that polling does:
```
processBatch()
wait()
processBatch()
wait()
processBatch()
```
instead of:
```
processBatch()
processBatch()
wait()
processBatch()
wait()
```
> [Synthetics] Fix wrongfully timed out results

- src/commands/dsyms/interfaces.ts
- src/commands/git-metadata/interfaces.ts
- src/commands/sourcemaps/interfaces.ts
This migrates the `sourcemaps`, `dsyms` and `git-metadata` commands to the new format of the API endpoint used to upload files.
The new format must contain all JSON-encoded metadata as a single part of the request named `event`, and each attachment in a separate part, with an appropriate `filename`.
> Use intake v2 format for sourcemap, git-metadata and dsym uploads

- src/commands/react-native/__tests__/interfaces.test.ts
- src/commands/react-native/interfaces.ts
This migrates the React Native sourcemaps upload command to the v2 API endpoint. (other commands have been migrated in https://github.com/DataDog/datadog-ci/pull/560).
> Use intake v2 for react-native sourcemaps uploads

- package.json
This PR releases version 1.9.0, containing:
- `react-native upload` command for react native sourcemaps
- use intake v2 for dsyms, sourcemaps and git-metadata
- remove `host:ci` from metrics for dsyms, sourcemaps and git-metadata
- support for Azure DevOps extensions
> Publish v1.9.0

- src/commands/lambda/README.md
Fix a typo. Comment is inconsistent with the command. Noticed by a translator on the public docs site.
Change "Instrument" to "Uninstrument"
> Fix a copypasta typo

- src/commands/tag/tag.ts
Increase the backoff when we do retries to the custom tags endpoint as some customers that send a lot of them may be hitting the rate limit and the to fast retries is making it worse as it not gives enough time for the rate limit threshold to refresh.
Increasing the initial backoff time
> Better back of for tags rate limit

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/junit.ts
This PR adds a `batch_id` property to the `testsuites` element's attributes of a JUnit report.
The `batch_id` property needs to be an attribute, part of the `testsuites` element (and not `testsuite` or `testcase`) because if multiple suites are run (e.g. multiple test config files are loaded), the suites' tests will be flattened and all run in the same batch.
> [SW-2256] Add batch_id to the junit report

- package.json
This PR bumps version to 1.12.0, with this proposed changelog:
* Add xcode command to upload sourcemaps automatically in React Native by @louiszawadzki in https://github.com/DataDog/datadog-ci/pull/548
* Enable specifying API key and site from datadog-ci.json for dsyms command by @louiszawadzki in https://github.com/DataDog/datadog-ci/pull/580
* Universal instrumentation for Java and .NET including .NET6.0 by @nine5two7 in https://github.com/DataDog/datadog-ci/pull/556
> Release v1.12.0

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/reporters/junit.ts
Include all summary data in JUnit reports by adding new properties to `testsuites`.
Introduce new `testsuites` properties:
- `tests_critical_error`
- `tests_failed`
- `tests_failed_non_blocking`
- `tests_not_found`
- `tests_passed`
- `tests_skipped`
- `tests_timed_out`
> [Synthetics] JUnit reporter: Add summary data to `testsuites` properties

- src/commands/metric/README.md
> Remove beta warning of metric command

- src/commands/sourcemaps/__tests__/upload.test.ts
- src/commands/sourcemaps/upload.ts
This improves the validation of the `--minified-path-prefix` parameter.
Today, passing something like `warn: unrelated log line\nhttps://example.com/statix/js` passes the validation, while it shouldn't.
This can be an issue if the output of a command (with unexpected logs in stdout) is passed to this parameter.
Instead of requiring the parsed URL to have a `protocol` (we have a test weirdly testing the opposite, which I suspect is accidentally passing because of the leading slash), require it to have a host.
`warn: unrelated log line\nhttps://example.com/statix/js` is being parsed without error by [`new URL`](https://nodejs.org/api/url.html#new-urlinput-base), but gives an almost empty URL with only a protocol.
Checking that the `host` is present should filter out this case, and should …
> [sourcemaps] Require minified URL to have a host, or leading slash

- src/commands/git-metadata/__tests__/library.test.ts
- src/commands/git-metadata/library.ts
https://github.com/DataDog/serverless-plugin-datadog now has a dependency on datadog-ci for uplaoding git-metadata. The serverless plugin must know the current repository URL to be able to tag serverless functions with `git.repository_url`.
Returns the repository URL in `uploadGitCommitHash`.
> Update uploadGitCommitHash to return the current repo URL

- package.json
Bumps version to 1.13.0. Changelog:
- [Synthetics] JUnit reporter: Add summary data to testsuites properties by @lefebvree https://github.com/DataDog/datadog-ci/pull/591
- [ci-visibility] Update CI env vars metadata extraction by @juan-fernandez https://github.com/DataDog/datadog-ci/pull/597
- [sourcemaps] Require minified URL to have a host, or leading slash by @rpelliard https://github.com/DataDog/datadog-ci/pull/596
- [git-metadata] Return repository remote in exported `uploadGitCommitHash` by @jybp https://github.com/DataDog/datadog-ci/pull/577
> Release v1.13.0

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/api.ts
This PR allows the retry mechanism to also work on HTTP 404 responses for both `getBatch` and `pollResults` API endpoints.
Make the retry policy function configurable by adding a new parameter to the `retryRequest` function: `retryPolicy`.
> [SW-2292] Retry getBatch and pollResults request on HTTP 404 as well

- src/commands/sourcemaps/__tests__/upload.test.ts
- src/commands/sourcemaps/__tests__/utils.test.ts
- src/commands/sourcemaps/interfaces.ts
- src/commands/sourcemaps/renderer.ts
- src/commands/sourcemaps/upload.ts
- src/commands/sourcemaps/utils.ts
- src/commands/sourcemaps/validation.ts
The PR adds a warning in the output when the `--minified-path-prefix` flag may have been misused.
We've had several tickets already where unminification wasn't working because customers uploaded sourcemaps with the wrong flag value which might not be easy to spot at first glance. The outputs were as such:
```
Uploading sourcemap build/static/js/abc.chunk.js.map for JS file available at https://my-website.com/static/js/static/js/abc.chunk.js
``` 
After this PR, launching the following command:
```
$ yarn launch sourcemaps upload ./src/commands/sourcemaps/__tests__ --service my-service --minified-path-prefix https://static.datadog.com/fixtures/basic --release-version 1.2
```
will now output the following warning:
```
⚠️ The --minified-path-prefix flag value …
```
> [sourcemaps] Detect --minified-path-prefix misusage

- src/commands/react-native/xcode.ts
Using `${indexFilePath}/..` would return ENOTDIR when trying to spawn the bundle script, so I removed last part of the path instead.
I could have also used `.replace('/index.js', '')` but I think this solution is more robust if the name of the "main" file changes.
Require.resolve cannot be mocked by jest, and I don't think it is worth adding `react-native` as a dependency to this project.
I could not find a way to unit testing this in a way that prevents potential bugs, so I added a comment instead.
> Fix React Native path in xcode command

- package.json
This PR bumps the package to version 1.13.3, releasing:
- [Fix React Native path in xcode command](https://github.com/DataDog/datadog-ci/commit/f0232e035f53a0ae5a0f0fe0870ec0e9e2bc7aaf)
- synthetics: Rename `getPresignedURL` to `getTunnelPresignedURL`
- synthetics: Add getTunnelPresignedURL endpoint
> Bump v1.13.3

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
- Rename `getTest` to `getTestWithPublicId`
- Extract code in `getTest` and `getAndOverrideTest` to simplify `getTestsToTrigger`
- Rename handleConfig to getOverriddenConfig
> synthetics: simplify getTestsToTrigger

- src/commands/synthetics/utils.ts
Why: readability.
- Extract code in `getBatch`, `getTestByPublicId` , `getPollResultMap` and `waitForBatchToFinish`
> Synthetics: Extract code to simplify waitForResults

- src/commands/synthetics/run-test.ts
- Extract code in  `overrideTestConfig` and `getTestListBySearchQuery` to simplify `getTestsList`
> Synthetics: Extract code to simplify `getTestList`

- README.md
Changes the instructions on how to build a run the CLI using a container. The current instructions do not take into account the fact that the CLI needs `git` for some commands and access to the local filesystem.
- New `Dockerfile` that is `alpine` based (to reduce size) and that installs `git` (required by several commands) and the CLI using `npm` (as the static binary is still experimental). It also installs the latest version of the CLI.
- Adds mounting the current directory into the container to have access to git metadata (required by several commands).
> Update container image instructions

- package.json
- yarn.lock
This adds caret versioning to aws-sdk. There are hard rules in our organization that the aws-sdk@v2 cannot be included more than once in a yarn-lock file due to serverless sizing limits. This change prevents that double-loading of this HUGE dependency.
Fixes #466 
Added a caret to the aws-sdk version.
- from `2.1012.0` to `^2.1012.0`
> chore: caret versioning for aws-sdk

- LICENSE-3rdparty.csv
- package.json
- yarn.lock
Add semver as a direct dependency to fix #634
> Add semver as a direct dependency

- .gitlab-ci.yml
- README.md
- container/Dockerfile
Add a CI job that will build and publish a docker image when we push a new tag.
This is done in Gitlab CI so we can reuse the logic to push to all registries (Dockerhub, Amazon ECR and Google GCR) used for other Datadog images like the Agent image or the Watermark Pod Autoscaler image.
> Release docker image when a tag is pushed

- .github/workflows/ci-visibility-itr.yml
- jest.config-ci-vis-itr.js
- package.json
CI Visibility's Intelligent test runner is able to skip tests based on code coverage and git diff metadata. This workflow enables ITR when running unit tests, but in a different, non blocking workflow, so we can battle test it before moving it to the current workflow. 
Add a new workflow for running unit tests using ITR.
> [ci-visibility] Create new workflow for ITR

- LICENSE-3rdparty.csv
- package.json
- yarn.lock
Add `ora` package for `'elegant' terminal spinners`.
We want to improve user experience for our interactive modes in the Lambda command. Some of our workflows require the user to wait until we load a large amount of data. Adding indications, like a spinner, will provide them with certainty that the terminal is not frozen.
)
Image used from the `ora` package.
Installing the dependency.
```sh
yarn add ora@5.4.1
```
Installing `5.4.1` since newer versions require a bumped version of Typescript which we currently do not support.
> [lambda] Add ora dependency

- package.json
- yarn.lock
This PR bumps `yamux-js` to fix an issue with the tunnel when processing big uploaded payloads.
> [synthetics] bump yamux-js to v0.1.1

- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/utils.ts
This PR makes the `device` property optional in a browser test's `result` because it will be undefined if a test times out when waited for.
Displaying this `device` property is also refactored into a `formatDeviceId()` utility function.
> [synthetics] `result.device` should be optional

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
In our interface, the `batchId` property of a run summary was optional because it's not initially set.
But seen from the outside, the `batchId` will always be defined.
Internally we use an `InitialSummary` but we expose a `Summary`.
> [synthetics] `Summary.batchId` should be required

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/utils.ts
This PR makes the jUnit reports generated for Synthetic tests compatible with the test report tab in the results of a GitLab pipeline.
- Use the 3 possible status icons:
- ⏩ for skipped tests
- ❗️for failed non-blocking tests
- ❌ for failed blocking tests
- Decouple test suites' stats and test cases' step stats:
- Test suites' stats now **only include**: `errors`, `failures`, `skipped` and `tests`. The `allowfailures` and `warnings` stats were removed because they were too specific to the steps inside of a test case.
- Test cases' stats are now **all prefixed with `steps_`: `steps_allowfailures`, `steps_count`, `steps_errors`, `steps_failures`, `steps_skipped`, `steps_warnings`. It's clearer what those stats are about **and** `skipped` was conflicting with the `<skipped>reason</skipped>` …
> [synthetics] Make jUnit reports compatible with GitLab

- yarn.lock
Upgrade vm2 dependency to address [CVE-2022-36067](https://nvd.nist.gov/vuln/detail/CVE-2022-36067)
Bump `vm2` dependency resolution to v3.9.11.
Github Action on related Dependabot PR branch seem to constantly fail to initialise: https://github.com/DataDog/datadog-ci/pull/650
> [dep] Bump `vm2` dependency resolution to v3.9.11

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
Using config overrides with different start URLs for the same test, we noticed that the URL reported in the results in the output was displaying the same URL for all the results. It should actually show a different URL as we overrode it for each test, in the config overrides.
The `test` retrieved with `getTestByPublicId` is a shared instance for all the results because the public ID is the same. Therefore, doing `deepExtend(test, pollResult.check)` a few lines below was actually overriding the same `test` object for all the results. Thus, all the results ended up with the test overrides of the last iteration.
https://github.com/DataDog/datadog-ci/blob/4965ff27a6b1642bd3dc11d012376f4e38dff37f/src/commands/synthetics/utils.ts#L379-L391
The solution was to clone the whole `test` object for …
> [Synthetics] Fix reported test URL when using config overrides

- src/commands/dsyms/README.md
- src/commands/flutter-symbols/README.md
- src/commands/git-metadata/README.md
- src/commands/lambda/README.md
- src/commands/react-native/README.md
- src/commands/sourcemaps/README.md
- src/commands/sourcemaps/upload.ts
I noticed some typos in READMEs and in one example for `datadog-ci sourcemaps upload`.
> Fix typos in user facing files

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/command.ts
- src/commands/synthetics/errors.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
Currently, there is no option to make a CI fail if a given test (through `--public-id` or a config file) is missing.
We introduce a new `--failOnMissingTests` flag to support this.
> [synthetics] Add `--failOnMissingTests` flag

- src/commands/dsyms/upload.ts
- src/commands/git-metadata/upload.ts
- src/commands/junit/upload.ts
- src/commands/react-native/codepush.ts
- src/commands/react-native/upload.ts
- src/commands/react-native/xcode.ts
- src/commands/sourcemaps/upload.ts
- src/commands/trace/trace.ts
For some reason, `clipanion` ignores single newlines when printing the `--help` of a command.
So what was printed for a lot of commands was something like this:
> **Details:**
> 
> This command wraps another command, which it will launch, and report a custom 
> span to Datadog.See README for details.
This PR just adds a double newline instead of a single newline. Here is the result:
> **Details:**
> 
> This command wraps another command, which it will launch, and report a custom 
> span to Datadog.
> 
> See README for details.
> Fix missing whitespace in `details` of some commands

- src/commands/metric/__tests__/metric.test.ts
- src/commands/tag/__tests__/tag.test.ts
- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
This PR changes how we get the CI env for the tag and metrics command so that we only retrieve what is strictly needed as well as return an error if some of the env needed is missing.
Hardcode the required env
> [CI Visibility] Improve handling of CI env for tag and metric cmd

- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/reporters/default.ts
Add a fancy spinner to the `synthetics` command when waiting for test results.
Use [ora](https://github.com/sindresorhus/ora) added from https://github.com/DataDog/datadog-ci/pull/638 to display `Waiting for...` text.
> [Synthetics] Add tests result wait spinner to default reporter

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
For `(us3|us5).datadoghq.com` main DCs, the computed "Result URL" and "Results URL" start with `https://app.us3.datadoghq.com/`, although it should start with `https://us3.datadoghq.com/`.
Fix the logic of `getAppBaseURL()`.
> [synthetics] Handle empty subdomain on all DCs

- .github/CODEOWNERS
The `flutter-symbols` currently has no codeowner.
> Add codeowner for the flutter-symbols command

- .gitignore
- src/commands/react-native/README.md
- src/commands/react-native/__tests__/fixtures/with-sources-content/main.jsbundle.map
- src/commands/react-native/__tests__/interfaces.test.ts
- src/commands/react-native/__tests__/xcode.test.ts
- src/commands/react-native/codepush.ts
- src/commands/react-native/interfaces.ts
- src/commands/react-native/renderer.ts
- src/commands/react-native/upload.ts
- src/commands/react-native/xcode.ts
Enable removal of sources content from react native source maps.
This can reduce the size of the sourcemap by 60%.
However doing so will result in not having the code snippet next to the unminified error, but that is considered nice to have for now.
Solves https://github.com/DataDog/dd-sdk-reactnative/issues/302
Also added some optional arguments to the xcode command.
> Add argument to remove sources content from react native source maps

- package.json
- src/commands/dsyms/__tests__/upload.test.ts
- src/commands/dsyms/renderer.ts
- src/commands/dsyms/upload.ts
- src/commands/dsyms/utils.ts
- src/commands/flutter-symbols/__tests__/upload.test.ts
- src/commands/flutter-symbols/upload.ts
- src/commands/react-native/__tests__/codepush.test.ts
- src/commands/react-native/__tests__/upload.test.ts
- src/commands/react-native/__tests__/xcode.test.ts
- src/commands/react-native/errors.ts
- src/commands/react-native/interfaces.ts
- src/commands/react-native/upload.ts
- src/commands/react-native/xcode.ts
Related to https://github.com/DataDog/datadog-ci/pull/666.
Mostly import rearrangements, and non-null assertion operator deletions since TypeScript type inference improved over the time.
You can **ignore the change in `package.json`**: it is **temporary** and here to make the CI pass on this PR. It will be removed once merged in #666.
> [lint][rum-mobile] Migrate to `eslint`

- README.md
The node version badge currently doesn't reflect:
https://github.com/DataDog/datadog-ci/blob/b347eb039770055c092afe89b0f65bfa5edc78cc/package.json#L11
and 
https://github.com/DataDog/datadog-ci/blob/b347eb039770055c092afe89b0f65bfa5edc78cc/.node-version#L1
Change the version shown in the node version badge.
> [readme] Update node version badge

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/utils.ts
This PR adds more context in API errors, specifically the URL which was used.
Thanks to this, there should be enough context to know what test failed with a 403 when getting all the test configs.
1. The `getTest()` method now throws a `EndpointError` in case of an error different than 404 not found.
2. The `formatBackendErrors()` now always logs the URL that was used for the query.
> [synthetics] Improve context on API errors

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/command.ts
- src/commands/synthetics/errors.ts
- src/commands/synthetics/utils.ts
This PR introduces a new `INVALID_CONFIG` critical error. For now, it's only used if the `datadogSite` is invalid to show a nice error message. It could later be used to do additional validation on the config.
This doesn't change the behavior in case of an invalid `datadogSite` since the command would have failed when querying the test configs anyway.
> [synthetics] Validate `datadogSite` on config resolved

- package.json
- src/commands/lambda/__tests__/fixtures.ts
- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/__tests__/functions/uninstrument.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/prompt.test.ts
- src/commands/lambda/__tests__/tags.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/functions/instrument.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/prompt.ts
- src/commands/lambda/tags.ts
- src/commands/lambda/uninstrument.ts
Related to https://github.com/DataDog/datadog-ci/pull/666.
Mostly import rearrangements, and non-null assertion operator deletions since TypeScript type inference improved over the time.
You can **ignore the change in `package.json`**: it is **temporary** and here to make the CI pass on this PR. It will be removed once merged in #666.
> [lint][serverless] Migrate to `eslint`

- package.json
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/__tests__/tunnel.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/__tests__/websocket.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/errors.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/tunnel.ts
- src/commands/synthetics/utils.ts
Related to https://github.com/DataDog/datadog-ci/pull/666.
Mostly import rearrangements, and non-null assertion operator deletions since TypeScript type inference improved over the time.
You can **ignore the change in `package.json`**: it is **temporary** and here to make the CI pass on this PR. It will be removed once merged in #666.
> [lint][synthetics-worker] Migrate to `eslint`

- package.json
- src/commands/git-metadata/__tests__/git.test.ts
- src/commands/git-metadata/__tests__/upload.test.ts
- src/commands/git-metadata/git.ts
- src/commands/git-metadata/upload.ts
- src/commands/sourcemaps/__tests__/upload.test.ts
- src/commands/sourcemaps/interfaces.ts
- src/commands/sourcemaps/upload.ts
- src/commands/sourcemaps/validation.ts
Related to https://github.com/DataDog/datadog-ci/pull/666.
Mostly import rearrangements, and non-null assertion operator deletions since TypeScript type inference improved over the time.
You can **ignore the change in `package.json`**: it is **temporary** and here to make the CI pass on this PR. It will be removed once merged in #666.
> [lint][source-code-integration] Migrate to `eslint`

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
* Update the main README:
* Add a step to the release process to update the CI integrations if changes to the `synthetics` command are released
* Move the "Usage" section (with the links to other READMEs) up in the file
* A few nits here and there
* Remove the checkbox specific to `synthetics` changes in the PR template
> [docs] Update main README

- src/commands/lambda/constants.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/functions/instrument.ts
- src/commands/lambda/prompt.ts
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-global-keys.json
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/command.ts
- src/commands/synthetics/utils.ts
- src/constants.ts
- src/helpers/__tests__/validation.test.ts
- src/helpers/validation.ts
We didn't want to maintain a list of datadog sites in #660, but the `lambda` command already does it. So, let's move this in the shared helpers so that all commands can use it.
Move `SITES` in a new `src/constants.ts` file and create a new `isValidDatadogSite()` validation helper.
> Move datadog site validation in shared helpers

- src/helpers/__tests__/ci-env/buddy.json
- src/helpers/ci.ts
Change the datadog-ci so that it recognizes when it is running in [buddy.works](https://buddy.works)
Adding to the helper function the mappings for the buddy environment.
> Add support for buddy.works in junit upload

- README.md
We are always one click away from knowing what version is actually published on NPM, and it's not obvious that datadog-ci is published on NPM at first glance.
This PR adds a version badge for NPM.
> [docs] Add NPM version badge

- src/commands/metric/metric.ts
- src/commands/tag/tag.ts
- src/helpers/ci.ts
Adds support for creating custom tags and metrics for Buddy. Note that only pipeline level is supported as we do not have enough information to identify a job.
⚠️  Do not merge until the backend is deployed
> Add custom tags and metrics support for Buddy

- .github/workflows/ci-visibility-itr.yml
- .github/workflows/ci.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
We're getting deprecation annotation in our github action runs: 
As seen in https://github.com/DataDog/datadog-ci/actions/runs/3297103052
We're not using node@12 but `setup-node@v1` and `checkout@v2` are.
* Bump `setup-node` action to `v3`
* Bump `checkout` action to `v3`
With these changes we don't get warning anymore: https://github.com/DataDog/datadog-ci/actions/runs/3297156471
> Use newest version of `setup-node` and `checkout` actions

- .github/workflows/ci-visibility-itr.yml
- .github/workflows/ci.yml
Run tests in different node versions to improve reliability.
At some point we'd want to test different operating systems, but windows tests are broken right now, so that will require a different PR.
* Run unit tests in node@14, node@16 and node@18.
> Run tests in different node versions

- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/api.ts
- src/commands/junit/interfaces.ts
- src/commands/junit/upload.ts
Adding a new CLI flag to junit upload command to customize how tags are added to tests.
It's quite simple we only split the flags provided in the first `=` and forward it to the backend request
> [CI Visibility] (innovation week) junitxml custom tags with xpath

- src/helpers/__tests__/validation.test.ts
- src/helpers/validation.ts
Add support for development environment variable `DD_CI_BYPASS_SITE_VALIDATION` disabling site validation.
Ignore the `datadogSite` validation when the `DD_CI_BYPASS_SITE_VALIDATION` environment var value is truthy.
> [dev] Add `DD_CI_BYPASS_SITE_VALIDATION` environment flag support

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
Remove `startUrl` native URL variables support (usage of `HOSTNAME`, `SUBDOMAIN`...) which has been deprecated [since `0.18.0`](https://github.com/DataDog/datadog-ci/pull/484):
- https://github.com/DataDog/datadog-ci/pull/483
This feature has been replaced with the more powerful and less confusing `startUrlSubstitutionRegex` and support for Synthetic variables and environment variables overrides. Synthetics runners now perform the URL computation based on variable overrides and substitution on test reception.
Remove code related to native URL variables.
> [MAJOR][Synthetics] Remove deprecated `startUrl` native URL variables support

- src/commands/react-native/__tests__/xcode.test.ts
- src/commands/react-native/xcode.ts
Prevents bundling (and composing if hermes is enabled) react native sourcemaps when no upload is planned in `react-native xcode` command.
This makes iOS debug builds faster, and avoids propagating errors to debug builds if some configuration is missing. 
Exit before bundling if source maps are not supposed to be uploaded.
The `react-native-xcode.sh` script also exits early if configuration is "Debug".
> Do not bundle and compose react native sourcemaps if no upload

- src/commands/react-native/__tests__/xcode.test.ts
- src/commands/react-native/utils.ts
- src/commands/react-native/xcode.ts
In React Native 0.71 we don't have to compose Hermes sourcemaps after build anymore, and we cannot as the "composable" parts are removed after the build.
Check if version of react native is over 0.70 before composing Hermes sourcemaps.
> Support React Native 0.71

- src/commands/metric/__tests__/metric.test.ts
- src/commands/tag/__tests__/tag.test.ts
- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
Detect when running on Jenkins and forward the right env vars so we can add custom tags and metrics to Jenkins pipelines.
Also updates the error message to say that Jenkins and Buddy are supported (buddy was added recently but the message not updated).
> [CI App] Add support for custom tags & metrics in Jenkins

- package.json
- yarn.lock
Bump `dd-trace` to keep with bug fixes and improvements, especially around intelligent test runner.
* Bump `dd-trace` to `3.9.0`
> [ci-visibility] Bump `dd-trace`

- .github/workflows/ci.yml
- .github/workflows/e2e/global.config.json
- Update the API and App key name to reflect the associated account
- Set the Synthetics E2E tests config to fail on critical errors and missing tests
> [ci] Update e2e keys, fail on synthetics test errors

- .github/workflows/ci.yml
- .github/workflows/e2e/global.config.json
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/uninstrument.ts
The merge of #688 didn't show a merge conflict. Making me think it would merge safely. Nonetheless, that was not the case since the `instrument.ts` and `uninstrument.ts` files got a line changed.
Also, some test snapshots were missing a line, caused by this non-showing merge conflict.
Updating the files as they should be, also its tests.
> [lambda] Fix merge conflicts from #688

- package.json
- yarn.lock
Bump `dd-trace` to keep up with latest features and bug fixes.
Bump `dd-trace` to `3.10.0`.
> [ci-visibility] Bump dd-trace

- src/helpers/__tests__/ci-env/github.json
- src/helpers/ci.ts
`GITHUB_JOB` is now available as an environment variable, so we'd like to extract it (more info in https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables).
* Read `GITHUB_JOB` from env vars. 
* Update fixtures.
> [ci-visibility] Extract GitHub Job name from env vars

- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/instrument.ts
Remove git metadata uploading when running the `lambda instrument` command with flag `-s` (`--source-code-integration`). Instead, add the repo url as a tag (alongside the commit sha that's already added) to the `DD_TAGS` env var. Fix tests.
This PR does not touch the datadog-ci `git-metadata` (`git-metadata upload`) command
Remove unneeded git upload function, get repo url from the git commit info (same place we get the commit hash).
These tags are added to `DD_TAGS` separated by commas, no spaces. The repo url is formatted in the following way:
`git.repository_url:github.com/thedavl/python_cdk_app.git`
- In order to not break backwards compatibility with tracer versions that don't support colons in tags, logic has been added to …
> Remove git metadata uploading + add git repo url tag for SCI

- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/reporters/junit.ts
Reporters functions should not be `async`.
Or if they are, it will need a bigger fix.
jUnit reporter's `runEnd` was `async` because it was using `fs.promises` to write the files.
Instead, use `fs.mkdirSync` and `fs.writeFileSync` to keep the function synchronous.
> [s8s] Make jUnit reporter's runEnd synchronous

- yarn.lock
Bump json5 2.x to `2.2.3` to fix [CVE-2022-46175](https://nvd.nist.gov/vuln/detail/CVE-2022-46175).
> [dep] Bump json5 2.x to `2.2.3`

- src/commands/lambda/README.md
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/instrument.ts
Enable the source code integration feature by default (tagging lambdas with the user's current git repo url + commit hash)
To disable, the flag `--no-source-code-integration` should be appended to the `instrument` command.
`private sourceCodeIntegration = true`
document it in the README
update unit tests
> Enable SCI by default

- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/index.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-test.ts
Using `executeTests` from outside is quite complex and requires a somewhat big bootstrap we should not have to worry about when using this as a library.
Create a wrapper around `executeTests` called `execute` (open on the naming).
This wrapper will handle the reporters and configuration defaults.
Also tested locally with 
- https://github.com/DataDog/web-ui/pull/77588
> [s8s] Add lib wrapper to use from outside

- .gitlab-ci.yml
- README.md
Makes building the Docker image a manual step that needs to be triggered by hand during the release process.
During releases, there was a race condition between publishing the package and trying to build the Docker image. 
This was because the Gitlab pipeline that builds the Docker image ran automatically once a tag was pushed, but the package might not yet be available at that point.
> Manual Docker image release

- src/commands/lambda/instrument.ts
- src/commands/lambda/renderer.ts
Adds a warning if source code integration fails when instrumenting lambda functions. 
Previously, the CI would exit completely if SCI fails.
Example warning printed:
Rather than returning, prints "[Warning] Couldn't add source code integration. Error: {SCI error encountered}"
> Display warning message when SCI fails, rather than exiting.

- package.json
- yarn.lock
Snyk has identified that simple-git has [remote code execution](https://security.snyk.io/vuln/SNYK-JS-SIMPLEGIT-3177391) issue in versions less than 3.16.0. This repo needs simple-git updated, which this PR does.
More info here: https://security.snyk.io/package/npm/simple-git
I ran `yarn upgrade simple-git@3.16.0` to update the latest version of `simple-git`.
> Update simple-git from 3.15.0 to 3.16.0 to mitigate RCE security risk.

- package.json
- yarn.lock
Upgrade yamux-js to 0.1.2:
- https://github.com/th-ch/yamux-js/pull/14
> [deps] Upgrade yamux-js to 0.1.2

- package.json
- src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/lambda/__tests__/__snapshots__/uninstrument.test.ts.snap
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
Updates long inline snapshots to snapshot files.
Added the command `test:lambda` easy access to `jest src/commands/lambda --colors`
It's worth noting that only really large pieces of inline snapshots are being moved to snapshots. This so our test files are smaller and those snapshots are generated by running a command.
Replacing `.toMatchInlineSnapshot(...)` to `toMatchSnapshot()`.
Then run `--updateSnapshot`
> [lambda] Update tests from inline snapshots to snapshots

- .github/advanced-issue-labeler.yml
- .github/workflows/issue-labeler.yml
Automatically label new issues with the product owning the `command` (if specified).
Use [GitHub Issue Parser](https://github.com/marketplace/actions/github-issue-parser) and [Advanced Issue Labeler](https://github.com/marketplace/actions/advanced-issue-labeler) actions.
> [github] Add workflow to auto-label issues with datadog-ci command

- src/commands/lambda/__tests__/__snapshots__/uninstrument.test.ts.snap
- src/commands/lambda/__tests__/uninstrument.test.ts
The last version v2.4.0 was hardcoded in a test's snapshots, so it started to fail with the latest release. 
Mock `package.json`, the same way as already done in `instrument.test.ts`.
> Do not hardcode version in snapshots

- src/commands/lambda/README.md
Document the option for users to disable git metadata uploading (which was turned on by default in [this PR](https://github.com/DataDog/datadog-ci/pull/772)). Git metadata uploading should be turned off if users have the Datadog Github Integration installed, as source code integration will work without it.
Documents the `--upload-git-metadata` flag in the lambda instrument command, which defaults to true. When users pass `--no-upload-git-metadata`, the CI will refrain from uploading git metadata to Datadog.
> Add upload git metadata parameter to lambda instrument README.md

- package.json
I noticed we were not excluding the test files when creating the `.tgz` file to publish on NPM. So they end up in the `node_modules` when datadog-ci is installed somewhere.
You can explore the files [here](https://www.npmjs.com/package/@datadog/datadog-ci/v/2.4.1?activeTab=explore).
Sadly, Yarn 1 (that we're using in this project) [doesn't fully support](https://github.com/yarnpkg/yarn/issues/685#issuecomment-484304385) `.npmignore` or blocklist rules in the `files` property of `package.json`.
So I had to use `rimraf` in the `prepack` script.
- Before:
-  `yarn prepack && du -sh dist`: **3.2 MB**
- After:
-  `yarn prepack && du -sh dist`: **1.8 MB**
> [package] Remove test files when published

- src/commands/dsyms/upload.ts
- src/commands/flutter-symbols/upload.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/uninstrument.ts
- src/commands/react-native/README.md
- src/commands/react-native/upload.ts
- src/commands/react-native/xcode.ts
- src/commands/synthetics/command.ts
- src/helpers/__tests__/utils.test.ts
- src/helpers/utils.ts
We can now run the `xcode` command with `../node_modules/.bin/datadog-ci react-native xcode`, instead of `yarn datadog-ci react-native xcode`.
This changes the current working directory to be the `ios/` folder of the RN app instead of the root of the RN app.
We have a similar change for the dsyms command.
The default value for the `react-native` path should be in this case `../node_modules/react-native` instead of `node_modules/react-native`.
Similarly, the default path for the `datadog-ci.json` file should be `../datadog-ci.json` instead of `./datadog-ci.json`.
I've left the legacy values to be picked up first to avoid regressions.
I've only changed the default path for `datadog-ci.json` for the react native and dsyms upload commands.
> Add new default values for commands ran from XCode

- src/commands/dsyms/upload.ts
- src/commands/flutter-symbols/helpers.ts
- src/commands/react-native/upload.ts
The `flutter-symbols upload` command was overriding the API endpoint to the old v1 api. It does not appear that this is necessary anymore and prevents symbols from being uploaded to certain data centers, so I removed it.
> Remove api endpoint override for flutter-symbols command.

- package.json
- yarn.lock
- Bump `fast-xml-parser` to 4.1.2 to address Prototype Pollution [SNYK-JS-FASTXMLPARSER-3325616](https://snyk.io/vuln/SNYK-JS-FASTXMLPARSER-3325616)
- Release v2.5.1
> Release v2.5.1, Bump `fast-xml-parser`

- src/commands/flutter-symbols/README.md
Add some phrasing to the documentation to make it clear that Flutter symbol uploads are keyed off of `flavor` on top of `service` and `version`. Current phrasing makes it sound like only version and service are considered.
> Minor documentation change

- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/constants.ts
The current supported ARM instrumentations don't include the runtime `dotnet6`, which has been available since the version 4 of the tracer layer, we are currently at the 7th.
Didn't add runtime `dotnetcore3.1` because automatic instrumentation for ARM architectures is only supported starting `dotnet5`. See more about this [here](https://docs.datadoghq.com/tracing/trace_collection/compatibility/dotnet-core/#supported-processor-architectures).
Adding the runtime `dotnet6` to the ARM layer array.
Tested adding a unit test to make sure the correct layer is given. Also tested manually.
> [lambda] Add ARM layer support for `dotnet6` runtime

- src/commands/metric/__tests__/metric.test.ts
- src/commands/tag/__tests__/tag.test.ts
- src/helpers/__tests__/ci-env/teamcity.json
- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
When running in TeamCity CI, read the job info from the env vars.
> CI env vars: add support for TeamCity

- src/commands/flutter-symbols/upload.ts
- src/commands/react-native/upload.ts
- src/helpers/upload.ts
This adds the ability to use gzip encoding when uploading. Currently this is opt in on the UploadOptions and is only used for Flutter Symbols, Android mapping files, and React Native source maps.
> Support gzip uploads

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
yarn 2+ documentation mentions the setting `npmAuthToken` and says it can be defined as an env var; in which case the syntax is YARN_<setting>.
This seems to confirm it:
https://github.com/yarnpkg/berry/blob/15d31310cc6a5164df9ba4e7a99289657ec58be6/packages/acceptance-tests/pkg-tests-specs/sources/commands/publish.test.ts#L40
> Update env var for publishing to NPM.

- src/commands/synthetics/__tests__/mobile.test.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/mobile.ts
Avoid calculating MD5 hash on entire file at once as this caused issues with large files in similar front-end code.
Use `fs.ReadStream` to incrementally calculate MD5 and avoid doing it on the entire file at once.
However, the upload itself *still* reads the entire file into memory using `fs.readFile` in order to set `Content-Length` header in the upload request. This will need to be revisited to handle uploads larger than 2GB which are disallowed by
the `fs.readFile` API. One solution may be to use multi-part upload in combination with `fs.ReadStream` when doing
the upload.
- [ X] Feature or bugfix MUST have appropriate tests (unit, integration)
- Associated unit test modified and passing
- Also manually tested with sample mini app upload
> [synthetics] Do incremental MD5 calculation in `uploadMobileApplications`

- src/commands/synthetics/__tests__/utils.test.ts
- src/constants.ts
- src/helpers/__tests__/validation.test.ts
Add a reference to the newly GA Datadog site: ap1.datadoghq.com.
Add an entry in the list of sites
> Add new ap1.datadoghq.com site

- src/commands/synthetics/README.md
Tab short code was breaking the NPM and Yarn tags in the **Run tests** section.
Chat with Corentin on Slack
https://docs-staging.datadoghq.com/alai97/preview-for-configuration-page-tabs/continuous_testing/cicd_integrations/configuration
> Continuous Testing CI/CD Integrations Configuration Edit

- src/commands/synthetics/command.ts
The type of the `--subdomain` parameter was incorrect, leading to an error:
```bash
$ yarn launch synthetics run-tests --subdomain hello
Unknown Syntax Error: Extraneous positional argument ("hello").
```
Change `Boolean` to `String`.
We currently have a ["all option flags are supported" test](https://github.com/DataDog/datadog-ci/blob/f3e5df8e2f455ca7194c4dbd651881c44f39aa3c/src/commands/synthetics/__tests__/cli.test.ts#L12) but it only tests that the option flag is _here_.
Testing if the type of the option flag is correct would require an e2e test, which would take a lot of time to execute.
> [synthetics] Fix `--subdomain` argument

- src/commands/flutter-symbols/README.md
The documentation had `--pubspec-location` but the correct option was `pubspec`.
Fixes #844
> Fix Flutter Symbol Upload documentation

- src/commands/synthetics/README.md
Adds a site address shortcode in the Configuration doc page.
DOCS-5226
https://docs-staging.datadoghq.com/alai97/continuous-testing-cicd-integrations-site-region-update/continuous_testing/cicd_integrations/configuration
> DOCS-5226 CI/CD Integrations Configuration Edits

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/command.ts
- src/commands/synthetics/run-test.ts
- src/commands/synthetics/utils.ts
Currently, the error handling in our CI integrations isn't aligned with what datadog-ci does (#663).
This PR refactors datadog-ci to extract and export new utils that will be used in our CI integrations.
Draft PRs on the CI integrations to use this new API:
- https://github.com/DataDog/synthetics-ci-github-action/pull/122
- https://github.com/DataDog/datadog-ci-azure-devops/pull/46
This PR creates 4 new utils:
- `reportCiError()` will allow us to remove files like [src/report-ci-error.ts (github action)](https://github.com/DataDog/synthetics-ci-github-action/blob/main/src/report-ci-error.ts).
- `reportExitLogs()` reports all logs that are common between failed and successful runs.
- `getExitReason()` replaces code that does manual error handling, like in …
> [synthetics] Export new utils for error handling

- src/helpers/__tests__/plist.test.ts
- src/helpers/plist.ts
On the default template for React Native, the Info.plist file uses environment variables for the version and build number.
We look if the value in the Info.plist is an env variable. 
If that's the case, we look for the environment variable or use the default values.
Screenshot of a working example:
> [React Native] Support environment variables in Info.plist for react-native xcode

- src/commands/git-metadata/upload.ts
- src/constants.ts
Git sync has been introduced in a previous version as an optional step. After more thorough testing it seems to work fine so the idea is to now release that as a default. There is still the option to disable it through --no-git-sync, just in case this new sync would fail the command in some setups.
Additionally I kept the `--git-sync` option for backward compatibility, and ignore any error for the gov DC as git sync is not available there yet.
> [git-metadata] Make git sync as default behavior.

- src/commands/junit/README.md
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
- src/helpers/__tests__/tags.test.ts
- src/helpers/tags.ts
Some customers want to add numerical tags (metrics) to their JUnit uploads. They can't do so through `DD_TAGS` because every tag is assumed a string. 
By adding `--metrics` and `DD_METRICS`, customers are able to pass numerical tags to their tests. 
* Add `--metrics` option to `junit upload` command. 
* Add `DD_METRICS` env var.
> [ci-visibility] Add `--metrics` and `DD_METRICS` options

- src/commands/git-metadata/README.md
- src/commands/react-native/README.md
- src/commands/sourcemaps/README.md
We now support generating link for Azure DevOps repository, so updating the documentation.
> [SC-1245] Update doc provider Azure DevOps

- src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/lambda/__tests__/__snapshots__/uninstrument.test.ts.snap
- src/commands/lambda/__tests__/functions/instrument.part1.test.ts
- src/commands/lambda/__tests__/functions/instrument.part2.test.ts
- src/commands/lambda/functions/instrument.ts
We found a bug where the handler path would change incorrectlly when no layer is set
Checks that a layer version is set before changing the Handler of a function
> [lambda] Only change handler path when a layer version is specified

- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/constants.ts
Our tag check was not compliant with Datadog's [tag definition](https://docs.datadoghq.com/getting_started/tagging/#define-tags).
This PR changes the regular expression to make sure we allow values as described there.
Updates the regex. Update test and more use cases.
> [lambda] fix tags regex to comply with Datadog tagging

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/mobile.test.ts
- src/commands/synthetics/__tests__/run-test.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/mobile.ts
- Compute and forward application size to `getMobileApplicationPresignedURL`. The endpoint was changed to verify the app size and send back a pre-signed URL or an error message with context. 
- Add try-catch around `getMobileApplicationPresignedURL` and `uploadMobileApplication`.
Changing back-end code
> s8s(mobile): Compute and forward application size to getMobileApplicationPresignedURL

- src/commands/sarif/__tests__/fixtures/invalid-result.sarif
- src/commands/sarif/__tests__/upload.test.ts
- src/commands/sarif/upload.ts
This PR fixes the logic to show the validation errors when the `sarif upload` command is used.
Join strings composed by `instancePath` and `message` to build the final message.
> Show validation errors on SARIF command

- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/uninstrument.ts
AWS CloudShell already provides credentials. These are not being used by `datadog-ci` since we only check for environment variables. Therefore, an update of how we get AWS credentials from environment is required.
Instead of checking just for credentials in environment variables, we are using the function `fromNodeProviderChain` from `@aws-sdk/credential-provider` which is a chain that checks in multiple places for AWS credentials.
> [lambda] update how AWS credentials are handled

- src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/functions/instrument.ts
Instrumentation for Ruby now allows users to use the Extension and the Library Layer.
ARM is now supported for instrumentation too.
– 
Users can still use the forwarder as an option too.
Adding runtime into layer and architecture lookups.
- Added tets
- Tested manually
> [lambda] update instrumentation for Ruby

- src/commands/gate/__tests__/evaluate.test.ts
- src/commands/gate/evaluate.ts
- src/commands/gate/renderer.ts
Changing the result exit status based on the gate evaluation result:
- Passed -> successful command
- Failed -> failed command
- Empty -> successful command unless `--fail-on-empty` is specified
> Changing gate command exit status based on gate evaluation result

- src/commands/stepfunctions/README.md
This PR fix README.md format issue.
> Fix format issue on the stepfunction command README.md

- README.md
I tried to release v2.12.0 with "Rebase and merge strategy" (according to #881) and weirdly, GitHub generates a new commit instead of just rebasing and pushing the exact same commit (same commit SHA).
- Commit that used to be on my branch: https://github.com/DataDog/datadog-ci/commit/9b91ed809a9c6cc560d6dd8ba5e0b8b08b471735 (pushed in https://github.com/DataDog/datadog-ci/pull/890)
- Commit once merged: https://github.com/DataDog/datadog-ci/commit/9b7e1d188030d42ef9edb86b6bae37c428b4e232
Since no version was published on NPM yet, and no Docker image was built, I'll overwrite the v2.12.0 tag. So for the record (before it's overwritten), here is a proof that the tag was pointing to my [branch commit](https://github.com/DataDog/datadog-ci/commit/9b91ed809a9c6cc560d6dd8ba5e0b8b08b471735).
cc. …
> Update release process in README

- standalone-e2e/standalone-binary.test.ts
The previous attempt (#838) to fixing this ended up working for a limited time. Even after "warming up" the binary with a `beforeAll`, the test is [still flaky](https://github.com/DataDog/datadog-ci/actions/runs/5071931748/jobs/9108968694).
Let's replace the "warming up" - which does an extra execution of the binary without a lot of benefits - by an increase of the timeout to 10 seconds (for macOS only).
> [test] Fix flaky standalone binary test on macOS

- .github/CODEOWNERS
Add serverless as the codeowner of `stepfunctions` command.
> add serverless as the codeowner of `stepfunctions` command

- src/commands/gate/__tests__/scope.test.ts
- src/commands/gate/api.ts
- src/commands/gate/evaluate.ts
- src/commands/gate/interfaces.ts
- src/commands/gate/renderer.ts
- src/commands/gate/utils.ts
Users will be able to provide:
- Scope, via the `--scope` option. They can provide multiple values for the same key (e.g. `--scope=team:backend --scope=team:frontend`). Scope will be used to further filter the rules that are being evaluated.
- Tags, via the `--tags` option. These will work exactly as the other commands.
> Add support for user defined scopes and tags

- src/commands/lambda/constants.ts
Removes support for `ruby2.5` instrumentation
This runtime has been deprecated by AWS (phase 2).
Removing it from the runtime lookups.
> [lambda] deprecate `ruby2.5`

- src/commands/synthetics/README.md
This PR replaces the documentation tags with the GFM compatible alternative.
It allows to keep the features for our internal documentation processor, while hiding the artifacts from the github markdown preview.
> [synthetics] hide documentation artifacts in README

- src/commands/lambda/__mocks__/instrument-uninstrument-renderer.js
- src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
- src/commands/lambda/__tests__/fixtures.ts
- src/commands/lambda/__tests__/flare.test.ts
- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/__tests__/functions/uninstrument.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
- src/commands/lambda/cli.ts
- src/commands/lambda/flare.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/renderers/common-renderer.ts
- src/commands/lambda/renderers/flare-renderer.ts
- src/commands/lambda/renderers/instrument-uninstrument-renderer.ts
- src/commands/lambda/uninstrument.ts
Adds the beginning of the code for the Lambda flare that will enable customers to send their Lambda configuration to Datadog for debugging and setting up instrumentation. 
* Add command header
* Add start of tests
* Refactor some of the instrument / uninstrument code to work with a command
> [lambda][flare] Add initial code for Lambda serverless flare 

- src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/constants.ts
AWS lambda will soon support the Ruby 3.2 runtime.
This change updates the `lambda` command to support instrumentation/uninstrumentation with the runtime.
Added Ruby 3.2 runtime to the constants
> [lambda] Add Ruby 3.2 support

- standalone-e2e/standalone-binary.test.ts
We managed to fix the flakiness on macOS (#893), but Windows can also [occasionally fail](https://github.com/DataDog/datadog-ci/actions/runs/5142676448/jobs/9256709607).
Let's fix this definitely.
Define timeouts for all platforms.
> [test] Improve standalone binary test timeout

- src/commands/flutter-symbols/README.md
- src/commands/flutter-symbols/__tests__/upload.test.ts
- src/commands/flutter-symbols/renderer.ts
- src/commands/flutter-symbols/upload.ts
This adds the ability to upload JavaScript sourcemaps as part of the `flutter-symbols upload` command.
Manual upload of Flutter source maps was already possible using the `sourcemaps upload` command, this just integrates it with the `flutter-symbols` command, allows automatic detection of version (if possible) and allows you to use one command over two.
I've added several parameters that enable upload of the javascript source maps, and forward those over to the sourcemaps command that's already available, including the default location that Flutter puts the sourcemaps in.
> [Flutter] Add JavaScript sourcemap upload

- src/commands/junit/README.md
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
- src/commands/junit/utils.ts
We've had some issues with slowness doing this git upload operation. Until we have proper metrics reporting in place, it's safer to turn this into opt-in rather than opt-out.
* Change `--skip-git-metadata-upload` to `--enable-git-metadata-upload`. Now, only if you're passing it will `datadog-ci junit upload` attempt to upload your data.
> [ci-visibility] Change default value of git upload

- src/commands/junit/api.ts
- src/helpers/__tests__/file.test.ts
- src/helpers/file.ts
Replaces the old unique filename with just the filename since we don't need it to be unique anymore on our side.
Deleting that code and just using the filename
> [junit] Replace unique filename with just filename

- .github/workflows/release.yml
All CI integrations now have a workflow to bump datadog-ci. It's now time to do this automatically on each release of datadog-ci.
Use the github's api to dispatch workflows.
> [ci] Bump datadog-ci in CI integrations on release

- package.json
- yarn.lock
Bump @aws to get latest versions of fast-xml-parser.  Current one has a high severity alert.  See https://github.com/NaturalIntelligence/fast-xml-parser/security/advisories/GHSA-6w63-h3fj-q4vw
Ran some `yarn add` commands.
> [dep] Bump aws-sdk to bump fast-xml-parser

- src/commands/junit/__tests__/id.test.ts
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/id.ts
- src/commands/junit/upload.ts
By adding a trace id in the git metadata upload requests we make sure that we can track the whole process. 
* Add an `id` module to generate span / trace ids. 
* Set trace id and parent id headers in the git requests.
> [ci-visibility] Add trace id to git requests when using `junit upload`

- package.json
- yarn.lock
Fixes https://github.com/DataDog/datadog-ci/security/dependabot/26
I thought that only the `7.x` (this major only) were affected by this vulnerability, but apparently it's all of them.
This PR aligns all the `semver` dependencies to a single one: [`7.5.3`](https://github.com/npm/node-semver/releases/tag/v7.5.3) (which contains another bug fix).
> Bump semver from 7.5.2 to 7.5.3

- package.json
- yarn.lock
Bumps ssh2 from 1.9.0 to 1.14.0. Closes #714, which was breaking some builds on windows
Upgrade ssh2, and its upstream dependencies.
> Bump ssh2 from 1.9.0 to 1.14.0

- src/commands/junit/README.md
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
- src/commands/metric/README.md
- src/commands/tag/README.md
- src/commands/trace/README.md
- src/commands/trace/trace.ts
We want to be as consistent as possible. `DD_*` env vars are the standard. We still want to support `DATADOG_*` but at least the documentation should stick with `DD_*`.
Update docs to recommend using `DD_*`.
> [ci-visibility] Update docs to recommend `DD_*` env vars everywhere

- .github/workflows/release.yml
This CI job didn't work as expected recently: we released [`v2.16.0`](https://github.com/DataDog/datadog-ci/releases/tag/v2.16.0), but the PRs which were created all targeted `v2.15.0` ([example](https://github.com/DataDog/synthetics-ci-github-action/pull/163)).
I suspect this is because the changes done by [`yarn npm publish`](https://github.com/DataDog/datadog-ci/blob/543578ebe4ea52d562dbf3c74bc8e43248b77c8b/.github/workflows/release.yml#L14) in this repository's CI took time to get propagated.
By default, when no inputs are given to the `bump-datadog-ci.yml` workflows, we default to latest. And I think that[ `npm view @datadog/datadog-ci --json`](https://github.com/DataDog/synthetics-ci-github-action/blob/93319f125c3ee84ad58e394c200a5d79927aa9ce/.github/workflows/bump-datadog-ci.yml#L50 …
> [ci] Bump integrations with given version of datadog-ci

- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/utils.ts
Closes https://github.com/DataDog/datadog-ci/issues/864
Without this, the user needs to wait until the end (or timeout) of the batch in order to view it in Datadog.
- Move the call of `reporter.testsWait()` from `getTestsToTrigger()` to `waitForResults()`.
- Add `baseUrl` and `batchId` to the arguments of `reporter.testsWait()` to craft the summary URL
FYI, the `batchId` is only available after (or in) `runTests()`, but `runTests()` doesn't take a `reporter` currently. And IMO, it's better semantically to give the link of the batch we are waiting for, inside `waitForResults()`.
New output:
```js
[3dq-qkt-ant] Found test "Test title" (1 config override)
View pending summary in Datadog: https://app.datadoghq.com/synthetics/explorer/ci?batchResultId=32cc437d-0a94-4565-8862-23fbec4d552b …
```
> [synthetics] Print summary link before waiting for results

- src/commands/junit/__tests__/fixtures/junit.xml/valid-report-2.xml
- src/commands/junit/__tests__/fixtures/junit.xml/valid-report.xml
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
- src/commands/junit/utils.ts
When passing folders with this shape: `./reports/junit.xml/`, `datadog-ci` considered that to be a valid file (because it used `path.extname`), so when attempting to read its contents it failed. 
This PR fixes that.
Using `isFile` util function to check if the input is actually a file or not.
> [ci-visibility] Do not use extension for checking if a path is a file

- src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
- src/commands/lambda/__tests__/flare.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/flare.ts
For more context on what Lambda Flare is, please read the description in this PR: https://github.com/DataDog/datadog-ci/pull/924
We want to obfuscate secrets (passwords, API keys, and other unknown environment variables) in Lambda function configuration so customers don't send private information to Datadog support. Any non-Datadog environment variables should also be obfuscated.
1. Create a whitelist of 'allowed' environment variables to not be obfuscated. These are stored in a set in the constant `NON_OBFUSCATED_ENV_VARS` for O(1) lookup.
2. If an environment variable is not in this set, we will pass it to the `getObfuscation` function which returns an obfuscated version of the string.
3. Short strings (<12 characters) will be entirely obfuscated and replaced with `*`'s. Longer strings …
> [lambda][flare] Obfuscate secrets

- src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
- src/commands/lambda/__tests__/flare.test.ts
- src/commands/lambda/flare.ts
For more context on what Lambda Flare is, please read the description in this PR: https://github.com/DataDog/datadog-ci/pull/924
We want to ask users for confirmation before sending their files to support.
If they answer `no` or anything other than `y` or `Y`, the flare files are not sent and are deleted
They must answer `y` or `Y` before the files are sent to support.
This is intended to:
1. Give the user an opportunity to check the files and see if there is anything they don't want to send to support
2. Prevent users from accidentally spamming their support ticket with files
Use `inquirer` to prompt the user for confirmation.
Exit the program early if they answer `no`, continue otherwise.
> [lambda][flare] Ask for user confirmation before sending files to support

- src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
- src/commands/lambda/__tests__/flare.test.ts
- src/commands/lambda/flare.ts
For more context on what Lambda Flare is, please read the description in this PR: https://github.com/DataDog/datadog-ci/pull/924
Currently, only the timestamp in milliseconds since UNIX epoch is recorded in the CSV files for CloudWatch logs.
This change adds human readable time as a column in the CSV file in the format `YYYY-MM-DD HH:mm:ss.<milliseconds>`.
This is intended to improve the readability of these CSV files to help the support team.
1. Convert UNIX milliseconds to Date object using `new Date(timestamp)`
2. Convert Date object to string in the format described above using 
```
date.toISOString().replace('T', ' ').replace('Z', '')
```
> [lambda][flare] Add human readable time to CloudWatch CSV files

- src/commands/git-metadata/__tests__/git.test.ts
- src/commands/git-metadata/__tests__/gitdb.test.ts
- src/commands/git-metadata/git.ts
- src/commands/git-metadata/gitdb.ts
- src/helpers/git/__tests__/format-git-sourcemaps-data.test.ts
- src/helpers/git/__tests__/get-git-data.test.ts
- src/helpers/git/format-git-sourcemaps-data.ts
- src/helpers/git/get-git-data.ts
Improve git metadata upload:
- We now work with git repositories whose default remote is not "origin"
- We do not change the git config when doing git metadata upload
- Improved git metadata upload on error conditions
- Reduced code duplication
> Improve unshallowing and git metadata upload

- package.json
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/tunnel/tunnel.ts
- src/commands/synthetics/tunnel/websocket.ts
- src/helpers/__tests__/utils.test.ts
- src/helpers/metrics.ts
- src/helpers/utils.ts
- src/types/proxy.d.ts
- yarn.lock
Closes https://github.com/DataDog/datadog-ci/issues/658
Closes https://github.com/DataDog/synthetics-ci-github-action/issues/119
This PR bumps `proxy-agent` to version 6, which removes our `ftp` dependency, and bumps `vm2`.
The main difference in the new version is that the constructor of `ProxyAgent` doesn't take a proxy URL as argument anymore. So we now have to use the `getProxyForUrl` callback.
However, setting this callback overrides the default `getProxyForUrl`, which [uses the `proxy-from-env` package](https://github.com/TooTallNate/proxy-agents/blob/08c4625d8b0c015265e27b260a17a23f55f486d1/packages/proxy-agent/src/index.ts#L99). So we have to update `utils.getProxyAgent()` to take this into account.
Also, `proxy-agent@5.0.0` [didn't support …
> [dep] Migrate to `proxy-agent@6.2.1`

- src/commands/lambda/flare.ts
The code for validating flags in lambda flare was complicated and hard to read.
This PR doesn't change any logic in the code but makes validation more scalable and readable.
This is the strategy used in synthetics: https://github.com/DataDog/datadog-ci/blob/c082a1035d0558da9e6d2d0209c2bace98d78bf1/src/commands/synthetics/utils.ts#L572-L581
Have an `errorMessages` array and push error messages to the array when encountered.
After all the validation is complete, print any error messages and exit the program if any errors were found.
- This is not a new feature or bugfix, so no tests were added or changed.
> [lambda][flare] Refactor flag validation

- src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
- src/commands/lambda/__tests__/fixtures.ts
- src/commands/lambda/__tests__/flare.test.ts
- src/commands/lambda/flare.ts
For more context on what Lambda Flare is, please read the description in this PR: https://github.com/DataDog/datadog-ci/pull/924
- Get resource tags for an AWS lambda function
- Save them in `tags.json`
- This is because resource tags can be useful to the Datadog support team when resolving customer issues
I also refactored tests a little bit by standardizing `region` in `flare.test.ts` to use `const MOCK_REGION = 'us-east-1'`
1. Create a `getTags` function to gather resource tags
2. Use `ListTagsCommand` in the AWS SDK to get resource tags for a particular function ARN
3. The function ARN is retrieved from the function config, which is fetched previously in the command
4. Use try/catch statements to ensure human-readable error logging
5. Write to `tags.json` when tags are found using the …
> [lambda][flare] Get resource tags

- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
Closes #959 
Currently, multi-step tests are forbidden to run in the tunnel but HTTP steps in multi-step tests are now supported.
- Refactor the checks on `step.type` and `step.subtype` into a `isTestSupportedByTunnel()` utility function.
- Allow a multi-step test to be tunneled as long as all its steps are `http` steps.
> [synthetics] Support tunneled multi-step tests

- yarn.lock
The `semver` package now has a backported fix for all latest major versions: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw 
Use the appropriate version for majors 5, 6 and 7.
> [dep] Use latest `semver@5,6,7`

- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/run-tests-command.ts
- src/helpers/__tests__/utils.test.ts
- src/helpers/utils.ts
- https://github.com/DataDog/datadog-ci/pull/970 ←
- https://github.com/DataDog/datadog-ci/pull/971
---
This PR adds a `--pollingTimeout` CLI argument.
This will allow us to add a `polling_timeout` input in our [CircleCI orb](https://github.com/DataDog/synthetics-test-automation-circleci-orb).
- Add a new argument
- Add a utility function to parse an optional integer
- We can later reuse it in the github action ([here](https://github.com/DataDog/synthetics-ci-github-action/blob/84ab83ecd7f52c6daec005ced8883a461cef51c3/src/resolve-config.ts#L106-L111)) and azure devops extension ([here](https://github.com/DataDog/datadog-ci-azure-devops/blob/main/SyntheticsRunTestsTask/utils.ts#L12-L17))
- Throw an `INVALID_CONFIG` error if the validation fails
- Satisfy this order of precedence:
- …
> [synthetics] Add support for `--pollingTimeout`

- src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
- src/commands/lambda/__tests__/flare.test.ts
- src/commands/lambda/flare.ts
We want to use environment variables `DATADOG_SITE` or `DD_SITE` to build the endpoint URL to send flare files to. This ensures that user experience low latencies.
In the case where neither environment variable is set, we will use `DATADOG_SITE_US1 = 'datadoghq.com'` to default to `US1`.
- Create the `getEndpointUrl()` function that calculates and returns the full endpoint URL as a string
- Determine the base URL with priority (1) `DATADOG_SITE`, (2) `DD_SITE`, or (3) the default Datadog site `DATADOG_SITE_US1`, if neither environment variable is set.
- Append `https://` to the endpoint
> [lambda][flare] Build endpoint URL from environment variables

- src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
- src/commands/lambda/__tests__/flare.test.ts
- src/commands/lambda/flare.ts
This PR adds optional `--start` and `--end` flags to specify a time range for CloudWatch logs.
Only log streams and log events that lie within the range will be saved.
Even though both are optional flags, if one is specified, the other is required.
Each timestamp is in milliseconds since UNIX Epoch.
1. The `--start` and `--end` validation is complicated, so I created a helper function `validateStartEndFlags()` that handles the validation.
2. The `getLogEvents()` function has been updated to set the `startTime` and `endTime` options in `GetLogEventsCommand`. The logic for this is abstracted and handled by the AWS SDK. If `--start` and `--end` were not specified, then these options won't be added to the `GetLogEventsCommand` config.
3. `DescribeLogStreamsCommand` does not have start or end …
> [lambda][flare] Add optional start and end flags for getting CloudWatch logs

- src/commands/lambda/__tests__/flare.test.ts
- src/commands/lambda/flare.ts
Config obfuscation was using a function in `flare.ts`. However, a function that does the same thing already exists in `commons.ts`.
This PR modifies the `maskConfig()` function to use helper functions from `commons.ts`. It also removes any unused functions and tests.
Uses `maskStringifiedEnvVar()` in `commons.ts` to obfuscate the config in the form of a string. We then convert the obfuscated string back into type `FunctionConfig` using `JSON.parse()`.
Existing tests for `maskConfig()` still pass as expected. Unused tests for the now deleted `getMasking()` function have been removed.
> [lambda][flare] Change config obfuscation to use functions from `commons.ts`

- src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
- src/commands/lambda/flare.ts
Due to a DNS inconsistency, the lambda flare endpoint doesn't work on sites with no subdomain (for example, US1).
This PR updates sites to append endpoint URL with `app.` when no subdomain is present in the original URL.
```
if ([DATADOG_SITE_US1, DATADOG_SITE_EU1, DATADOG_SITE_GOV].includes(baseUrl)) {
endpointUrl = 'app.' + baseUrl
}
```
Snapshots have been updated to handle this change
> [lambda][flare] Update site endpoints

- src/commands/sarif/api.ts
- src/helpers/__tests__/file.test.ts
- src/helpers/file.ts
We replaced `getSafeFileName` by `replaceForwardSlashes` in https://github.com/DataDog/datadog-ci/pull/931/files#diff-d185890b7519424a2afa587baaf3b2ab18edc4710bb53bde9880e20db2896fbeR55
but we shouldn't have. 
Bring back `getSafeFilename`
> [sarif] Sanitize characters from filename

- .github/CODEOWNERS
Change owners of `sarif` command from `ci-app-libraries` to `static-analysis-core`. The reason being, they're the actual owners of the command and should review the PRs affecting it.
Change row in `CODEOWNERS` file.
> Set static analysis team as code owners of `sarif`

- src/commands/dsyms/__tests__/upload.test.ts
- src/commands/dsyms/renderer.ts
Add message stating there might be a delay in processing dsyms as to make it explicit to users that symbolication might not work instantly.
> [RUMM-3399] Add message stating symbol processing will take 5 minutes

- LICENSE-3rdparty.csv
- package.json
- src/commands/junit/api.ts
- src/helpers/__tests__/file.test.ts
- src/helpers/file.ts
- yarn.lock
If we send the normal filename it can contain some characters that would cause 400 errors at the intake. Now we create a [uuidv4](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)) for the filename and send the original filename somewhere else.
Use uuid package and send filename somewhere else as `_dd.report_name`
> [junit] Use uuidV4 for filename

- package.json
- yarn.lock
Bump proxy-agent to remove the deprecated vm2 dependency: https://github.com/TooTallNate/proxy-agents/pull/224
proxy-agent: `6.2.1` → `6.3.0`
> [deps] Bump `proxy-agent` to remove `vm2` dependency

- src/commands/stepfunctions/__tests__/awsCommands.test.ts
- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/__tests__/instrument.test.ts
- src/commands/stepfunctions/awsCommands.ts
- src/commands/stepfunctions/helpers.ts
- src/commands/stepfunctions/instrument.ts
We are asking customers to manually change their step functions definition to inject Step Functions Context Object into Lambda payload. To help customers do this automatically, we add `mergeStepFunctionAndLambdaTraces` flag for customers to opt (default to false) in merging their step functions trace with lambda traces.
Also fixed the issue where the same step functions arn are printed while looping all steps.
For each step functions' steps, we find all default lambda api steps and check if their lambda step payload has special logic. If not, we change their `Payload.$` to `'States.JsonMerge($$, $, false)'` to inject step functions context (which contains the info that is to be hashed by lambda Python/NodeJS layer) into payload. The scenario that we are updating their payload are:
- …
> Add `mergeStepFunctionAndLambdaTraces` option to `stepfunctions` command

- src/commands/lambda/README.md
Now that https://github.com/DataDog/datadog-ci/pull/962 is merged, the `datadog-ci lambda flare` command is expected to be ran in the root of the project directory to autodiscover project files.
If the command is not ran in the correct directory, it will be unable to automatically find project files.
Update README.md in `lambda/README.md`
No tests needed
> [lambda][flare] Update documentation to tell user to run command in project directory

- src/commands/stepfunctions/constants.ts
- src/commands/stepfunctions/helpers.ts
- src/commands/stepfunctions/instrument.ts
https://datadoghq.atlassian.net/browse/SLS-3822
- To help customers enable step functions tracing when they run instrument command, we add `DD_TRACE_ENABLED=true` tag automatically. 
- If customer enables `mergeStepFunctionAndLambdaTraces` flag but they are using legacy lambda integration, we show warning with instructions to them so that they can know their legacy lambda steps' spans cannot merge with step functions span.
Tested in sandbox
```
======= For arn:aws:states:sa-east-1:425362996713:stateMachine:Kimi-Testing-State-machine =========
Will apply the following change:
TagResource:
{
"resourceArn": "arn:aws:states:sa-east-1:425362996713:stateMachine:Kimi-Testing-State-machine",
"tags": [
{
"key": "DD_TRACE_ENABLED",
"value": "true"
}
]
}
TagResource finished successfully!
Will apply …
```
> Add DD_TRACE_ENABLED for stepfunctions instrument and warning for legacy lambda integration

- .github/workflows/release.yml
In #942, we tried to invalidate the cache by passing a specific version to `yarn add`, but the downstream pipelines still occasionally fail ([example](https://github.com/DataDog/synthetics-ci-github-action/actions/runs/5587506326/job/15132248097)).
> ~~If this doesn't work, then we can move the `bump-ci-integrations` job matrix at the very bottom of `.github/workflows/release.yml`, which should add enough delay. **Source: #942**~~
Add a `needs:` dependency on `build`.
> [ci] Make `bump-ci-integrations` depend on `build`

- package.json
- yarn.lock
Fixes https://github.com/DataDog/datadog-ci/security/dependabot/28
A bump for `protobufjs` was made in `dd-trace@3.28.0`: https://github.com/DataDog/dd-trace-js/pull/3383/commits
Update `package.json` and `yarn.lock`.
> [dep] Bump `dd-trace` to `3.29.0`

- package.json
- yarn.lock
This release includes a fix for jest cache: https://github.com/DataDog/dd-trace-js/pull/3445
This does not affect our CI but could potentially affect local development, if we run tests locally with `dd-trace` enabled. 
Bump `dd-trace` to `3.29.1`
> Bump `dd-trace` to 3.29.1 

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
Currently, the wrong property is used for the max parallelization message.
Replace `orgMaxConcurrencyCap` with `onDemandConcurrencyCap`
> [synthetics] Fix max parallelization message

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
This PR adds the `testTimeout` in the global config file, to allow setting a timeout to browser tests.
> [SYNTH-10381] add browser test timeout

- .github/workflows/ci.yml
- .github/workflows/e2e/junit-reports/junit-2.xml
- .github/workflows/e2e/junit-reports/junit.xml
- .github/workflows/e2e/sarif-reports/sarif-report-2.sarif
- .github/workflows/e2e/sarif-reports/sarif-report.sarif
- .gitignore
Add integration tests to junit and sarif commands, to reduce the likelihood of future incidents. 
* Add `DD_API_KEY_CI_VISIBILITY` to report to a ci visibility controlled org. 
* Add two steps to `e2e-test` for junit and sarif uploads.
> [static analysis][ci-visibility] Add e2e tests to sarif and junit uploads

- package.json
- yarn.lock
This PR bumps `dd-trace` to [v3.32.1](https://github.com/DataDog/dd-trace-js/releases/tag/v3.32.1).
Fixes https://github.com/DataDog/datadog-ci/security/dependabot/32 (vulnerability of `import-in-the-middle`).
- Bump `dd-trace`
> [dep] Bump `dd-trace` to 3.32.1

- src/commands/synthetics/__tests__/api.test.ts
This PR reduces the duration of the "Retry policy" unit tests by leveraging fake timers.
> [synthetics] Use fake timers for api retries unit tests

- src/cli.ts
- src/commands/dsyms/upload.ts
- src/commands/flutter-symbols/__tests__/upload.test.ts
- src/commands/flutter-symbols/upload.ts
- src/commands/git-metadata/library.ts
- src/commands/git-metadata/upload.ts
- src/commands/lambda/flare.ts
- src/commands/lambda/tags.ts
- src/commands/react-native/upload.ts
- src/commands/react-native/utils.ts
- src/commands/sourcemaps/upload.ts
- src/commands/stepfunctions/instrument.ts
- src/commands/version/cli.ts
- src/helpers/flare.ts
- src/helpers/version.ts
- src/index.ts
This PR replaces all `require('../path/to/package.json')` to get the package's version by a shared `version` constant.
It also exports that constant for lib users:
```ts
import {version} from '@datadog/datadog-ci`
```
This also fixes a bunch of warnings, and makes all the commands more consistent.
- Create a new `src/helpers/version.ts` module, which only exports a `version` constant.
- I chose not to change the namings in the commands. They sometimes redeclare the variable globally or as a class field.
- I chose to name it `version` **and not `cliVersion`** because for lib users, what we export is not a CLI, but a "datadog-ci" library.
> Provide `version` as a shared and exported constant

- src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/lambda/__tests__/functions/instrument.part2.test.ts
- src/commands/lambda/functions/instrument.ts
Handler for NodeJS and Python AWS Lambdas was not being set properly on interactive mode.
Due to not checking if we were running on such mode when deciding to update the handler.
Check either if layer version is set or we are in interactive mode.
> [lambda] fix handler not being set when running interactive mode

- src/commands/git-metadata/upload.ts
- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/__tests__/functions/instrument.part2.test.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/functions/instrument.ts
See [ticket](https://datadoghq.atlassian.net/browse/SLS-2713?atlOrigin=eyJpIjoiZTUxZDBiOTgwMGI3NGE2ZWI4MGRjMzEzZWZiYmRiMTAiLCJwIjoiaiJ9) and [issue](https://github.com/DataDog/datadog-ci/issues/737) 
Previously, the `lambda` command only accepted `DATADOG_API_KEY` as an env var. This PR will allow users to pass in both `DD_API_KEY` and `DATADOG_API_KEY`. 
Set `apiKey` value to either `DD_API_KEY` or `DATADOG_API_KEY` env var
> [lambda] Fix api key handling for lambda to accept DD_API_KEY

- src/commands/cloud-run/README.md
- src/commands/lambda/README.md
Now that the `datadog-ci cloud-run flare` command is available, we add documentation on how to use the command. This PR also makes some small changes to the `lambda flare` documentation and removes an unused footer link.
- Create the `src/commands/cloud-run/README.md` file
- Update the `src/commands/lambda/README.md` file
No tests needed
> [flare] Add cloud-run flare documentation & update lambda flare documentation

- .github/CODEOWNERS
This command is now maintained by the RUM Browser SDK team.
> Make rum-browser owner of the sourcemaps upload command

- src/commands/gate/evaluate.ts
- src/helpers/retry.ts
If the command execution time is greater than the command timeout, bail to avoid retrying.
> [gate] If the command execution time is greater than the command timeout, bail to avoid retrying

- package.json
- Add --version and --help root arguments by @Drarig29 in https://github.com/DataDog/datadog-ci/pull/1031 
- Bump dd-trace to 3.32.1 to fix https://github.com/DataDog/datadog-ci/security/dependabot/32 (vulnerability of import-in-the-middle) by @Drarig29 in https://github.com/DataDog/datadog-ci/pull/1027
- [flare] Add cloud-run flare documentation & update lambda flare documentation by @nhulston in https://github.com/DataDog/datadog-ci/pull/1037
- [gate] update the command to wait for the time returned from the service, and add `--timeout` flag by @liashenko in https://github.com/DataDog/datadog-ci/pull/1013
- [gate] add support for `DD_APP_KEY` by @liashenko in https://github.com/DataDog/datadog-ci/pull/1017
- [sbom] add beta sbom upload command by @juli1 in …
> Publish v2.19.0

- README.md
The new instructions will look like:
---
1. Create a new branch for the version upgrade.
2. Update the `package.json` version to `X.X.X`, commit the change `vX.X.X` and tag it with `git tag vX.X.X`.
- You may refer to [Semantic Versioning](https://semver.org/#summary) to determine what level to increment.
4. Push the branch **along with the tag** with `git push --tags origin name-of-the-branch`, create a PR, and get at least one approval.
- [Create a draft GitHub Release (prefilled link)](https://github.com/DataDog/datadog-ci/releases/new?title=%3Csame-as-tag%3E&body=%3C!--%20Use%20the%20%22Generate%20release%20notes%22%20button%20at%20the%20top%20right,%20then%20categorize%20the%20changes%20--%3E) and **save it as a draft**.
- Please categorize the changes by product or "Documentation" / …
> [chore] Update release instructions

- src/helpers/__tests__/flare.test.ts
This unit test sometimes fail because `Math.min('9999999999999', Date.now())` always returns `Date.now()`, which may be different than a previous `Date.now()`.
- Use fake timers to get rid of the flakiness
> [test] Fix flaky test for `validateStartEndFlags()`

- src/commands/react-native/__tests__/fixtures/react-native/scripts/react-native-xcode.sh
- src/commands/react-native/__tests__/xcode.test.ts
- src/commands/react-native/xcode.ts
After the clipanion v3 migration, the `react-native xcode` command started to fail when no script path was provided (which is the default case).
This was detected by our E2E tests that started failing right after the `2.19.0` release.
This happens as when we are in the constructor, `Option.String({ required: false })` returns an object (so the default is never applied) that is later changed (how?) to `undefined` when we access the attribute inside the `execute` context.
This wasn't tested so it was hard to catch during the migration, I've adapted the code to make it more testable as well.
We now apply the default when accessing the `scriptPath` attribute.
> Fix default react native xcode script path

- src/commands/gate/__tests__/evaluate.test.ts
- src/commands/gate/evaluate.ts
- src/commands/gate/interfaces.ts
Mark last retry from datadog-ci gate to be able to send failed gate executions to EvP from the service.
We want to provide better visibility in Datadog in the following cases:
* one or more rule evaluations failed during the last request from datadog-ci
* datadog-ci timed out before finishing the evaluation
Currently Quality Gates service is not aware of internal datadog-ci retries, so we can’t send CIGATE events to EvP on the last request for the cases mentioned above.
More context in the [RFC](https://docs.google.com/document/d/1Cj5i5rs_S85AueP7m60gg4iWYVZ-Opr-SB2VpHzvEvE/edit)
When it's a last retry attempt or the remaining wait time is 0, add `isLastRetry:true` to the API request.
> [CIAPP-7523] Mark last retry from datadog-ci gate

- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils.ts
Add `resourceUrlSubstitutionRegexes` config to datadog-ci's synthetics command.
https://datadoghq.atlassian.net/browse/SYNTH-11115
Add it in types, and in what we use from the configuration.
> [SYNTH-11115] Add new resourceUrlSubstitutionRegexes config

- src/commands/gate/api.ts
In the previous [PR](https://github.com/DataDog/datadog-ci/pull/1055) the logic to send `is_last_retry` on the last request to the service was implemented. 
But it doesn't actually send `is_last_retry` option in the payload to the service.
This PR is fixing this issue.
Encode `is_last_retry` option in the payload.
> Fix sending is_last_retry in the payload

- src/commands/gate/README.md
- src/commands/gate/__tests__/evaluate.test.ts
- src/commands/gate/evaluate.ts
- src/commands/gate/utils.ts
Removing `DATADOG_*` environment variables support in the gate command, as these environment variables are deprecated :)
> [CIAPP-7371] Remove "DATADOG_*" env variables support in the gate command

- package.json
Now that `vm2` was removed (https://github.com/DataDog/datadog-ci/pull/993), we don't need to include some of its files in the standalone binary anymore.
Remove the last references to `vm2` under `pkg.scripts` in `package.json`.
> [chore] Clean up list of files in standalone binary

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/utils.ts
This PR adds a `--selectiveRerun` input, which is disabled by default.
When using this flag to trigger Synthetics tests, only the tests which previously failed for the same commit will be retried.
- Pass a `selective_rerun` boolean in the trigger payload.
> [synthetics] Add `--selectiveRerun` input

- LICENSE-3rdparty.csv
- package.json
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/tunnel/tunnel.test.ts
- src/commands/synthetics/__tests__/tunnel/websocket.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/tunnel/blockedIPs.ts
- src/commands/synthetics/tunnel/index.ts
- src/commands/synthetics/tunnel/tunnel.ts
- yarn.lock
Adds support for blocking/allowing particular IP addresses in synthetics tests that use the tunnel. Also includes default blocked IP addresses that align with the IANA recommended blocked IP addresses.
Adds a few things:
1. The options `allowedIPRanges`, `blockedIPRanges` and `enableDefaultBlockedIPRanges`
2. Logic to perform IP validation on individual requests made through the tunnel to particular IP addresses.
> [SYNTH-10966] Support blocking IP addresses in the tunnel

- src/commands/git-metadata/__tests__/gitdb.test.ts
- src/commands/git-metadata/gitdb.ts
There are situations where the unshallow command fails: 
* If the local HEAD is a commit that has not been pushed to the remote
* If the CI is working on a detached HEAD or branch tracking hasn’t been set up
We want to try to work in those situations.
Adding fallbacks if either of those cases happen.
> [git-upload] Improve unshallow process

- .github/workflows/ci.yml
- bin/check-junit-upload.js
- package.json
Add e2e test for JUnit XML report upload: we now not only upload data and check the return status, but query the datadog API to check that test data has actually arrived to the platform. 
Add a `bin/check-junit-upload.js` script to query the datadog API.
> Add e2e check for junit xml test data

- LICENSE-3rdparty.csv
- package.json
- src/commands/lambda/functions/commons.ts
- yarn.lock
After [this change](https://github.com/DataDog/datadog-ci/pull/1074/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR751-R753) in https://github.com/DataDog/datadog-ci/pull/1074, we reverted our vulnerability fix for:
- https://github.com/DataDog/datadog-ci/security/dependabot/25.
Also, it closes https://github.com/DataDog/datadog-ci/issues/471.
**Only** bumping `@aws-sdk/credential-providers` from `3.358.0` to `^3.427.0` is required to fix the vulnerability. But it's better to sync all versions.
> [dep] Bump `aws-sdk` to fix `fast-xml-parser` vulnerability

- src/commands/lambda/README.md
- Adds an example instrumenting multiple Lambda functions by their ARNs
- Updates versions in examples to use latest extension version (49) and latest Python version (81)
Updates the doc
> Add example of instrumenting multiple Lambda functions by ARN

- src/commands/sbom/__tests__/fixtures/java-go.sbom.json
- src/commands/sbom/__tests__/fixtures/ruby.sbom.json
- src/commands/sbom/__tests__/license.test.ts
- src/commands/sbom/__tests__/payload.test.ts
- src/commands/sbom/language.ts
- src/commands/sbom/license.ts
- src/commands/sbom/types.ts
We want to make sure we can parse SBOM for Ruby, Go and Maven/Java
We are adapting the language and license detection. We are testing by having an SBOM generated for each of those languages.
> SBOM: support ruby, go and maven/java

- package.json
Creating the release 2.23.0
CI Visibility:
* Add support for AWSCodePipeline by @albertvaka in https://github.com/DataDog/datadog-ci/pull/1085
Static Analysis:
* adapt SBOM payload by @juli1 in https://github.com/DataDog/datadog-ci/pull/1090
* SBOM: support ruby, go and maven/java by @juli1 in https://github.com/DataDog/datadog-ci/pull/1093
Serverless:
* Add example of instrumenting multiple Lambda functions by ARN by @sfirrin in https://github.com/DataDog/datadog-ci/pull/1092
Dependencies:
* Bump @babel/traverse from 7.22.10 to 7.23.2 by @dependabot in https://github.com/DataDog/datadog-ci/pull/1089
**Full Changelog**: https://github.com/DataDog/datadog-ci/compare/v2.22.1...v2.23.0
> Creating release 2.23.0

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
Before this PR, when using `datadog-ci synthetics run-tests -f ~/tests.synthetics.json`, the terminal used to interpret `~` and pass `$HOME/tests.synthetics.json` to datadog-ci, which then printed:
```
Finding files in /Users/john.doe/path/to/current/directory/Users/john.doe/tests.synthetics.json
```
if the command was run from `~/path/to/current/directory`.
"Finding files in" makes it sound like the passed glob is a directory (i.e. something which **contains** files), whereas what we're actually doing is to find files which match a specific glob, which may also be the real path of a single file.
So I changed "in" to "matching". And if the glob is an absolute path, we just show that absolute path.
> [synthetics] Improve "Finding files" message

- src/commands/synthetics/README.md
Fix the formatting of the list of CLI options, and add sub-sections.
Reuse the syntax from [here](https://github.com/DataDog/datadog-ci/blob/master/src/commands/synthetics/README.md#global-configuration-file-options), with a line break before the colon `:`.
> [synthetics][docs] Improve upload mobile application section

- src/commands/sbom/__tests__/payload.test.ts
- src/commands/sbom/license.ts
- src/commands/sbom/upload.ts
Remove duplicate licenses in the SBOM payload. Ensure we only send one occurrence of the same license, even if the SBOM file contains it twice.
Use a `Set` to store the licenses we will send.
> [SBOM] remove duplicate licenses

- src/commands/sbom/__tests__/license.test.ts
- src/commands/sbom/__tests__/payload.test.ts
This [test](https://github.com/DataDog/datadog-ci/actions/runs/6785564730/job/18444174279?pr=1102#step:8:48) is printing logs in the CI and it makes it longer to read the Jest output.
Mock the implementation of `console.info` and `console.debug`.
> [test] Suppress console logs in unit tests

- jest.config-standalone.js
- package.json
- src/commands/gate/__tests__/evaluate.test.ts
- src/commands/gate/api.ts
- src/commands/gate/interfaces.ts
- src/commands/git-metadata/gitdb.ts
- src/commands/junit/interfaces.ts
- src/commands/sarif/interfaces.ts
- src/commands/sbom/api.ts
- src/commands/sbom/upload.ts
- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/api.ts
- src/commands/trace/interfaces.ts
- src/helpers/__tests__/retry.test.ts
- src/helpers/__tests__/utils.test.ts
- src/helpers/interfaces.ts
- src/helpers/utils.ts
- yarn.lock
Closes https://github.com/DataDog/datadog-ci/issues/1096
Bumping `axios` to `1.6.0` came with 2 issues:
- https://github.com/axios/axios/discussions/5866, fixed in a5c801aba9fa8131aeefc4ffa75002df67156c8e
- Sending requests with `FormData` (which sends `multipart/form-data` payloads) was failing silently in our backend with only a warning.
- For reference, the warning was `Decoder has partially decoded field`, which was probably caused by an incorrect boundary. Bumping `form-data` from `3.0.1` to `4.0.0` ([compare changes](https://github.com/form-data/form-data/compare/v3.0.1...v4.0.0)) solved the issue: 41ce71b54e19deacf6953865dd14ee3031cf61c4
- This bug was caught in [one of our e2e tests](https://github.com/DataDog/datadog-ci/actions/runs/6704428841/job/18217012787#step:9:43), for the …
> [dep] Upgrade axios from 0.21.4 to 1.6.0

- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/utils.ts
This PR changes how often the `run-tests` command displays test runs. Before this PR, we were only showing them once, at the very end.
With this PR, datadog-ci will show each test run as soon as we detect it's failed or passed.
Before:
- `getBatch()` every 5 seconds
- Use `emittedResultIndexes` to keep track of the in-batch results we emitted with `Reporter.resultReceived()` (minimal information about the result)
- Once the batch is not `in_progress` anymore, use `pollResults()` to get the full information of all results, and display their information with `renderResults()`, which calls `Reporter.resultEnd()` multiple times
After:
- `getBatch()` and `pollResults()` every 5 seconds
- Use `emittedResultIndexes` to keep track of the in-batch results we emitted with …
> [synthetics] Show test runs as they arrive

- .github/CODEOWNERS
- src/cli.ts
- src/commands/dora/README.md
- src/commands/dora/__tests__/deployment.test.ts
- src/commands/dora/api.ts
- src/commands/dora/cli.ts
- src/commands/dora/deployment.ts
- src/commands/dora/interfaces.ts
- src/commands/dora/renderer.ts
- src/helpers/git/__tests__/format-git-span-data.test.ts
- src/helpers/git/get-git-data.ts
Adds a new command to send deployment events for DORA Metrics
- [RFC](https://docs.google.com/document/d/1b3cQnj0r3KPKfFfEaO2kwuWt0JVAHBfoN14Iu0WrIjo/edit?pli=1#heading=h.rnd972k0hiye)
- [Proposal specific about the command](https://docs.google.com/document/d/1BBvtZyqNY-udLp8EVnNVnaroxHPUWZ4vrpDe52Q9SyU/edit#heading=h.srzhgb6sxwrv)
It's mostly a shortcut to avoid a curl command. It handles the DD_SITE and retries. It also helps a bit on figuring reasonable defaults some of the attributes for the API and runs some validations:
- Deployment finished-at defaults to now
- Get git info automatically (although it logs a warning in case this is a mistake and the deployment happens from a different repository or commit)
```
Send a new Deployment event for DORA Metrics to Datadog.
━━━ Usage …
```
> [CIVIS-7830] DORA Metrics deployment command

- LICENSE-3rdparty.csv
- package.json
- src/commands/lambda/__tests__/functions/instrument.part1.test.ts
- src/commands/lambda/__tests__/functions/uninstrument.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/__tests__/uninstrument.test.ts
- src/commands/lambda/constants.ts
- src/commands/lambda/flare.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/uninstrument.ts
- yarn.lock
Adds retries to AWS requests made by the lambda cli due to `Throttling Exception: Rate Exceeded` errors when instrumenting a large number of Lambda functions.
https://datadoghq.atlassian.net/browse/SVLS-3931
* Uses [@smithy/util-retry](https://github.com/awslabs/smithy-typescript) package to retry failed requests to AWS
* Retries 4 times after initial attempt with exponential backoff starting at 1 second
* `getLambdaFunctionConfigsFromRegex` previously had dedicated retry logic but this was removed in favor of the retry strategy being used for all AWS requests
* From manual testing, Throttling Exceptions occur on `ListTagsCommand` requests. However the retry logic is applied to all AWS requests to handle potential Throttling Exceptions in environments different than the one used to test. …
> [SVLS-3931] Adds retry strategy with exponential backoff to AWS requests in Lambda Command

- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/utils.ts
💡 _Better reviewed commit by commit_
Our unit tests were incomplete and #1097 broke something when we have residual results, i.e. when datadog-ci stops polling before our backend.
We can reproduce this edge case with a really small value of `--pollingTimeout`, like 1 millisecond:
**Expected:**
**Actual:**
- Fix the unit tests: 1ef26d01e3f5e04d677645960b35bfb819929f93 and 30d211fc8a3e42991e9c8e3bb88686306dee40dc
- Fix the code: 5e40fc51c918f82ea0ac39ec18eca2082da6f7c1 and a93c75a79390dde14ab0b0709a69e5b3d4b5153d
> [synthetics] Fix the reporting of residual results

- src/commands/flutter-symbols/upload.ts
Reported in https://github.com/DataDog/datadog-ci/issues/1117
No need for more information: this PR just removes the reporting of `0` which could be mistaken for a number of uploaded files.
- ~[ ] Feature or bugfix MUST have appropriate tests (unit, integration)~ (the text output is not unit tested in this command)
> [flutter-symbols] Improve message for mapping upload

- package.json
- yarn.lock
Latest versions should include support for Node 20 runtime in AWS Lambda.
Upgraded all packages just to keep version consistency.
Although the main ones should be `@aws-sdk/types` and `@aws-sdk/client-lambda`, this ensures we are consistent while upgrading the SDK version.
> [dep] Bump @aws-sdk/* to `v3.454`

- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/run-tests-lib.ts
We want to `execute` tests programmatically and benefit from everything that `execute` provides (setting up reports, rendering results etc.), but also gather the results and summary, and process them on our side (log a custom summary in console etc.)
Currently datadog-ci just logs things itself, and returns only a `0 | 1` exit code at the end of execution.
Instead of returning `0 | 1`, return an object with detailed info.
> [synthetics] Add `executeWithDetails()` method

- src/commands/synthetics/__tests__/__snapshots__/utils.test.ts.snap
- src/commands/synthetics/__tests__/utils.test.ts
- src/commands/synthetics/utils.ts
We received this [issue](https://github.com/DataDog/datadog-ci/issues/1103). The problem is that if the --failOnMissingTests flag is present and there were no tests found to be run, we should exit with an error.
I included the 'NO_TESTS_TO_RUN' as a reason to fail and also changed the messaging to be an error instead of a log
before:
after:
> [synthetics] Make `failOnMissingTests` fail on "No tests to run"

- .github/workflows/ci.yml
It enables the datadog static analyzer, which allows to:
- get a list of all violations [here](https://app.datadoghq.com/ci/static-analysis?query=service%3Adatadog-ci&index=cicodescan&start=1701949821395&end=1701953421395&paused=false)
- reports all dependencies used, with their security and licenses (upcoming)
Add a CI/CD job to do so.
> [STAL-898] Enable datadog static analyzer

- src/commands/sbom/payload.ts
- src/commands/sbom/types.ts
We need to send the `purl` of a package to the backend API.
1. Add the `purl` in the structure of the payload
2. Extract the `purl` from the SBOM and add it to the payload
> [STAL-904] Add purl to the package information to upload

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
This PR updates the default and junit reporters to report test level failures (`result.failure`).
The default reporter will now always show a test level failure when it's present. It's only a visual difference.
The JUnit reporter will now **fall back to a test level failure** when no other failures were reported from the step level (e.g. for a multi-step or browser test).
It's only a fall back (and not nothing that is always added) because it may be redundant with what was already reported from the step level, causing the stats to be wrong: if a step timeout is reported both from the test level and from the step level, the `failures` count would be `2` instead of `1`, which is wrong.
Also, generally on the private location side, the step level failure is replicated at the test level, so …
> [synthetics] Report test level failures

- src/commands/gate/__tests__/evaluate.test.ts
- src/commands/gate/renderer.ts
- src/commands/gate/utils.ts
Add the rule url when printing a rule evaluation.
Reusing `getCommonAppBaseURL` method, build a url to the rule in Datadog.
> [CIVIS-2981] Add the rule url when printing a rule evaluation

- src/commands/lambda/__tests__/functions/instrument.part2.test.ts
- src/commands/lambda/constants.ts
It's now supported in GA for AWS Lambdas.
Added constant and unit tests.
> [lambda] support Python 3.12

- package.json
- yarn.lock
Fixes:
* Prototype pollution vulnerability https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788
* ReDoS vulnerability https://security.snyk.io/vuln/SNYK-JS-AXIOS-6124857
This upgrade [jumps over multiple patch releases](https://github.com/axios/axios/releases), which all are low risk.
Related: https://github.com/DataDog/datadog-ci/pull/1154
> [dep] Bump axios to `1.6.5`

- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-tests-command.ts
This PR fixes a bug which makes it impossible to turn on `selectiveRerun` via config files. This is because the default value of the CLI parameter is `false` and not `undefined`, thus the `selectiveRerun` value set in a config file is overridden.
Remove the default value for the CLI parameter, and only rely on `DEFAULT_COMMAND_CONFIG`, which is the source of truth for default config parameters.
> [synthetics] Fix enabling selective re-run with config file

- src/commands/metric/README.md
- src/commands/metric/__tests__/metric.test.ts
- src/commands/metric/metric.ts
- src/commands/tag/README.md
- src/commands/tag/__tests__/tag.test.ts
- src/commands/tag/tag.ts
- src/helpers/ci.ts
Adding support for custom tags at job level for GitHub by relying on the `GITHUB_JOB` environment variables. In case the [name](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name) property is used when defining jobs, customers will need to additionally expose the `DD_GITHUB_JOB_NAME` pointing to that name.
> Support custom tags and metrics for GH jobs

- package.json
Releasing version 2.29.0.
* Support custom tags and metrics for GH jobs by @andrea-mosk in https://github.com/DataDog/datadog-ci/pull/1161
**Full Changelog**: https://github.com/DataDog/datadog-ci/compare/v2.28.0...v2.29.0
> Creating release v2.29.0

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/utils/public.ts
The current error message ("Result timed out") doesn't give enough information.
Change the error message to be more explicit:
> The batch timed out before receiving the result.
> [synthetics] Change error message for timed out results

- .github/workflows/ci.yml
- README.md
- src/cli.ts
The SCA product is out now and available to customers. We are removing the beta flag.
> Remove sbom from beta

- package.json
- yarn.lock
Closes https://github.com/DataDog/datadog-ci/issues/1164
Bump `ssh2` to `1.15.0`
> [dep] Bump ssh2 to `1.15.0`

- package.json
- yarn.lock
Fixes https://github.com/DataDog/datadog-ci/security/dependabot/35
The vulnerable library was `lodash.pick`, and `dd-trace` removed it from their dependencies (https://github.com/DataDog/dd-trace-js/pull/3999).
The command `yarn why lodash.pick` now returns nothing ✅
> [dep] Bump dd-trace to `3.47.0`

- .gitlab-ci.yml
With our new runners we can now use `docker buildx`.
Change runners.
> [ci] Use docker buildx for public images

- package.json
- yarn.lock
Fixes https://github.com/DataDog/datadog-ci/issues/1164#issuecomment-1930104230
Upgrade `@google-cloud/run`. It had no major changes except migrating to Node 14.
> [dep] Bump @google-cloud/run to `1.0.2`

- src/commands/sbom/__tests__/fixtures/trivy-4.9.json
- src/commands/sbom/__tests__/payload.test.ts
- src/commands/sbom/__tests__/validation.test.ts
- src/commands/sbom/payload.ts
- src/commands/sbom/types.ts
We need to handle the `group` attribute of an SBOM. Previous version only handle `name`, `version` and `language`.
When the payload has a `group` attribute in a dependency, pass it to the payload. Otherwise, set it to `undefined`.
- Added unit test to check a SBOM with `group`
- Ran in staging, see output below 
```
yarn launch sbom upload --service rodrigo --env local src/commands/sbom/__tests__/fixtures/trivy-4.9.json
File src/commands/sbom/__tests__/fixtures/trivy-4.9.json successfully uploaded in 1633 ms
Upload finished
```
> [STAL-1268] Handle group in payload

- .github/workflows/ci.yml
- src/commands/sarif/__tests__/upload.test.ts
This PR adds Node.js 20 to the unit test matrix.
A single unit test was breaking because of a different error message in Node.js 20.
> [ci] Unit test against Node 20

- src/commands/sourcemaps/README.md
Copying the code under "[End-to-end testing process](https://github.com/DataDog/datadog-ci/tree/master/src/commands/sourcemaps#end-to-end-testing-process)" does not work and throws this error:
```
❌ --minified-path-prefix should either be an URL (such as "http://example.com/static") or an absolute path starting with a / such as "/static"
```
That is because the `--minified-path-prefix` URL parameter is missing `:`.
Just updating docs.
> docs(sourcemaps): fix minified path prefix URL example on E2E tests

- .github/workflows/release.yml
We want datadog-ci releases to trigger the creating of PRs in the integrations to update the version of datadog-ci
We added the 2 new integrations in the list of integrations that need to be triggered
> [SYNTH-11928] Reference Bitrise integrations in datadog-ci

- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/utils/public.ts
In cases where we would have a "/" at the end of the url in a `Test Config` or a cli command like
`datadog-ci synthetics run-tests --public-id ''`
We would get a `[] Found test "undefined"` message. Neither of these are desired behaviours.
For the first case we want the test to be correctly identified. And for the 2nd we want to raise an error. 
This PR is addressing both by improving the way we find the public_id in a url and in case we don't find it we raise an error.
> [SYNTH-12059] Trailing slash in test suite id leads to `[] Found test "undefined"`

- src/commands/dsyms/interfaces.ts
- src/commands/flutter-symbols/__tests__/upload.test.ts
- src/commands/flutter-symbols/upload.ts
- src/commands/git-metadata/interfaces.ts
- src/commands/react-native/__tests__/interfaces.test.ts
- src/commands/react-native/interfaces.ts
- src/commands/sourcemaps/interfaces.ts
- src/commands/unity-symbols/__tests__/upload.test.ts
- src/commands/unity-symbols/upload.ts
- src/helpers/__tests__/upload-fixtures/file.txt
- src/helpers/__tests__/upload.test.ts
- src/helpers/upload.ts
This is another attempt to fix #1129 
The file upload retry mechanism is incorrect as it tries to upload the same stream instances multiple times. When a `FormData` (from the `form-data` package) is built with a used stream, the resulting stream never ends, so the request never ends, resulting in a "socket hang up" error.
<details>
<summary>Minimal example with <code>form-data</code> only</summary>
```js
import FormData from "form-data";
import fs from "fs";
(async () => {
const stream = fs.createReadStream("./repro.mjs");
await sendStream(stream); // This works, prints "Start, Data, Data, End"
await sendStream(stream); // This does not end, prints only "Start"
})();
function sendStream(stream) {
return new Promise((resolve, reject) => {
const formData = new FormData(); …
```
> 🐛 [RUM-2721] fix upload retry

- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
Without JUnit report (the `%` with white background is **added by Zsh** to show that a command's `stdout` doesn't end with a newline):
With JUnit report: (notice the missing newline)
Without JUnit report:
With JUnit report:
Add a `\n` at the end of the `Continuous Testing Summary` and at the beginning of the `Created a JUnit report` text.
> [synthetics] Fix newline in text output with JUnit reports

- src/commands/react-native/__tests__/xcode.test.ts
- src/commands/react-native/xcode.ts
https://github.com/DataDog/datadog-ci/issues/1189#issuecomment-1941745706 is related.
It is possible for the `USE_HERMES` environment variable to be set to false. In which case, `process.env.USE_HERMES` would then be `"false"`, causing the check in `shouldComposeHermesSourcemaps` to incorrectly interpret that process env to be true.
Evaluate the actual value of `process.env.USE_HERMES` instead of just checking for its existence.
> `react-native xcode`: Respect `USE_HERMES` env var being set to false

- .gitlab-ci.yml
In #1175, I thought that since `tags: ['arch:arm64']` asks for a arm64 runner, the build `platform` would automatically be set to `arm64`, but it's not enough: https://hub.docker.com/r/datadog/ci/tags?name=v2.30.0 was built for `amd64` twice.
- Use a single job (`build-docker-image`) to build a **multi-arch image** thanks to `--platform linux/amd64,linux/arm64/v8`.
- Remove the `-amd64` and `-arm64` suffix from our internal tags.
I took inspiration from the [`observability-pipelines-worker`'s image build process](https://github.com/DataDog/observability-pipelines-worker/blob/a1e730d415d59af6367f0ba73ee70def2e614118/.gitlab/release.yml#L31-L32).
This will be fixed in `v2.30.1`.
> [docker] Fix `amd64` double building

- src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/constants.ts
Ruby 2.7 went in deprecation phase 2 as per [AWS Lambda Runtime Deprecation Policy](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy).
Removing all mentions of it.
> [lambda] Deprecate Ruby 2.7 instrumentation

- src/commands/lambda/__tests__/functions/commons.test.ts
- src/commands/lambda/constants.ts
Python 3.7 went in deprecation phase 2 as per [AWS Lambda Runtime Deprecation Policy](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy).
Removing all mentions of it.
> [lambda] Deprecate Python 3.7 instrumentation

- src/commands/lambda/__tests__/functions/uninstrument.test.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/constants.ts
Dotnetcore 3.1 went in deprecation phase 2 (a long time ago) as per [AWS Lambda Runtime Deprecation Policy](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy).
Removing all mentions of it.
> [lambda] Deprecate dotnetcore 3.1 instrumentation

- src/commands/sarif/renderer.ts
- src/commands/sbom/upload.ts
Add a link to the results page to direct the user to our product page on datadog.
We are adding a link to the code-analysis dashboard to check the results.
```
...
✅ Uploaded 1 files in 0.336 seconds.
ℹ️ Results available on https://app.datad0g.com/ci/code-analysis
=================================================================================================
```
**Prod**
```
File /Users/julien.delange/datadog-ci-sbom.json successfully uploaded in 381 ms
Upload finished, please check results on https://app.datadoghq.com/ci/code-analysis
```
**Staging**
```
File /Users/julien.delange/datadog-ci-sbom.json successfully uploaded in 366 ms
Upload finished, results available on https://app.datad0g.com/ci/code-analysis
```
> [STAL-1340] Add link to results

- src/commands/metric/metric.ts
We had wrongly added the `--tags` option instead of the `--metrics` option.
> [CIVIS-9031] Fix bug in metrics command examples

- src/commands/junit/README.md
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/api.ts
- src/commands/junit/interfaces.ts
- src/commands/junit/renderer.ts
- src/commands/junit/upload.ts
- src/commands/tag/README.md
Reverts DataDog/datadog-ci#1203
> Revert "[CIVIS-9031] Deprecate 'metrics' naming in favour of 'measures' in junit cmd"

- src/commands/git-metadata/__tests__/library.test.ts
- src/commands/git-metadata/library.ts
Currently, the `datadog-ci git-metadata upload` command both:
- synchronises GitDB
- uploads a payload with tracked files to the legacy sourcemap intake
But the `uploadGitCommitSha` function that is exported and used in the serverless plugin (here: https://github.com/DataDog/serverless-plugin-datadog/blob/51b7844efd6224d1a4fb5c1215453aac3038f915/src/index.ts#L302) only upload to the sourcemap intake.
We want all upload tooling to synchronize GitDB, and eventually deprecate the sourcemap store for Git metadata.
This PR updates the exported function to also synchronize GitDB.
> [git-metadata] Make exported function upload to gitdb

- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/run-tests-lib.ts
Currently the logic that fetches the Test Config and uses to override the previous configurations only gets executed if publicIds were not defined before that point through the Global Level Configuration (Global Config, Env Variables, CLI params). It should happen always instead, so fix that.
Moved out the code that fetches the Test Config out of that if statement and did some small refactoring. Also added tests to make sure that we account for that edge case
> [SYNTH-13000] Fix bug where Test Config was not being used when a public_id was already defined

- README.md
- src/commands/gate/README.md
- src/commands/gate/__tests__/evaluate.test.ts
- src/commands/gate/evaluate.ts
- src/commands/sbom/README.md
`APP` isn't an acronym, but just the abbreviation for "Application" key.
Global search and replace
> [docs] Replace `APP` with `App`

- README.md
- src/commands/sarif/renderer.ts
- src/commands/sarif/upload.ts
- src/commands/sbom/api.ts
- src/commands/sbom/renderer.ts
- src/commands/sbom/upload.ts
- src/helpers/tags.ts
Adds validation and a pretty message when the commands are not run in `.git` directory. 
Updates the root readme as we've updated the documentation and each product has it's own page now.
We check for a `git.repository_url` as this field is required in the backend for further processing and in the case of the SARIF upload, this failure will not be surfaced to the user. 
Ran both commands locally in and outside of a `.git` directory.
**SARIF:**
**SBOM:**
> [STAL-998] Add metadata validation in SBOM/SARIF upload commands

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
Related: #1217 
> [!NOTE]  
> 💡 Can be reviewed commit by commit.
The main reason for this PR is that a customer reported their CI was failing for ~4 minutes each time we publish a release.
Their logs:
```bash
Run curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     9    0     0    0     0      0      0 --:--:-- …
```
> [chores] Improve release process

- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
Closes #1222 
The default behavior of the `junit upload` command was changed to skip the upload of git metadata **by default** in https://github.com/DataDog/datadog-ci/pull/928 for performance reasons (released in [v2.15.0](https://github.com/DataDog/datadog-ci/releases/tag/v2.15.0)).
But in case users want to be explicit about skipping the git metadata upload, passing `--skip-git-metadata-upload` should work without an extra `=true` at the end. This behavior broke because of #1021.
Use `tolerateBoolean: true`
> [junit] Tolerate `--skip-git-metadata-upload` as boolean flag

- .github/release.yml
- .github/workflows/pr-required-labels.yml
- CONTRIBUTING.md
Since we use the "Create a merge commit" strategy when merging release PRs, the merge commit always shows _after_ the corresponding `vX.X.X` commit in the history:
Because of that, the release PR ends up in the release notes for `v2.32.0...v2.32.1`:
- Require all release PRs to have a `release` label
- Exclude PRs with the `release` label in the release notes
- Update the release process instructions
> [chores] Exclude `release` label from release notes

- .github/workflows/publish-release.yml
I used to have this `needs:` property [during my testing](https://github.com/DataDog/datadog-ci/actions/runs/8249102051/workflow#L152), but forgot to add it in #1219... 🤦 
**During my testing:**
**Right now:**
- Add `needs:` to `npm-publish`
> [chores] Add `needs:` to `npm-publish`

- .github/workflows/publish-release.yml
I worked on #1217 (introduces `.github/release.yml` to configure the release notes) and #1219 separately, so I hadn't tested the job summary with release notes **configured with `.github/release.yml`**.
Turns out that in that case, the release notes start with a HTML comment like so:
```html
```
And this results in the markdown codeblock being rendered incorrectly. All the `#` and `*` are missing:
I reported the bug here: https://github.com/actions/toolkit/issues/1689
For now, we can replace `\n\n` with `\n` after the HTML comment.
> [chores] Add missing `.exe` and fix release notes bug

- src/commands/sbom/upload.ts
Adding a message that explicitly mentions what to do if the API or APP keys are not defined as requested by customer.
> [STAL-1431] static-analysis add explicit message

- package.json
- yarn.lock
Closes https://github.com/DataDog/datadog-ci/security/dependabot/39
Bump axios, which is now using `follow-redirects@^1.15.6`
> [dep] Upgrade axios to `1.6.8`

- src/commands/sbom/language.ts
- src/commands/sbom/types.ts
Add .net support
Correctly map the language when the package purl contains `pkg:nuget`.
```
yarn launch sbom upload --service vscode --env local ~/tmp/debug.json
[...]
✅ Uploaded 1 files in 0.443 seconds.
ℹ️  Results available on https://app.datad0g.com/ci/code-analysis
=================================================================================================
```
Removed the message about license not found which is noisy and this logic will move into the backend.
> [STAL-1561] add .net support

- .github/release.yml
- .github/workflows/publish-release.yml
The products in the changelog should be alphabetized, while the other sections should appear in their order of priority: chores are far less important than vulnerability fixes.
Even after https://github.com/DataDog/datadog-ci/pull/1228, the release notes [were still not rendering properly](https://github.com/actions/toolkit/issues/1689#issuecomment-1997415469). So I decided to just get rid of this problematic codeblock, and just give a link to the draft release.
Update some YAML 😁 
> [chores] Fix last nits about the release process

- .github/workflows/ci.yml
Fixes these warnings:
Bumping github actions.
> [dep] Bump `upload-artifact` github action

- src/commands/synthetics/batch.ts
- src/commands/synthetics/utils/public.ts
- https://github.com/DataDog/datadog-ci/pull/1252 (← **you are here**)
- https://github.com/DataDog/datadog-ci/pull/1251
This PR is a noop. All moved functions were **NOT** exported.
Reduce the `utils/public.ts` file size by moving all non-exported and batch-related functions to `batch.ts`.
> [synthetics] Move non-exported utils to `batch.ts`

- src/commands/synthetics/README.md
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- https://github.com/DataDog/datadog-ci/pull/1254 (← **you are here**)
- https://github.com/DataDog/datadog-ci/pull/1255
This PR aligns what we say in the README and the actual reporter interface.
- Use `ResultInBatch` instead of `Batch['results'][0]` since it's exported
- Order in the order of events, instead of alphabetically because it makes zero sense.
> [synthetics] Align README and reporter interface

- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/reporters/default.ts
This PR changes the wording for selective re-run to align with the UI, which talks about batches (and not CI runs).
Update wording.
> [synthetics] Change wording around selective re-run

- src/commands/sbom/__tests__/payload.test.ts
Following https://github.com/DataDog/datadog-ci/pull/1244, the `lint:ci` script is failing.
Run `yarn format`
> [chores] Fix lint on main branch

- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/batch.ts
- src/commands/synthetics/utils/public.ts
- https://github.com/DataDog/datadog-ci/pull/1252
- https://github.com/DataDog/datadog-ci/pull/1251 (← **you are here**)
Currently, it can sometimes happen that nothing is present [in the `ServerResult` inside `Result`](https://github.com/DataDog/datadog-ci/blob/cce0c563decef34f1d70ae5540f6afb07177ef98/src/commands/synthetics/interfaces.ts#L134).
Instead, you'll only have an `eventType: created` property:
```js
{
executionRule: 'blocking',
location: 'Ireland (AWS)',
passed: true,
result: {
eventType: 'created'
},
resultId: '5311971567944320288',
test: {
public_id: 'aaa-bbb-ccc',
name: 'Some test name',
type: 'browser',
...
},
timedOut: false,
timestamp: 1234567890,
}
```
This means that:
- The default reporter would not report the information correctly if the test was failing, because in …
> [SYNTH-13138] Wait for each `ServerResult` to be available

- src/commands/git-metadata/upload.ts
If another command uses `git-metadata upload` and accept a `DD_API_KEY` environment variable, the command will fail.
We set the `apiKey` field in the `getMetricsLogger` utils, so it will use the which ever API key is set on [this line](https://github.com/DataDog/datadog-ci/blob/13beb67eadf79cb92abc2b509c6e56b992afe9a3/src/commands/git-metadata/upload.ts#L53) instead of just falling back to solely a `DATADOG_API_KEY` env var.
> [source-code-integration] Set `apiKey` in logger

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/batch.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/utils/public.ts
- https://github.com/DataDog/datadog-ci/pull/1254
- https://github.com/DataDog/datadog-ci/pull/1255  (← **you are here**)
The frontend will now provide more information when the result isn't found yet, but known to be in-progress in the batch. For this, we change `?from_ci=true` to `?batch_id=<batchId>` in the results link.
Since the lines were becoming really long, I added a line break. The `⎋` icon represents an external link, so I kept it next to the result link.
> [SYNTH-12914] Include `?batch_id` in result links

- src/commands/deployment/mark.ts
- src/commands/tag/README.md
- src/commands/tag/__tests__/tag.test.ts
- src/commands/tag/tag.ts
This PR introduces the `--silent` option to the `tag` command. This option, as the README will state, it prevents the tag command from writing to stdout and stderr. One of its uses will be to hide implementation details for the `datadog-ci deployment mark` beta command. That command runs the tag command twice and we do not want the second time to output anything as it would be redundant.
> [ci-visibility] Add silent option to tag command

- src/commands/synthetics/__tests__/test.test.ts
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/test.ts
- src/commands/synthetics/utils/public.ts
- https://github.com/DataDog/datadog-ci/pull/1271 (← **you are here**)
- https://github.com/DataDog/datadog-ci/pull/1272
Fixes a bug introduced in https://github.com/DataDog/datadog-ci/pull/1214 (released in `2.32.1`)
For better unit testing, this PR first moves some non-exported code to a new file named `test.ts`, which contains all S8S-test-related logic.
> [!NOTE]  
> 💡 Better reviewed commit by commit.
The main change of this PR is: 50a262c13af8fea8e7c64cdfcfe77f5f92371351
> [SYNTH-13771] Fix "No tests to run" not being shown anymore

- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/batch.ts
The message was always showing for timed out results because they are very likely to be incomplete. And for timed out results, we do not show anything, so we don't need such message.
- Fix the formatting (add new lines)
- Do not show an error message when an incomplete result is timed out
- Use `reporter.error()` instead of `reporter.info()` because it's more correct semantically
> [synthetics] Fix incomplete residual results message

- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/__tests__/test.test.ts
- src/commands/synthetics/__tests__/utils/__snapshots__/public.test.ts.snap
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/test.ts
- src/commands/synthetics/utils/internal.ts
- src/commands/synthetics/utils/public.ts
- https://github.com/DataDog/datadog-ci/pull/1271
- https://github.com/DataDog/datadog-ci/pull/1272 (← **you are here**)
This PR merges 2 not-so-useful warnings into a single more-useful warning.
The 2 warnings were almost duplicates, and the most important fact is that _only 100 tests_ will be **TRIGGERED**. The fact that datadog-ci will FETCH only 100 tests isn't important.
Also, we never say how many were returned _exactly_, just "more than 100".
The `getTestsList()` function used to be the one reporting the "will be fetched" warning, and https://github.com/DataDog/datadog-ci/pull/1214 changed it to be reported by `getTriggerConfigs()` instead.
The "were fetched" one didn't change: it's still reported by `getTestsToTrigger()`.
My proposition is to only keep the "were fetched" one, and …
> [synthetics] Improve warning for too many tests to trigger 

- .github/workflows/ci.yml
We want to enable the static analyzer with diff-aware and not diff-aware to test the results on a live, public repo
Have two jobs to upload results for this repository:
1. One with diff-aware
2. One without diff-aware
This way we can compare the output in the datadog UI.
> enable diff-aware and non-diff-aware

- src/commands/sarif/__tests__/upload.test.ts
- src/commands/sarif/renderer.ts
- src/commands/sarif/upload.ts
- src/commands/sbom/renderer.ts
- src/commands/sbom/upload.ts
When an SBOM is uploaded and we detect that it's a duplicate, our API will throw a `409` error now. We want to catch this error, add a message explaining it, and exit gracefully.
For SARIF, we don't return an error, so we want to add a note that only one upload is possible.
Check if it's an Axios error and it's a 409 code.
**SBOM**
**SARIF**
> [STAL-1577] Improve SBOM/SARIF messaging

- src/commands/flutter-symbols/helpers.ts
- src/commands/git-metadata/library.ts
- src/commands/git-metadata/upload.ts
- src/commands/react-native/upload.ts
- src/commands/sourcemaps/upload.ts
- src/commands/unity-symbols/helpers.ts
Intake doesn't allow to have a space in the header value, so the whole header is dropped. This PR fixes that.
Alternatively we can have just `datadog-ci` everywhere.
> Fix DD-EVP-ORIGIN header values

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/__tests__/test.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/test.ts
Renaming `global` field in the Global Config to `defaultTestOverrides`. This is done becase having it named global is confusing. We've moved to a intermediary state where we're still backwards compatible and a ticket for the eventual clean up has been created and linked in the appropriate places
Created a new field called `defaultTestOverrides` and if it's not defined but `global` is we copy over to it whatever is in `global`. Otherwise we just use `defaultTestOverrides` as is. The rest of the code has been transitioned to use `defaultTestOverrides`
> [SYNTH-12971] Rename global to defaultTestOverrides

- .github/workflows/ci.yml
- .github/workflows/publish-prerelease.yml
- .github/workflows/publish-release.yml
https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/
Yesterday, the `macos-latest` tag changed:
- From [macOS 12](https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240412.2) (x64) ([example passing run](https://github.com/DataDog/datadog-ci/actions/runs/8807444673/job/24176654538))
- To [macOS 14 arm64](https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240422.3) ([example failing run](https://github.com/DataDog/datadog-ci/actions/runs/8815899406/job/24199749613))
Corresponding docs PR: https://github.com/actions/runner-images/pull/9601
Because of this change, the `setup-node` job started failing with:
```bash
Unable to find Node version '14.18.3' for platform darwin and architecture arm64 …
```
> [ci] Fix macOS jobs failing to download Node.js 14

- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/utils/public.ts
The CLI output was showing `(1 config override)` for every test, and that was misleading since the user didn't set any custom polling timeout.
Do not count `pollingTimeout` if it's set to the default value.
> [SYNTH-12976] Ignore default polling timeout in override count

- src/commands/git-metadata/README.md
Updates the readme for the `git-metadata` command to document the 30d limitation.
> [git-metadata] Update command limitations

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/api.ts
Do not require the etag header be returned when uploading mobile application parts. Azure strictly does not return the etag header.
Just default to empty string for etag field when completing upload. The backend for azure expects this behavior
> [SYNTH-14344] Do not require etag from app part upload

- package.json
- yarn.lock
Keep with latest features and bugfixes for dd-trace: https://github.com/datadog/dd-trace-js/releases/tag/v3.58.0
Bump `dd-trace` to the latest v3 release.
> [dep] Bump `dd-trace`

- .github/workflows/ci.yml
Remove SCA from being run in GitHub action
> Remove SCA from GitHub action

- src/commands/react-native/README.md
- src/commands/react-native/xcode.ts
Introduces a way to override the version name for the upload of iOS React Native sourcemaps, using an environment variable.
> RN: Override iOS upload version with ENV var

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/utils/internal.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/upload-application-command.ts
- src/commands/synthetics/utils/internal.ts
Many configuration properties were not configurable through environment variables:  `configPath`, `failOnCriticalErrors`, `failOnMissingTests`,`failOnTimeout`,`files`,`jUnitReport`,`latest`,`mobileApplicationId`,`publicIds`,`selectiveRerun`,`testSearchQuery`,`tunnel` and `versionName`. This PR adds support for configuring these properties through environment variables, all prefixed with `DATADOG_SYNTHETICS_`.
We fixed this problem by adding the the missing environment variables. In this PR, we also:
- Added `jUnitReport` property to the `Global Config`
- Added `testSearchQuery` to the `DEFAULT_COMMAND_CONFIG` as it was missing
- Created a utility function `toBoolean` to convert environment variable strings to boolean values, while handling edge cases (undefined values).
> [SYNTH-12985] Add properties to env variables

- .github/CODEOWNERS
Add the @DataDog/datadog-ci team as reviewer to every PR.
CODEOWNERS files **aren't additive**: lines appearing after `* @DataDog/datadog-ci` are **overriding** the owners.
- Add `@DataDog/datadog-ci` everywhere
> [codeowners] Add maintainer team everywhere

- src/commands/measure/measure.ts
https://github.com/DataDog/datadog-ci/pull/1205 introduced a `console.log` in the `measure` command that had been used for debugging. We shouldn't have this in the command.
@rodrigo-roca nice catch 💯 
> Remove unnecessary console.log in the `measure` command

- src/commands/measure/measure.ts
Closes #856 
Makes errors more descriptive to the user for the `measure` command. For example if the API validation fails because we send more than 20 measures in a single command:
Before: 
```
Could not send measures: Request failed with status code 400
```
After:
```
Could not send measures: {
"errors": [
"API input validation failed: {'metrics': ['Length must be between 1 and 20.']}"
]
}
```
Looking into error.response instead of error.message.
> Improve measure command error handling

- src/commands/elf-symbols/__tests__/upload.test.ts
- src/commands/elf-symbols/renderer.ts
- src/commands/elf-symbols/upload.ts
* `symbols-location` is now a positional argument
* Allow multiple input locations
* Ignore unreadable directories
`glob` throws an error when it encounter an unreadable directory.
Pass `strict: false`, to make `glob` ignore these errors and then later
recheck if directories are readable and emit a warning if not.
Top-level directory being unreadable results in a an error.
> [PROF-9872] Improve elf-symbols upload command

- .github/workflows/ci.yml
- .github/workflows/publish-release.yml
- standalone-e2e/standalone-binary.test.ts
This PR adds a Github job that creates standalone binaries for ARM64 
Using the Github runners in ARM, I duplicated the `build-binary-ubuntu` job to generate ARM64 binaries.
> [ci] Add build job for Ubuntu ARM

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/__tests__/instrument.test.ts
- src/commands/stepfunctions/helpers.ts
- src/commands/stepfunctions/instrument.ts
Adds the step function context to the state definition when a step function calls another stepfunction. This is gated behind the `--propagate-upstream-trace` or `--merge-step-function-and-lambda-traces` flags.
> Add step function context to nested step function calls

- yarn.lock
Fixes https://github.com/DataDog/datadog-ci/security/dependabot/41
Bump in `yarn.lock` only, as the parent dependency hasn't published a fix yet: https://github.com/googleapis/gax-nodejs/issues/1610
> [dep] Bump @grpc/grpc-js to `1.10.9`

- yarn.lock
Closes https://github.com/DataDog/datadog-ci/security/dependabot/42
> [dep] Bump braces to `3.0.3`

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/mobile.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/mobile.ts
Mobile app validator sends back extracted application metadata about the users app. For temporary apps, this *only* gets passed back to datadog-ci (it isn't persisted anywhere), so datadog-ci must pass it back up when running the test with a temporary app.
Take `extracted_metadata` from app-validator response and send it along with the run-test API call to backend
> [SYNTH-14569] Send validator extracted-metadata for temporary apps

- .github/workflows/ci.yml
- .github/workflows/publish-release.yml
In #1333, we renamed the `datadog-ci_darwin-x64` binary to `datadog-ci_darwin-arm64` for alignment, but didn't keep the original `datadog-ci_darwin-x64`.
This PR updates the CI to build both `datadog-ci_darwin-x64` and `datadog-ci_darwin-arm64`.
Use `macos-latest-large`, which is an x64 image.
> [ci] Bring back x64 macOS binary

- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/run-tests-lib.ts
We discovered a bug where having multiple test configs with the same test id would result in only the first occurence being used multiple time. This was caused by the usage of the `find` function in `getTriggerConfigs` in `run-tests-lib.ts:202`. Check out the [ticket](https://datadoghq.atlassian.net/browse/SYNTH-15171) for more context on how the bug was discovered and how to reproduce it.
- Use `findIndex` and `splice` to remove a test from `testsFromTestConfigs` once it has been found.
- Add test coverage for this issue.
> [SYNTH-15171] Fix multiple test configs with same id bug

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/batch.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/utils/internal.ts
- src/commands/synthetics/utils/public.ts
Every 5 second when the batch is fetched, if a non-final attempt is detected, it's now reported. Before this PR, we used to only report the final attempt.
**Visual:**
Following a recent backend change, all properties of a batch result are updated with non-final attempts (e.g. `retries`, `duration`, `result_id`), and the `status` stays `in_progress` for backwards compatibility.
The main change of this PR is changing from `emittedResultIndexes` to `emittedResultIds`, so that we can report multiple results per result index (i.e. each attempt).
Note that **if the retries are too quick** (less than the polling cycle of 5 seconds), they won't be detected and reported by datadog-ci. For that reason, we may have a single ${{\color{Green}{\textsf{  Passed\ (attempt 3 of 3)\}}}}\$ result, without …
> [SYNTH-9539] Report non-final attempts of a result

- src/commands/gate/__tests__/evaluate.test.ts
- src/commands/gate/api.ts
- src/commands/gate/evaluate.ts
- src/commands/gate/interfaces.ts
- src/helpers/ci.ts
- src/helpers/interfaces.ts
- src/helpers/tags.ts
- src/helpers/utils.ts
Whenever a github action is triggered through a `pull_request` or `pull_request_target`, the `GITHUB_SHA` env var does not point to the head of the branch but to a merge commit that GH does on the spot. 
After this change, in addition to `GITHUB_SHA` we also grab `git.commit.head_sha` by reading `GITHUB_EVENT_PATH`, which is, according to [github](https://docs.github.com/en/actions/learn-github-actions/variables):
> The path to the file on the runner that contains the full event webhook payload. For example, /github/workflow/event.json.
This new tag is also passed as part of `options.pull_request_sha` in the `gate evaluate` payload. 
Read file in `process.env.GITHUB_EVENT_PATH` and grab `event.pull_request.head.sha`
> [gate evaluate] Add `options.pull_request_sha` to the `datadog-ci gate evaluate` payload

- README.md
Using the powershell command as given in the readme, leads to a 404 response page from github.
This is due to the fact, that the URL must not contain the *.exe* extension.
As this is somewhat of the smallest possible contribution I thought it would be okay to just send a PR for the fix instead of having a discussion on it beforehand 😉
> Fix download link for windows binaries

- .github/workflows/pr-required-labels.yml
Enforcing exactly 1 label is too restrictive. For example, a PR changing the docs for one command deserves 2 labels: `documentation` and the label corresponding to the command. The PR would still be categorized as "Documentation" in the release notes.
- Change `mode: exactly` to `mode: minimum`
> [pr-labels] Allow multiple labels on PRs

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/compatibility.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-tests-lib.ts
When the internal query that the selective re-run feature does is rate-limited, the endpoint still returns a 200, and re-runs all tests (ignoring the selective re-run).
In that case, the backend now returns a `selective_rerun_rate_limited` property. This PR adds a log to inform when that happens.
Demo with a rate-limit on staging:
- Update the interface and add a log.
> [SYNTH-13898] Inform when selective re-run is rate-limited

- .github/workflows/e2e/example-global-config.json
- .github/workflows/e2e/global.config.json
- src/commands/synthetics/README.md
Changing the README to make it clear that the run-tests and upload-application commands use the same global config. This was not clear before.
Also updated the example for the global config file to actually have all of the possible thing that you can configure, so people can actually see how they can use the global config
Made changes to the README and added a new example global config file
> [SYNTH-12978] Clarify use of global configuration file in README

- src/commands/synthetics/__tests__/cli.test.ts
- #1373 (← **you are here**)
- #1365
In a previous PR, we added missing test cases for the parameters override precedence.
> When aligning the datadog-ci variables, we realised that a lot of test cases were missing to check the parameters override precedence. This PR adds a part of the missing test cases by refactoring override from config file < ENV < CLI into smaller tests ...
In this PR, we add the rest of the missing test cases, that are: `config file < test file`, `ENV < test file ` and `CLI < test file`
- Add `config file < test file` overriding test
- Add `ENV < test file ` overriding test
- Add `CLI < test file` overriding test
- Remove the now useless `parameters override precedence: global < ENV < test file` test
> [SYNTH-15150] Add the rest of the missing test cases

- package.json
- src/commands/dsyms/__tests__/upload.test.ts
- src/commands/dsyms/__tests__/utils.test.ts
- src/commands/dsyms/upload.ts
- src/commands/elf-symbols/upload.ts
- src/commands/flutter-symbols/__tests__/upload.test.ts
- src/commands/flutter-symbols/upload.ts
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
- src/commands/sarif/__tests__/upload.test.ts
- src/commands/sarif/upload.ts
- src/commands/sourcemaps/upload.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/utils/public.ts
- src/commands/unity-symbols/__tests__/upload.test.ts
- src/commands/unity-symbols/upload.ts
- yarn.lock
Related to https://github.com/DataDog/datadog-ci/issues/1378
Differences with the old version:
- The algorithm was rewritten, and the order of results has changed
- A `dotRelative` option was added to keep `./`: https://github.com/isaacs/node-glob/issues/495
- The `silent` and `strict` options were removed:
> Any readdir errors are simply treated as "the directory could not be read", and it is treated as a normal file entry instead, like shells do. (see [changelog.md](https://github.com/isaacs/node-glob/blob/main/changelog.md#90))
> [dep] Bump glob to `11.0.0`

- package.json
- yarn.lock
Fixes https://github.com/DataDog/datadog-ci/security/dependabot/44
Bump the `fast-xml-parser` dependency.
> [dep] Bump fast-xml-parser to `4.4.1`

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/utils/public.ts
An [issue](https://github.com/DataDog/datadog-ci/issues/1159) was opened because the right scope to grant an App key wasn't clear.
This PR adds an hint when the App key is missing the `synthetics_default_settings_read` scope, when reading the max parallelisation. It also introduces the possibility to provide hints for other queries.
Add a line to the error message mentioning the hint from the failed query.
> [Synthetics] Hint the user on the missing scope in case of error

- package.json
- yarn.lock
Fixes the following deprecation warning:
```
npm warn deprecated google-p12-pem@4.0.1: Package is no longer maintained
```
Related to #1378 
Bump `google-auth-library`, which dropped its `google-p12-pem` dependency.
> [dep] Upgrade google-auth-library to `9.12.0`

- package.json
- src/commands/dsyms/__tests__/upload.test.ts
- src/commands/dsyms/__tests__/utils.test.ts
- src/commands/dsyms/upload.ts
- src/commands/elf-symbols/upload.ts
- src/commands/flutter-symbols/__tests__/upload.test.ts
- src/commands/flutter-symbols/upload.ts
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
- src/commands/sarif/__tests__/upload.test.ts
- src/commands/sarif/upload.ts
- src/commands/sourcemaps/upload.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/utils/public.ts
- src/commands/unity-symbols/upload.ts
- yarn.lock
This PR reverts #1381.
The functionality works fine on all versions of Node.js that we support, but glob@11 officially dropped support for Node.js versions below 20.
Revert the PR.
> Revert "[dep] Bump glob to `11.0.0` (#1381)"

- LICENSE-3rdparty.csv
- package.json
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/utils/internal.test.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/utils/internal.ts
- yarn.lock
`--override` keys are case sensitive, and a case typo leads to silent failure.
Example image, courtesy of @Drarig29 :
So we use Levenshtein distance to predict a corrective suggestion instead of failing silently.
⚠️ **This PR is large since we add `fast-levenshtein` npm package, which changed the yarn.lock significantly** ⚠️ 
- Use `fast-levenshtein` npm package for Levenshtein algo.
- Create an array of all possible `--override` keys to apply Levenshtein algo comparing user input to each key.
- If no valid key is found, calculate Levenshtein distance : distance > 5 ? Invalid key error with no suggestion, otherwise suggest a correction.
> [SYNTH-15356] Wrong case with `--override` fails silently

- src/commands/sarif/upload.ts
- src/commands/sbom/__tests__/payload.test.ts
- src/commands/sbom/upload.ts
- src/helpers/__tests__/tags.test.ts
- src/helpers/tags.ts
We want to provide the option for customer to disable CI tags. We have a custom who runs their pipeline from a centralize devops repo (call it repoA). Then, the job from this repo clone other repositories (for example, repoB) and analyze them.
However, when reporting the data, `datadog-ci` uses the environment variable from the CI runners. In this case, the results will appear from repoA whereas it should appear as repoB.
Add an option to disable ci tags.
> Add option to remove ci tags

- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/run-tests-command.ts
We are marking runName as deprecated and leaving comments for us to be able to clean it up easier later on when we release the new major version
Adding @depraceted and leaving some comments
> [SYNTH-12986] Mark runName as deprecated

- src/commands/sarif/README.md
- src/commands/sarif/upload.ts
- src/commands/sbom/README.md
- src/commands/sbom/upload.ts
We remove the `service` and `env` as mandatory arguments for the `sarif` and `abom` command. We put a default value. This default value will then be hidden from the user. It can used for graphs but not going to be surfaced in the product.
Put a default value in the argument
> remove service and env

- .github/workflows/ci.yml
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/utils/internal.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/batch.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/utils/internal.ts
- src/commands/synthetics/utils/public.ts
This PR fixes a bug where results without the complete information (server result from the polling endpoint) are reported as passed by default, even when the batch says the result failed.
Change the source of truth for `hasResultPassed()` to be the `ResultInBatch`, instead of the `ServerResult`.
> [SYNTH-15833] Use batch as source of truth for `hasResultPassed()`

- src/commands/sbom/renderer.ts
- src/commands/sbom/upload.ts
1. We should have only one path passed as parameter
2. We should show an error if we fail to generate the payload
Ensure we have only one path passed as parameter
Show an error and exit if we cannot generate the payload
> Show error message when payload is invalid

- src/commands/sbom/renderer.ts
- src/commands/sbom/upload.ts
Customer with no default branch have their upload rejected. They reach out support. We want to add a message that indicates how to troubleshoot so that the users can troubleshoot and fix the issue themselves.
When the default branch is not found, the server will return an error code 412. When we receive this error, we show then a message to invite the user to define a default branch.
> [STAL-2160] Show message when default branch not found

- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/compatibility.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/run-tests-lib.ts
Closes https://github.com/DataDog/datadog-ci/issues/1424
Currently, a warning log is shown even when the user uses the new property `batchTimeout` as expected.
Behavior after the fix:
```bash
$ yarn launch synthetics run-tests --batchTimeout 123
ERROR: No tests to run
```
```bash
$ yarn launch synthetics run-tests --batchTimeout 123 --pollingTimeout 456
The 'pollingTimeout' property is deprecated. Please use 'batchTimeout' instead.
If both 'pollingTimeout' and 'batchTimeout' properties exist, 'batchTimeout' is used!
ERROR: No tests to run
```
```bash
$ yarn launch synthetics run-tests --pollingTimeout 456
The 'pollingTimeout' property is deprecated. Please use 'batchTimeout' instead.
If both 'pollingTimeout' and 'batchTimeout' properties exist, 'batchTimeout' is used!
ERROR: No tests to …
```
> [SYNTH-15922] Fix warning log about `pollingTimeout`

- src/commands/synthetics/README.md
I tried to use `--override 'locations=["pl:test-corentin-preprod-e23cc6f215a2bd991b512080f81eb556"]'` but the backend didn't accept it:
> [p8z-bd4-y8z] Failed to trigger tests: query on [...]/trigger/ci returned: "The value provided for parameter 'locations' is invalid"
The right format is `--override locations="pl:test-corentin-preprod-e23cc6f215a2bd991b512080f81eb556"`
> [docs] Fix some instructions on test overrides

- src/commands/sarif/__tests__/fixtures/test_validation/rules-in-extensions.sarif
- src/commands/sarif/__tests__/validation.test.ts
- src/commands/sarif/validation.ts
We check that the SARIF file is valid to check that all rules are defined. We currently check in the tool section and not in the extensions. When processing a SARIF file that does have rules in extensions, it fails.
Detect rules in extensions
> check rule existence in extensions

- src/commands/deployment/__tests__/mark.test.ts
- src/commands/tag/tag.ts
This PR fixes the following error:
```bash
Type Error: The "path" argument must be of type string. Received an instance of Object
at validateString (node:internal/validators:162:11)
at Object.normalize (node:path:1131:5)
at readJsonFile (/Users/corentin.girard/go/src/github.com/DataDog/datadog-ci.git/master/src/helpers/tags.ts:240:25)
at parseTagsFile (/Users/corentin.girard/go/src/github.com/DataDog/datadog-ci.git/master/src/helpers/tags.ts:136:23)
at TagCommand.<anonymous> (/Users/corentin.girard/go/src/github.com/DataDog/datadog-ci.git/master/src/commands/tag/tag.ts:74:48)
at Generator.next (<anonymous>)
at /Users/corentin.girard/go/src/github.com/DataDog/datadog-ci.git/master/src/commands/tag/tag.ts:8:71
at new Promise (<anonymous>)
at Object.<anonymous>.__awaiter …
```
> [deployment] Fix error with `deployment mark`

- src/commands/synthetics/__tests__/batch.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/utils/internal.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/batch.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/utils/internal.ts
This PR fixes a bug where timed out retries were sometimes not reported.
Bug description:
- If a result (e.g. result ID 1) is an intermediate failed result (expected to be retried), its result ID is saved as reported,
- Now, if the retry times out, then the result ID is unchanged, resulting in datadog-ci thinking the result was already reported.
In a backend PR, we added the `max_retries` property.
If the result is `timed_out && retries < max_retries`, then we report it as a residual result.
This PR also fixes the JUnit reporter by not saving intermediate results in the JUnit file, and adds a few properties (`retries`, `max_retries`, `initial_result_id`) to results in the JUnit file.
> [SYNTH-15675] Report timed out retries

- yarn.lock
Closes https://github.com/DataDog/datadog-ci/security/dependabot/49
This package is used by 2 `devDependencies`: `aws-sdk-client-mock` and `dd-trace`.
Bump the dependency with `yarn resolution`
> [dep] Bump `path-to-regexp` to `6.3.0`

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
The context injection for Lambda in Step Function requires the Lambda function requires the Lambda definition to be like
```
"Lambda Invoke": {
...
...
"Payload.$": "$"
},
```
If the user has a custom `Payload.$` field, context injection will be skipped, but no error/warning message will be printed.
Print a warning message if context injection is skipped if:
1. `Parameters` field doesn't exist for the Lambda function, or
2. there's a custom `Payload.$` field
To make it transparent to users what won't work.
Print the messages
I wasn't able to test this because Parameters field is required when editing the State Machine from AWS Management Console. Should we remove this if-check?
Update: We are going to keep this if-check as @agocs suggested:
> This if statement prevents …
> Print warning if traces merging is skipped for Lambda in Step Function

- src/commands/lambda/flare.ts
- src/commands/lambda/functions/commons.ts
- src/commands/lambda/functions/instrument.ts
- src/commands/lambda/functions/uninstrument.ts
- src/commands/lambda/instrument.ts
- src/commands/lambda/loggroup.ts
- src/commands/lambda/prompt.ts
- src/commands/lambda/tags.ts
- src/commands/lambda/uninstrument.ts
- src/commands/stepfunctions/instrument.ts
- src/commands/stepfunctions/uninstrument.ts
Add explicit return type for most functions in
- `src/commands/lambda`
- `src/commands/stepfunctions` 
to make code more readable, improving developer experience.
The return type for some functions is complicated (>= 4 lines long), and I'm not adding explicit return type for them because I think it would make code verbose and less readable.
N/A
No new failure in `npm test`
> Add explicit function return type for Lambda and Step Function code

- src/commands/deployment/__tests__/correlate.test.ts
- src/commands/deployment/correlate.ts
- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/helpers/__tests__/fixtures.ts
We previously just showed the status code:
```
Failed to send deployment correlation data: Request failed with status code 400
```
But we want to show the error message so that the customers know what exactly is wrong
> [ci-visibility] Show error message on deployment correlate command

- src/commands/synthetics/__tests__/utils/__snapshots__/public.test.ts.snap
- src/commands/synthetics/run-tests-command.ts
This PR increases the datadog-ci limit for a batch from the arbitrary value of 100, to align it with the backend value of 1000.
> [SYNTH-16168] Increase batch limit to 1000

- LICENSE-3rdparty.csv
- package.json
- src/commands/lambda/__tests__/fixtures.ts
- yarn.lock
Yarn `resolutions` are for package consumers, so they should not be mentioning `devDependencies`.
- `@types/retry` is not used in the repo (we do not import from `retry`), so I removed it altogether
- `aws-sdk-client-mock` and `aws-sdk-client-mock-jest` are for unit tests
- I removed them from `resolutions`, and update the unit tests so they work with the latest versions of those 2 packages
- `kind-of` is not in the repo anymore
The only remaining one - `ini` - is an actual dependency.
Remove packages from `resolutions`.
> [chore] Clean yarn resolutions

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
Let's say Step Function A executes Step Function B. If B:
1. doesn't have a `Parameters` field, or
2. its `Parameters.Input` field is not a JSON object
3. its `Parameters.Input` field has a custom `CONTEXT.$` field
traces merging will be skipped, but no warning message will be printed.
Print a warning message in these cases to let users know what won't work.
I wasn't able to test this because `Parameters` field is required when editing the State Machine from AWS Management Console.
1. Change the Step Function execution step to be like:
```
"Step Functions StartExecution": {
"Type": "Task",
"Resource": "arn:aws:states:::states:startExecution",
"StateMachineArn": "...",
"Input": "Input!"
},
"End": true
}
```
2. Run `datadog-ci stepfunctions instrument` command
A warning …
> Print warning if traces merging from xfn to xfn is skipped

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
If a Lambda function in a State Machine has a custom `Payload` defined using `"Payload": ...`, e.g.,
```
"Lambda Invoke": {
"Type": "Task",
"Resource": "arn:aws:states:::lambda:invoke",
"OutputPath": "$.Payload",
"FunctionName": "...",
"Payload": {
"action": "service/delete_customer"
}
},
...
}
}
```
then context injection for the Step Function will fail with the error:
> [Error] Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Cannot have both the field 'Payload.$' and the field 'Payload' at the same time at /States/Lambda Invoke/Parameters'. Failed to inject context into lambda functions' payload of arn:aws:states:sa-east-1:425362996713:stateMachine:YimingTestExpressStateMachine2
This is because our instrumentation code will add a field `"Payload.$": ...`, …
> Skip xfn->Lambda context injection if custom Payload is used without $

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
If a Lambda function in a State Machine has a custom `Payload` defined using `"Payload": ...`, e.g.,
```
"Step Functions StartExecution": {
"Type": "Task",
"Resource": "arn:aws:states:::states:startExecution",
"StateMachineArn": "xxx",
"Input": {
"CONTEXT": "Context!"
}
},
"End": true
}
```
then context injection for the Step Function will fail with the error:
> [Error] Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Cannot have both the field 'CONTEXT.$' and the field 'CONTEXT' at the same time at /States/Step Functions StartExecution/Parameters'. Failed to inject context into lambda functions' payload of arn:aws:states:sa-east-1:425362996713:stateMachine:YimingTestExpressStateMachine2 
This is because our instrumentation code will add a field `"CONTEXT.$": …
> Skip xfn->xfn context injection if custom Payload is used without $

- src/commands/stepfunctions/helpers.ts
https://github.com/DataDog/datadog-ci/pull/1443 and https://github.com/DataDog/datadog-ci/pull/1447 introduce a bug that when context injection is already set up for a Lambda or a Step Function in a Step Function, a warning will be printed, saying context injection won't work, which is wrong:
If context injection is already set up, i.e.
- a Lambda has `"Payload.$": "States.JsonMerge($$, $, false)"`
- a Step Function has `"CONTEXT.$": "States.JsonMerge($$, $, false)"`
then print a better error message:
> Context injection is already set up. Skipping context injection.
Run `datadog-ci stepfunctions instrument` command twice. The second time, these messages were printed:
> fix: print a better message if Step Function context injection is already set up

- src/commands/stepfunctions/helpers.ts
A Step Function can have multiple steps. Some steps may execute Lambda functions. Some steps may execute other Step Functions. When instrumenting a Step Function, we want to inject necessary context into both Lambda functions and child Step Functions.
If the last step doesn't need to be updated, e.g. if it's neither a Lambda function nor a Step Function, then context injection will be skipped. This is because the flag `definitionHasBeenUpdated` isn't updated properly.
Fix the usage of the flag so that if any part of definition is updated, this flag will be true.
1. Create a State Machine where
- the Lambda step is not instrumented
- the last step doesn't need to be updated
2. Instrument the Step Function by running `datadog-ci stepfunctions instrument`
Before:
- `definitionHasBeenUpdated` …
> fix: xfn context injection skipped if no update on last step

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
Currently the `injectContextForLambdaFunctions()` function roughly looks like this:
```
const injectContextForLambdaFunctions = (...): boolean => {
if (shouldUpdateStepForTracesMerging()) {
addTraceContextToLambdaParameters()
return true
}
return false
}
```
It calls `shouldUpdateStepForTracesMerging()`.
This PR merges the two functions by moving the code of `shouldUpdateStepForTracesMerging()` into `injectContextForLambdaFunctions()`.
We will soon have different instrumentation strategies depending on the existing state of Lambda definition, so `shouldUpdateStepForTracesMerging()` which has a boolean return value will no longer work.
Design doc: [Fixing Step Function Instrumentation](https://docs.google.com/document/d/18YpNVN6reCjA-dq6U1Tfs2MyLxcVnjO_N8Uy9Gm_BGM/edit#bookmark=id.pczh1xpu3 …
> Refactor xfn Lambda injection code my merging two functions

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
In Step Machine definition, if a Lambda function doesn't have `Payload` field, right now we are injecting context using
```
"Payload.$": "States.JsonMerge($$, $, false)"
```
This PR changes it to:
```
"Payload.$": "$$['Execution', 'State']"
```
which passes less information.
This is case #1 in this design doc: [Fixing Step Function Instrumentation](https://docs.google.com/document/d/18YpNVN6reCjA-dq6U1Tfs2MyLxcVnjO_N8Uy9Gm_BGM/edit)
Pass the touched tests
1. Make the Lambda Execution step have no `Payload` field
2. Build the package: `yarn prepack`
3. Instrument the Step Function using `./dist/cli.js stepfunctions instrument`
4. Execute the State Machine
1. `"Payload.$": "$$['Execution', 'State']"` was added to Lambda definition
2. TODO: question to reviewers: What product should we check …
> Inject context for xfn->Lambda when no Payload exists (case 1)

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
In a State Machine, if a Lambda execution step's `Payload` field is not a JSON object, e.g.
```
"Lambda Invoke": {
"Type": "Task",
"Resource": "arn:aws:states:::lambda:invoke",
"OutputPath": "$.Payload",
"FunctionName": "arn:aws:lambda:sa-east-1:425362996713:function:yimingPlayground",
"Payload": "Just a string!"
},
"Next": "Step Functions StartExecution"
},
```
then print a warning and skip context injection.
This is case # 3 in this design doc: [Fixing Step Function Instrumentation](https://docs.google.com/document/d/18YpNVN6reCjA-dq6U1Tfs2MyLxcVnjO_N8Uy9Gm_BGM/edit)
To inject context into Lambda payload, the payload must be a JSON dictionary. Injection can't work if payload is a string.
Passed the added test and existing tests
1. Change the Lambda Execution step to have …
> Skip xfn->Lambda context injection of Payload is not object (case 3)

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
This PR handles Step Function context injection into Lambda when `Payload` (not `Payload.$`) is used in the Lambda execution step.
This is case # 2 in this design doc: [Fixing Step Function Instrumentation](https://docs.google.com/document/d/18YpNVN6reCjA-dq6U1Tfs2MyLxcVnjO_N8Uy9Gm_BGM/edit)
Sub-cases:
```
"Lambda Invoke": {
"Payload": {
"Execution.$": "$$.Execution",
"State.$": "$$.State"
},
},
},
```
Then just print a message.
If the payload already has any of `Execution.$`, `Execution`, `State.$` or `State`, e.g.
```
"Lambda Invoke": {
"Payload": {
"State": {
"Name": 'Lambda Invoke'
}
},
},
},
```
and it's not case 2.1, then print a warning and skip context injection
i.e. it's not Case 2.1 or 2.2, e.g.
```
"Lambda Invoke": {
"Payload": { …
```
> Handle sfn->Lambda context injection when Payload is used without $ (case 2)

- README.md
No instability issues for years. 
Remove beta notice. 
~~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~~ (does not apply)
> Remove beta flag from standalone binary 

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
Currently the `injectContextForStepFunctions()` function roughly looks like this:
```
const injectContextForStepFunctions = (...): boolean => {
if (shouldUpdateStepForStepFunctionContextInjection()) {
addTraceContextToStepFunctionParameters()
return true
}
return false
}
```
It calls `shouldUpdateStepForStepFunctionContextInjection()`.
This PR
1. merges the two functions by moving the code of `shouldUpdateStepForStepFunctionContextInjection()` into `injectContextForStepFunctions()`.
2. makes the tests for `shouldUpdateStepForStepFunctionContextInjection()` test `injectContextForStepFunctions()` instead
We will soon have different instrumentation strategies depending on the existing state of Lambda definition, so `shouldUpdateStepForStepFunctionContextInjection()` which has a boolean …
> Refactor sfn->sfn context injection code by merging two functions

- src/commands/stepfunctions/helpers.ts
Merge `addTraceContextToStepFunctionParameters()` into its callsites, and removing the extra `if` checks.
Depending on the original state `Input`, we will have different instrumentation strategies, so a single `addTraceContextToStepFunctionParameters()` will no longer work.
Run `npm test` to pass existing tests
> Refactor sfn->sfn context injection code by merging two functions (2)

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
Skip the context injection in Step Function execution step if the `CONTEXT` field exists and it's not an object.
This is case # 2 in this design doc: [Fixing Step Function Instrumentation](https://docs.google.com/document/d/18YpNVN6reCjA-dq6U1Tfs2MyLxcVnjO_N8Uy9Gm_BGM/edit)
> Support sfn->sfn context injection case 3

- src/commands/stepfunctions/__tests__/helpers.test.ts
- src/commands/stepfunctions/helpers.ts
Revamps Step Function -> Step Function context injection:
1. Change `States.JsonMerge($$, $, false)` to `$$['Execution', 'State', 'StateMachine']`, so the unnecessary `Task` won't be passed
2. Revamp the case numbers. Currently the case numbers (1, 2.1, 2.2, 2.3, 3, 4.1, 4.2, 4.3) are in sync with the case numbers for SFN->Lambda context injection. However the cases for SFN->SFN is simpler because we are using a custom field name `CONTEXT`, which users are unlikely to use, so we can just not handle the rare case the `CONTEXT` field is set.
3. Add test cases
4. Add doc
Design doc: [Fixing Step Function Instrumentation](https://docs.google.com/document/d/18YpNVN6reCjA-dq6U1Tfs2MyLxcVnjO_N8Uy9Gm_BGM/edit#bookmark=id.15flqi5dkv9i)
Passed existing and new tests.
> Revamp SFN->SFN context injection

- src/helpers/tags.ts
We use an author email to implement billing and thus it should be a required field.
Adds the git author email tag to the mandatory fields object.
> [STAL-2949] Make git author a mandatory field

- src/commands/deployment/README.md
- src/commands/deployment/__tests__/correlate.test.ts
- src/commands/deployment/correlate.ts
The `correlate` command tries to automatically get the affected commit SHAs ([docs](https://docs.datadoghq.com/continuous_delivery/deployments/argocd#correlate-deployments-with-ci-pipelines)). However, in some setups such as generating a PR and merging it from the CI, the command is not able to properly make the correlation.
This PR adds an option to the correlate command so that customers can manually select which git commit SHAs should be correlated. 
Adding an array option to the command.
> Add option to pass config shas manually on `correlate` command

- src/commands/sarif/renderer.ts
- src/commands/sarif/upload.ts
- src/commands/sbom/renderer.ts
- src/commands/sbom/upload.ts
- src/helpers/tags.ts
We should NOT upload SARIF results when a required git tag is absent. We've extended the list of fields to be more accurate with our current product.
When a git tag is missing we don't specify which one is required, so we now keep track and list them out so they are visible to users.
Removed my committer email from getting sent and ran the commands.
> [STAL-3155] Specify which git tags are missing

- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/test.ts
- src/commands/synthetics/utils/internal.ts
- src/commands/synthetics/utils/public.ts
This PR adds support for loading LTDs and sending them to the trigger endpoint.
- Add `localTestDefinition` to `.synthetics.json` files
> [SYNTH-16911] Trigger batch with LTDs

- LICENSE-3rdparty.csv
- package.json
- src/commands/sbom/__tests__/fixtures/sbom-invalid-purl.json
- src/commands/sbom/__tests__/validation.test.ts
- src/commands/sbom/upload.ts
- src/commands/sbom/validation.ts
- yarn.lock
We want to prevent customer from uploading invalid requests (for example, with invalid `purl`).
Filter the data and prevent uploading payload with invalid package url.
Added one unit test.
Running locally
```
$ yarn launch sbom upload ./src/commands/sbom/__tests__/fixtures/sbom-invalid-purl.json             
invalid purl invalid purl: Invalid purl: missing required "pkg" scheme component
❌ Invalid SBOM report file [./src/commands/sbom/__tests__/fixtures/sbom-invalid-purl.json].
The report is not a valid SBOM or is not compliant with our json schema.
```
> [K9VULN-1175] Validate purl

- src/commands/sbom/__tests__/validation.test.ts
- src/commands/sbom/payload.ts
- src/commands/sbom/renderer.ts
- src/commands/sbom/upload.ts
- src/commands/sbom/validation.ts
Clients are sending us package names for Python with invalid characters. We want to start filtering these names. They are filtered in the API.
Warn the user about invalid package names for Python. This is not removing for the payload as this is done by the API. It warns the user about a malformed payload.
Added units tests
Tried locally with a SBOM and a library containing the name `cloud picke` (with a space).
> [K9VULN-2465] Add validation of package names

- src/commands/sbom/__tests__/fixtures/sbom.1.5.ok.json
- src/commands/sbom/__tests__/payload.test.ts
- src/commands/sbom/constants.ts
- src/commands/sbom/payload.ts
- src/commands/sbom/types.ts
Support the `is-dev` property from `osv-scanner` by propagating it when it's present.
> [K9VULN-2266] Support `is-dev` property from `osv-scanner`

- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/test.ts
- src/commands/synthetics/utils/internal.ts
- src/commands/synthetics/utils/public.ts
Fixes the case of the variable containing the local test definition. Before it was in Camel Case but it should have been in snake case.
Note: There are still some instances of the Camel Case version, but it is only for variables defined in typescript as it is required by the linter.
- Change `localTestDefinition` to `local_test_definition`
> [SYNTH-17698] Fix local test definition variable case

- src/commands/sbom/__tests__/validation.test.ts
[This merge commit](https://github.com/DataDog/datadog-ci/commit/9f2b4f1158e6bb60b802fddafbc6f1803dd315ac) shows that we're failing to build the package. This PR adds the `is_dev` value to these new tests, so that they pass.
> [K9VULN] Specify `is_dev` in tests

- .github/CODEOWNERS
Changing from Serverless team to serverless-onboarding-enablement subteam
Serverless team is too large, and people may not look at PRs. Changing to ONE team, which is a better owner. Also, team members will be added as a reviewer in a Round Robin way.
> Change Serverless team in CODEOWNERS

- .github/CODEOWNERS
The `sbom` command should be owned by the `k9-vm-sca` team while the `sarif` command should be owned by the `k9-vm-ast` team.
Updating permissions accordingly.
> Update code ownership

- src/commands/sarif/README.md
- src/commands/sarif/__tests__/upload.test.ts
- src/commands/sarif/api.ts
- src/commands/sarif/interfaces.ts
- src/commands/sarif/renderer.ts
- src/commands/sarif/upload.ts
- src/commands/sbom/README.md
- src/commands/sbom/upload.ts
We want to deprecate the `--service` flag as this is no longer used and service is being mapped based on the repo and service mapping.
1. We deprecate the flag for now instead or removing it completely to avoid customers failure
2. We will transition GitHub actions and remove it from GitHub actions
3. Around April 2025, we will completely remove the flag. It should give customers enough time to transition by then and our GitHub actions will be updated.
> [K9VULN-3031] remove service flag

- src/commands/synthetics/__tests__/multilocator.test.ts
- src/commands/synthetics/errors.ts
- src/commands/synthetics/import-tests-lib.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/multilocator.ts
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/utils/internal.ts
- src/commands/synthetics/utils/public.ts
This PR implements Multilocator updates in local test definitions. 
We parse the Multilocator from the poll_results response, prompt the user asking if he wants to update his local test definitions with the new Multilocator and then save the changes in the selected file with `-f` (only works with 1 file, just like the `import-test` function )
> [SYNTH-18215] Save multilocator in ltd

- .github/CODEOWNERS
This PR updates the `CODEOWNERS` file to reflect the `metric` folder being renamed to `measure` in https://github.com/DataDog/datadog-ci/pull/1205.
I also alphabetically ordered other lines.
> [chores] Replace `metric` by `measure` in codeowners

- src/commands/sourcemaps/README.md
- src/commands/sourcemaps/upload.ts
Adds a quiet option to sourcemap uploads
Adds a --quiet flag.
> Add quiet option to sourcemap upload

- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
Add the missing unit test cases for `resourceUrlSubstitutionRegexes`.
> add missing unit tests for resourceUrlSubstitutionRegexes

- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/deploy-tests-config-with-all-keys.json
- src/commands/synthetics/__tests__/deploy-tests-lib.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/cli.ts
- src/commands/synthetics/deploy-tests-command.ts
- src/commands/synthetics/deploy-tests-lib.ts
- src/commands/synthetics/import-tests-lib.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/local-test-definition.ts
- src/commands/synthetics/multilocator.ts
- src/commands/synthetics/test.ts
This PR adds a command to deploy LTDs as main tests. For now, it only supports deploying the LTDs from a single test file.
It also focuses on API tests only. Browser tests will be supported later.
To deploy all LTDs inside the given file:
```bash
yarn launch synthetics deploy-tests -f path/to/single-test-file.synthetics.json
```
To deploy some LTDs inside the given file:
```bash
yarn launch synthetics deploy-tests -f path/to/single-test-file.synthetics.json -p 123-456-789
```
> [SYNTH-17719] Command to deploy LTDs

- src/commands/synthetics/README.md
Adding documentation in the README about the `resourceUrlSubsitionRegexes`.
> [synthetics] add README.md documentation for resourceUrlSubstitutionRegexes

- src/commands/synthetics/README.md
This PR changes the examples for the substitutions in the documentation to use the simpler pipe (`|`) format, as the sed one (`s/regex/rewrite rule/`) would be more complex due to escaping the URLs slash, hence too confusing.
> use simpler substitution format

- src/__tests__/cli.test.ts
- src/commands/coverage/upload.ts
The PR to add this command (#1520) was old and didn't include the FIPS options added in #1501.
Add `--fips` and `--fips-ignore-error` to `datadog-ci coverage upload` command.
> Add fips options to code coverage command

- .github/CODEOWNERS
- .github/advanced-issue-labeler.yml
- README.md
- src/commands/coverage/README.md
This PR adds the `ci-app-libraries` team as codeowners for the `coverage` command, updates the issue labeler and add missing documentation in the beta section of the main readme.
Update meta files
> [chores] Update codeowners, docs, issue labeler

- src/commands/synthetics/README.md
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
- src/commands/synthetics/__tests__/config-fixtures/config-with-global-polling-timeout.json
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/run-tests-lib.test.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/batch.ts
- src/commands/synthetics/compatibility.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/run-tests-lib.ts
- src/commands/synthetics/test.ts
- src/commands/synthetics/utils/internal.ts
- src/commands/synthetics/utils/public.ts
- https://github.com/DataDog/datadog-ci/pull/1542
- https://github.com/DataDog/datadog-ci/pull/1543
- https://github.com/DataDog/datadog-ci/pull/1544 (← **you are here**)
- https://github.com/DataDog/datadog-ci/pull/1545
- https://github.com/DataDog/datadog-ci/pull/1546
- https://github.com/DataDog/datadog-ci/pull/1548
> [!NOTE]  
> This PR was created to prepare for the **next major release of datadog-ci**: `v3.0.0`
> A migration guide ([like such](https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md)) will be created in a follow-up PR.
This PR removes 4 deprecated CLI parameters:
- `--pollingTimeout`
- `--locations`
- `--variable`
- `--deviceIds`
Remove the CLI parameters.
> [SYNTH-12989] Remove deprecated CLI parameters

- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/utils/public.ts
The `failing to get org settings is not important enough to throw` unit test wasn't mocked properly, so the `/synthetics/settings` call was failing and retrying 3 times.
This was very noticeable in the train with slow internet 😅 
Fix mocks in unit tests
> [ci] Fix slow `getSyntheticsOrgSettings` unit test

- .github/workflows/ci.yml
- .github/workflows/publish-prerelease.yml
- .github/workflows/publish-release.yml
- package.json
This PR drops support for Node 14 and 16. It's a noop in terms of code, but will unblock other issues.
Update `package.json`, and stop testing on Node 14 and 16.
> Drop support for Node 14 and 16

- src/commands/synthetics/run-tests-command.ts
- https://github.com/DataDog/datadog-ci/pull/1542
- https://github.com/DataDog/datadog-ci/pull/1543
- https://github.com/DataDog/datadog-ci/pull/1544
- https://github.com/DataDog/datadog-ci/pull/1545
- https://github.com/DataDog/datadog-ci/pull/1546
- https://github.com/DataDog/datadog-ci/pull/1548 (← **you are here**)
> [!NOTE]  
> This PR was created to prepare for the **next major release of datadog-ci**: `v3.0.0`
> A migration guide ([like such](https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md)) will be created in a follow-up PR.
This PR removes the backwards compatibility for `"files"` being a glob string in the global configuration file. It now needs to be an array of strings.
Remove backwards compatibility and deprecation log.
> [SYNTH-12989] Remove deprecated `files` usage

- package.json
- src/commands/coverage/__tests__/upload.test.ts
- src/commands/coverage/upload.ts
- src/commands/dsyms/__tests__/upload.test.ts
- src/commands/dsyms/__tests__/utils.test.ts
- src/commands/dsyms/upload.ts
- src/commands/elf-symbols/upload.ts
- src/commands/flutter-symbols/__tests__/upload.test.ts
- src/commands/flutter-symbols/upload.ts
- src/commands/junit/__tests__/upload.test.ts
- src/commands/junit/upload.ts
- src/commands/sarif/__tests__/upload.test.ts
- src/commands/sarif/upload.ts
- src/commands/sourcemaps/upload.ts
- src/commands/synthetics/__tests__/utils/public.test.ts
- src/commands/synthetics/utils/public.ts
- src/commands/unity-symbols/upload.ts
- yarn.lock
> [!NOTE]  
> This PR is based on https://github.com/DataDog/datadog-ci/pull/1381, which had to be reverted (https://github.com/DataDog/datadog-ci/pull/1398) because it was bumping `glob` to its latest version (`11.0.0`), which has dropped support for Node 18: https://github.com/isaacs/node-glob/blob/main/changelog.md#110
Related to https://github.com/DataDog/datadog-ci/issues/1378
This PR bumps `glob` to the latest version **that still supports Node 18** (our new minimal version as per #1554).
Differences with the old version:
- The algorithm was rewritten, and the order of results has changed
- A `dotRelative` option was added to keep `./`: https://github.com/isaacs/node-glob/issues/495
- The `silent` and `strict` options were removed:
> Any readdir errors are simply treated as "the …
> [dep] Bump glob to `10.4.5`

- package.json
- yarn.lock
This PR bumps `dd-trace` to the latest version. This is a dev dependency only used in CI.
Bump it now that we dropped support for Node.js < 18
> [ci] Bump dd-trace to `5.38.0`

- src/commands/synthetics/run-tests-lib.ts
This PR fixes an [issue](https://github.com/DataDog/datadog-ci/issues/1565) where pipelines hang indefinetly because of a new prompt.
Only prompt ML update if local test definitions are present in the payload.
> [SYNTH-18686] Hotfix: only prompt ml updates if config contains ltds

- src/commands/sarif/renderer.ts
- src/commands/sarif/validation.ts
We want to prevent large SARIF files from being uploaded. This leads to operational issues.
Add a check in the validation and do an early exit if validation fails.
Tested by setting the max size to 1. There is the output below.
> [K9VULN-3897] Filter large SARIF files

- src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/constants.ts
Adds support for `ruby3.3` and `provided.al2023` runtimes.
Adding them to the lookup keys.
> [lambda] support `ruby3.3` and `provided.al2023`

- src/commands/lambda/__tests__/functions/instrument.part2.test.ts
- src/commands/lambda/constants.ts
In https://github.com/DataDog/datadog-ci/pull/1537, we added support for instrumenting Python3.13 lambdas using `datadog-ci lambda instrument` command. In that PR, we missed adding `python3.13` constant to the `ARM_LAYERS` array, which causes the command to apply non-ARM Python layers to ARM Python 3.13 lambdas.
This PR adds the constant and a unit test that catches the issue.
- Ran yarn prepack to build CLI locally
- Created a Python 3.13 ARM lambda
- Ran node `./dist/cli.js lambda instrument --function MY_FUNCTION_ARN --extensionVersion 68 --layer-version 105` 
- Saw it successfully instrument with the `arn:aws:lambda:ca-central-1:464622532012:layer:Datadog-Python313-ARM:105` layer
> [lambda] [bugfix] Ensure ARM layers are used for python3.13 ARM functions

- src/commands/synthetics/__tests__/multilocator.test.ts
- src/commands/synthetics/multilocator.ts
- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
- src/helpers/prompt.ts
Currently, running an LTD can result in pipelines stuck on hold waiting for a prompt from the user, when a ML update is detected. We want to skip this step if we detect that the `run-tests` command was used in a CI environment.
Only prompt the user for ml updates if in interactive mode.
- Add a new `isInteractive` function
- Reuse preexisting `requestConfirmation` function and improve its typing
> [SYNTH-18694] Do not prompt ML update confirmation in CI environments

- package.json
- yarn.lock
Keep up with latest bug fixes and features: https://github.com/DataDog/dd-trace-js/releases/tag/v5.42.0. Specifically relevant: https://github.com/DataDog/dd-trace-js/pull/5390
`yarn up dd-trace`
N/A, just check that current tests pass
> Bump `dd-trace` to `^5.42.0`

- src/commands/sarif/README.md
- src/commands/sarif/__tests__/fixtures/gitconfig
- src/commands/sarif/__tests__/upload.test.ts
- src/commands/sarif/renderer.ts
- src/commands/sarif/upload.ts
- src/commands/sbom/README.md
- src/commands/sbom/__tests__/fixtures/gitconfig
- src/commands/sbom/__tests__/payload.test.ts
- src/commands/sbom/__tests__/validation.test.ts
- src/commands/sbom/upload.ts
- src/helpers/__tests__/tags.test.ts
- src/helpers/git/format-git-span-data.ts
- src/helpers/tags.ts
Adding `--git-repository` option support to `datadog-ci sbom upload` and `datadog-ci sarif upload`.
We have users complaining about **CI** integration of `datadog-ci` to generate SBOM for repository which do not report the correct git information. 
Currently, it is not clear how the `datadog-ci sbom upload` command gets Git context. It currently does:
1. Current process location
2. CI environment variables (can be disabled with: `--no-ci-tags` option)
3. Override environment variables (`DD_GIT_*` variables)
Currently users have two options to have the correct Git values when running the `upload` command from CI:
1. disable ci automatic detection of env vars with`--no-ci-tags`
2. use override `DD_` variables.
The current workaround is to override `DD_` variables
```typescript
export …
```
> [K9VULN-3872] Add --git-repository option to sbom/sarif upload

- src/commands/synthetics/__tests__/build-and-test.test.ts
- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
- src/commands/synthetics/build-and-test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/utils/internal.ts
This PR implements the `synthetics build-and-test` command.
Provided with a `buildCommand`, and an optional `buildPluginPort` (defaults to 4000) options, this command runs the build command, wait for a successful build, and a dev server spawned by the [Datadog build-plugin](https://github.com/DataDog/build-plugins/pull/153), to run Synthetics tests against this dev server using the tunnel.
Except the unit tests, this command hasn't been tested properly yet. It'll be done later.
The `build-and-test` command spawns the build command, and regularly request the expected dev server (e.g. `https://localhost:4000`) until the build is advertised as successful. Then it runs the tests.
> implement the build-and-test command

- src/commands/react-native/__tests__/codepush.test.ts
- src/commands/react-native/__tests__/fixtures/codepush-deployment-history/valid-deployment-with-invalid-version.txt
- src/commands/react-native/__tests__/fixtures/codepush-deployment-history/valid-deployment-with-prefix-symbols.txt
- src/commands/react-native/__tests__/utils.test.ts
- src/commands/react-native/codepush.ts
- src/commands/react-native/utils.ts
Introduces an extra step to sanitize the release version extracted from codepush deployments history.
In some cases, the version might have a prefix:
```
[
"v7",
"Sep 05, 02:27 PM",
">=2.0",                             <---- see here
"No",
null,
"\u001b[35mNo installs recorded\u001b[39m"
]
```
This PR removes extra leading symbols from the version, and validates it before proceeding with the upload.
> [RN CODEPUSH] Sanitize Upload Release Version

- src/helpers/__tests__/flare.test.ts
- src/helpers/flare.ts
According to @SiddhithaBhoopathy , a few customers failed to send Lambda Flare due to potential API key error:
- https://datadog.zendesk.com/agent/tickets/2076284
- https://datadog.zendesk.com/agent/tickets/2077466
- https://datadoghq.atlassian.net/browse/SLES-1893
The current error message customers get is like:
> [Error] Failed to send flare file to Datadog Support: Request failed with status code 400. request does not match with Datadog or Zendesk information: VER_000
Is your Datadog API key correct?
where no clear action item is available, so the customer reached back to support engineers for help.
Adds a doc link in the error message, and suggests the customer to follow it to set API key.
> chore: Improve error message for flare file upload

- src/commands/synthetics/__tests__/build-and-test.test.ts
- src/commands/synthetics/build-and-test.ts
- src/commands/synthetics/run-tests-command.ts
- src/commands/synthetics/utils/internal.ts
The build command can trigger several build and neither `datadog-ci` nor the build-plugins have any control or insight over the number of builds triggered. These builds could be run in parallel or in sequence, and the only way to detect that all builds finished is when the build command exited successfully. (we'll handle the case when the build command exit with an error later, in [SYNTH-19418](https://datadoghq.atlassian.net/browse/SYNTH-19418)).
This PR redesign the `build-and-test` command to host the dev server in `datadog-ci` rather than in the build-plugin.
The build plugins will report the completed builds to the dev server through the `/_datadog-ci_/build` endpoint.
The unit tests for the static serving of the dev server will be implemented later in …
> [Synthetics] Redesign build-and-test command to spawn the dev server

- src/cli.ts
Removes the requirement to set `DD_BETA_COMMANDS_ENABLED=1` end var when doing code coverage upload.
Removes code coverage upload command from the list of beta commands.
> Make code coverage upload command non-beta

- src/commands/synthetics/__tests__/batch.test.ts
- src/commands/synthetics/batch.ts
Need to deal with some smoke test triggers with the following error:
```
SMOKE TEST ERROR: The batch didn't timeout after the expected timeout period
```
The safety limit margin was set to 15s which is a bit to short of a margin, as any lag > 15s between the batch reducer and datadog-ci can cause this error.
Thus, went from 15s to 60s by having `12*POLLING_INTERVAL` instead of `3*`
> [SYNTH-19349] bump the batch timeout safety margin to 60s

- src/commands/synthetics/__tests__/api.test.ts
- src/commands/synthetics/__tests__/batch.test.ts
- src/commands/synthetics/__tests__/deploy-tests-lib.test.ts
- src/commands/synthetics/__tests__/fixtures.ts
- src/commands/synthetics/__tests__/multilocator.test.ts
- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/__tests__/reporters/junit.test.ts
- src/commands/synthetics/__tests__/test.test.ts
- src/commands/synthetics/api.ts
- src/commands/synthetics/batch.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/multilocator.ts
- src/commands/synthetics/reporters/default.ts
- src/commands/synthetics/reporters/junit.ts
- src/commands/synthetics/utils/internal.ts
- src/commands/synthetics/utils/public.ts
This PR updates the Synthetics component to use the new v2 `poll_result` endpoint that sends v1 results.
- Refactored the API configuration to use separate `baseV1Url` and `baseV2Url` instead of a single `baseUrl`
- Added `RawPollResult` interface to handle the new nested JSON structure
- Updated `pollResults` to properly extract test result and data from the api response
- Updated test fixtures to match the new V2 API response format with proper test relationships
- Fixed all tests to match the new result format and relationship structure
> [SYNTH-18941] Use v1 results

- package.json
- src/commands/synthetics/__tests__/utils/public.test.ts
Upgrading rimraf in #1560 made us stop removing `__tests__` folders before publishing to NPM, accidentally undoing #785.
Use the new `--glob` option as it's now opt-in in recent versions of `rimraf`.
> [chores] Fix `rimraf` not removing test files

- src/commands/synthetics/README.md
I forgot to update the section for the upload-application command.
And this PR also adds partial comments, like in https://github.com/DataDog/synthetics-ci-github-action/pull/323. Here is [the result](https://docs-staging.datadoghq.com/corentin.girard/preview-datadog-ci/continuous_testing/cicd_integrations/configuration?tab=npm&site=us5#datadogsite):
Use `<-- partial` comments.
> [docs] Update synthetics upload section + add partial comments

- src/commands/gate/renderer.ts
This PR escapes the details URL in our Quality Gates response. Without this URL escape, the URL leads to a 404.
Simply adds a `URLEncode` to the `details_url` string in the rendering of the quality gate.
Current tests cover changes
> Escape Details URL in Quality Gates Response

- src/commands/coverage/README.md
- src/commands/coverage/api.ts
- src/commands/coverage/interfaces.ts
- src/commands/coverage/upload.ts
- src/commands/git-metadata/__tests__/fixtures/add_delete.diff
- src/commands/git-metadata/__tests__/fixtures/modify_single_file.diff
- src/commands/git-metadata/__tests__/git.test.ts
- src/commands/git-metadata/git.ts
- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
- src/helpers/interfaces.ts
- src/helpers/tags.ts
- src/helpers/utils.ts
Updates `coverage upload` command to include git diff data for current commit and current PR (if detected).
Git diff data is obtained using `simpleGit` and is attached to the uploaded events.
> Update coverage upload command to include git diff data

- src/commands/synthetics/__tests__/cli.test.ts
- src/commands/synthetics/upload-application-command.ts
This PR adds back the version UUID in the output, so that it can be [extracted from the logs](https://github.com/DataDog/synthetics-test-automation-bitrise-step-upload-application/blob/2eacc2b79ad4aeb5166d3d9a1e75a1fc6b6d4104/upload-application.sh#L52) in the https://github.com/DataDog/synthetics-test-automation-bitrise-step-upload-application CI integration.
The log was removed in a previous PR, so we are reintroducing it (slightly rephrased with a hint on how to use that version ID/UUID). See https://github.com/DataDog/datadog-ci/pull/1240#discussion_r2100010499.
Without this log, the Bitrise upload-application step won't be able to produce its expected `DATADOG_UPLOADED_APPLICATION_VERSION_ID` output.
> [synthetics] Fix output of mobile app upload command

- src/commands/sbom/README.md
- src/commands/sbom/renderer.ts
When Datadog is unable to determine or infer a default branch for a repository, we should make it as simple as possible (these are often users that are onboarding) to address the issue.
> [K9VULN-4956] Update text when unable to infer default branch

- src/commands/coverage/api.ts
- src/commands/coverage/interfaces.ts
- src/commands/coverage/upload.ts
- src/commands/git-metadata/__tests__/git.test.ts
- src/commands/git-metadata/git.ts
Updates the format of git diff data uploaded together with code coverage data.
Apart from the list of files with their added/removed lines, the updated diff contains the SHAs of the head and base commits used to calculate the diff.
> Add base and head SHAs to git diff data uploaded with coverage

- src/helpers/__tests__/ci.test.ts
- src/helpers/ci.ts
- src/helpers/interfaces.ts
- src/helpers/tags.ts
Replaces `pr.id` tag with `pr.number` tag in uploaded code coverage events, because the tag really contains the PR number, and not the ID (they are two different things)
> Rename PR ID tag to PR number

- src/commands/coverage/README.md
- src/commands/coverage/__tests__/upload.test.ts
- src/commands/coverage/renderer.ts
- src/commands/coverage/upload.ts
Adds git metadata upload to `coverage upload` command.
Coverage upload needs git metadata for the following reasons:
- backend needs commit data in gitdb, and if the user has not enabled Datadog GitHub integration, then the data needs to be uploaded from a library
- calculating and uploading git diffs as part of coverage upload needs repo unshallowing, and git metadata upload does this
> Upload git metadata when uploading coverage

- src/commands/synthetics/__tests__/reporters/mobile/app-upload.test.ts
- tsconfig.json
- yarn.lock
This PR changes the `moduleResolution` to be `node16` to unblock https://github.com/DataDog/datadog-ci/pull/1665#discussion_r2138381593.
Just change `moduleResolution` and `baseUrl`. All other options are kept as is to avoid any breaking changes.
> Use `moduleResolution: node16` and remove `baseUrl`

- src/commands/sbom/__tests__/fixtures/sbom-with-reachability.json
- src/commands/sbom/__tests__/payload.test.ts
- src/commands/sbom/payload.ts
This adds a check before iterating over a field (`vulnerabilities[].affects[]`) that may be omitted.
In our tests, we only include an affected vulnerability (reachable), so this situation went unnoticed. 
I've updated the test case to include both (un)reachable vulnerabilities.
> [K9VULN-5794] Guard against vulnerabilities without affects being defined

- src/commands/aas/__tests__/instrument.test.ts
- src/commands/aas/instrument.ts
- src/helpers/__tests__/upload.test.ts
- src/helpers/apikey.ts
Adds API key validation to the `aas instrument` CLI to check for a valid API key before adding it to the instrumentation.
Calls the `/api/v1/validate` endpoint to ensure the key is valid
> [SVLS-7006] add api key validation

- src/commands/coverage/upload.ts
We want `this.git` even if `this.skipGitMetadataUpload` is true
Move `this.git` initialization outside of the `this.skipGitMetadataUpload` `if`
Make sure the tests we have today work
> Fix `git` logic in `coverage upload` command

- src/commands/coverage/__tests__/fixtures/subfolder.xml/opencover-coverage-invalid.xml
- src/commands/coverage/__tests__/fixtures/subfolder.xml/opencover-coverage-malformed.xml
- src/commands/coverage/__tests__/fixtures/subfolder.xml/opencover-coverage.xml
- src/commands/coverage/__tests__/upload.test.ts
- src/commands/coverage/__tests__/utils.test.ts
- src/commands/coverage/utils.ts
Updates `coverage upload` command, adding detection and validation logic specific to Opencover format.
> Support uploading opencover coverage reports

- src/commands/sbom/__tests__/fixtures/sbom-with-exclusion.json
- src/commands/sbom/__tests__/payload.test.ts
- src/commands/sbom/__tests__/validation.test.ts
- src/commands/sbom/constants.ts
- src/commands/sbom/payload.ts
- src/commands/sbom/types.ts
Our current scans of Maven projects do it by analyzing `pom.xml` files and resolving transitive dependencies down the road. However, it does not currently support the Maven `<exclusions>` mechanism ([doc](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html)), which allows projects to intentionally omit specific transitive dependencies.
As a result, our SCA scanning includes dependencies that are explicitly excluded by the project, leading to inaccurate or misleading outputs. 
We now set as a property the detected exclusions for a given package, we should send it to the API as a property. 
We are reading:
```json
{
"properties": [
{ "name": "datadog-sbom-generator:exclusion", "value": "com.github.jnr:jnr-ffi"}, // this
{ "name": …
```
> [K9VULN-5872] Send exclusion properties as a dependency field

- src/commands/aas/__tests__/common.test.ts
- src/commands/aas/__tests__/instrument.test.ts
- src/commands/aas/common.ts
- src/commands/aas/instrument.ts
- src/commands/aas/interfaces.ts
Adds the additional required dotnet settings as specified by the docs. This allows us to fully support instrumenting dotnet applications running on linux code or container runtimes
Adds an additional flag `--dotnet` to force the settings, and for code runtimes we can auto-detect the runtime and add it in after the fact.
> [SVLS-7005] aas instrument dotnet settings support

- README.md
- container/Dockerfile
- container/entrypoint.sh
Closes #1658 
Same as https://github.com/DataDog/datadog-sca-github-action/blob/e373cb84ac57d35fbefd4c7c7ee5b4592e976fbc/entrypoint.sh#L71
Git fails when the current user inside the `docker/ci` container is not the user owning the files:
```sh
fatal: detected dubious ownership in repository at '/w'
```
And `/w` is the directory where we expect users to mount their host's repository folder: [see docs](https://github.com/DataDog/datadog-ci/blob/42ce08a40d1905ffb9846c1d292db09a916edec2/README.md?plain=1#L197).
> [SYNTH-20482] Mark `/w` as safe in docker image entrypoint

- package.json
- src/commands/cloud-run/__tests__/instrument.test.ts
- src/commands/cloud-run/flare.ts
- src/commands/cloud-run/instrument.ts
- src/commands/cloud-run/types.ts
- yarn.lock
Needed to get `instrument` working with Cloud Run functions.
I was getting Typescript build errors:
```
node_modules/@google-cloud/run/node_modules/google-auth-library/build/src/auth/jwtclient.d.ts:1:29 - error TS1479:
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'.
Consider writing a dynamic 'import("gtoken")' call instead.
```
Since `gtoken` is [dual-shipped in ESM and CJS](https://github.com/googleapis/node-gtoken/blob/2c21cb7a8e9d4c8511000916af5a12cb268d83c0/package.json#L37-L44), but google-auth-library [is not](https://github.com/googleapis/google-auth-library-nodejs/blob/082c171cae021e184d68bf3c794fdf8f2eddbd94/package.json#L9-L10).
The workaround now is to …
> [chore] Bump `@google-cloud/run` to v2

- src/commands/coverage/renderer.ts
- src/commands/coverage/upload.ts
- src/commands/coverage/utils.ts
- src/commands/junit/utils.ts
- src/commands/sarif/renderer.ts
- src/commands/sbom/api.ts
- src/commands/sbom/renderer.ts
- src/helpers/app.ts
When running the `coverage upload` command, prints a link to code coverage details screen in Datadog
> Print link to Datadog UI when uploading coverage data

- LICENSE-3rdparty.csv
- package.json
- src/commands/cloud-run/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/cloud-run/__tests__/instrument.test.ts
- src/commands/cloud-run/__tests__/utils.test.ts
- src/commands/cloud-run/instrument.ts
- src/commands/cloud-run/interfaces.ts
- src/commands/cloud-run/prompt.ts
- src/commands/cloud-run/renderer.ts
- src/commands/cloud-run/utils.ts
- yarn.lock
In the Cloud Run instrument command:
- Implement `--dry` flag
- Implement `--interactive` flag
- And finally, display a git-style diff of the service configuration when running the instrument command:
<br/>
<br/>
> [Cloud Run Instrument] Dry run and interactive mode

- src/commands/cloud-run/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/cloud-run/__tests__/instrument.test.ts
- src/commands/cloud-run/instrument.ts
- src/commands/lambda/__tests__/instrument.test.ts
- src/commands/lambda/instrument.ts
- src/helpers/git/instrument-helpers.ts
- Allow user to optionally customize sidecar image, sidecar name, log volume name, log volume path, and logs file path
- Implement `--fips` flag
- Implement source code integration in Cloud Run tags
- Implement `--sidecar-cpus` and `--sidecar-memory` flags to let users customize their sidecar allocation
This is the last PR required before we can release and document the `datadog-ci cloud-run instrument` command
If they pass invalid values for cpu/memory, the cloud-run API has a nice error message, so we don't need to validate anything:
There are cases where customizing the sidecar name, log volume name, log volume path, and logs file path might be useful. However, it's only recommended for users that know what they're doing. 
For example, if the user instruments their app with …
> [Cloud Run Instrument] FIPs, source code integration, and customizable sidecar,shared-volume,logs-path

- LICENSE-3rdparty.csv
- package.json
- src/commands/aas/__tests__/common.ts
- src/commands/aas/__tests__/instrument.test.ts
- src/commands/aas/instrument.ts
- yarn.lock
Adds automatic tagging support to the AAS for full  [Unified Service Tagging](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/) support, via the Azure Integration.
Uses the resource management client to add in the additional tags, since this cannot be done with the web apps client
> [SVLS-7097] add unified tags as resource tags

- src/commands/aas/__tests__/instrument.test.ts
- src/commands/aas/common.ts
- src/commands/aas/instrument.ts
- src/commands/aas/interfaces.ts
- static-analysis.datadog.yml
Add arbitrary environment variable support, since there are many options that folks may want to use.
Adds an additional param which takes in a list of `key=value` strings to add to the main container and sidecar.
> [SVLS-7098] aas instrument support arbitrary env vars

- src/commands/synthetics/__tests__/base-command.test.ts
- src/commands/synthetics/base-command.ts
Closes https://github.com/DataDog/datadog-ci/issues/1712
This PR fixes the JUnit reporter not being initialized by the base command.
Fix order of calls in `this.setup()`, add unit tests, and add JSDoc + reorganize the file
> [SYNTH-20802] Fix JUnit reporter not being initialized

- src/commands/coverage/__tests__/fixtures/random-file-symlink.xml
- src/commands/coverage/__tests__/upload.test.ts
- src/commands/coverage/upload.ts
- src/helpers/file-finder.ts
Fixes the code that does directory scanning for code coverage reports upload.
The code mistakenly assumed that anything that is not `isFile()` is a directory, and this check failed for symlinks.
The fixed code uses `statSync` instead of `lstatSync` to follow symlinks. It also does not assume that anything that isn't a file is a directory, and does an explicit check as well.
There's a minor improvement to the `--ignored-paths` param handling as well: now it's possible to specify an ignored paths partially (no need to specify the full path relative to what the scan directory is).
> Fix coverage upload dir scan to handle symlinks

- src/commands/coverage/upload.ts
Fixes calculation of pull-request base SHA in GitHub actions.
When running a GHA with a `pull_request` trigger, GitHub merges the head of the feature branch into the _head_ of the target branch, and runs the CI checks on the merge commit.
The `head_sha` attribute available in the pull-request event JSON is the head of the feature branch.
The `base_sha` attribute is the _head_ of the target branch (not the real base commit).
Thus, `base_sha` provided by GitHub is not suitable for our PR diff calculation, as it may include more commits than we need.
The solution is to look for a merge-base of the `head_sha` and the `base_sha` to find the real base commit.
In case `base_sha` was correct to begin with (e.g. for another CI provider), doing a merge-base will not alter it.
> Fix base SHA calculation for GitHub actions

- src/commands/coverage/upload.ts
Removes redundant log message from `coverage upload` command.
> Remove redundant log from coverage upload command

- .github/CODEOWNERS
We want to rename the `@DataDog/datadog-ci` team to `@DataDog/datadog-ci-admins` as the current clashes with the name of the library, resulting in email spamming when the library is commented on a PR (cf screenshot). 
This PR adds the new team name as code owners, and we will cleanup the old name later when the team gets renamed.
- Add `@DataDog/datadog-ci-admins`  to the  `CODOWNERS` file.
~~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~~
> Add `datadog-ci-admins` group to codeowners

- src/commands/aas/__tests__/common.test.ts
- src/commands/aas/__tests__/instrument.test.ts
- src/commands/aas/common.ts
- src/commands/aas/instrument.ts
- src/commands/aas/interfaces.ts
Previously, `musl` was the default backend for the profiler path, which should be glibc, since Azure is now using only ubuntu for dotnet code deployments. if customers are instrumenting a musl-based containerized web app running dotnet, they can now specify the `--musl` flag to specify, since we would have no way of knowing otherwise.
> [SVLS-7166] [AAS .NET] use glibc by default for the profiler path, with the option for musl

- .github/release.yml
- .github/workflows/pr-required-labels.yml
Some PRs are spanning across multiple commands, which make them "repo-wide" (like https://github.com/DataDog/datadog-ci/pull/1723).
We want to put those PRs under a `## datadog-ci` section in the release notes (like [`v3.14.0`](https://github.com/DataDog/datadog-ci/releases/tag/v3.14.0).
Create a `datadog-ci` label and configure it in YML files.
> [chores] Add `datadog-ci` label for repo-wide changes

- .github/CODEOWNERS
- #1759
We want to rename the `@DataDog/datadog-ci` team to `@DataDog/datadog-ci-admins` as the current clashes with the name of the library, resulting in email spamming when the library is commented on a PR (cf previous PR).
This PR removes the old team name as code owners, now that the team got renamed to `@DataDog/datadog-ci-admins`.
- Remove `@DataDog/datadog-ci` from the `CODEOWNERS` file
~~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~~
> Remove the `@DataDog/datadog-ci` from CODEOWNERS

- LICENSE-3rdparty.csv
- package.json
- src/commands/synthetics/README.md
- src/commands/synthetics/tunnel/tunnel.ts
- yarn.lock
Use the `debug` package to support `DEBUG=synthetics:tunnel datadog-ci ...`
Replace `this.reporter.warn` calls with `debug` calls for some non-actionable warn logs.
All those warn logs were being printed even for successful runs, so they aren't interesting. In case the user suspects something is going wrong because of the tunnel, they can enable debug logs with `DEBUG=synthetics:tunnel`
> [synthetics] Downgrade some tunnel warn logs to debug

- .github/workflows/publish-release.yml
We want to automatically create a PR in the `batch-smoke-tester` repo when there is a new release of `datadog-ci`.
- Add the repo to the `bump-ci-integrations` job list.
~~- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)~~
> [SYNTH-19315] Add batch-smoke-tester to bump-ci-integrations list

- src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
- src/commands/synthetics/__tests__/reporters/default.test.ts
- src/commands/synthetics/interfaces.ts
- src/commands/synthetics/reporters/default.ts
This PR improves how the default reporter behaves with results without `subtype`.
Refactor
> [synthetics] Support results without `subtype` in default reporter

- .github/dependabot.yml
Try setting `versioning-strategy` as advised here: https://github.com/dependabot/dependabot-core/issues/10594
Hopefully this will force dependabot to update `package.json` in addition to `yarn.lock`. (For example, [this PR does not update our version range in `package.json`](https://github.com/DataDog/datadog-ci/pull/1767)).
Add dependabot configuration file
> [chores] Set `versioning-strategy: increase` for dependabot

- .github/CODEOWNERS
I noticed https://github.com/DataDog/datadog-ci/pull/1773 didn't require Serverless ONE as codeowners, so this fixes that.
Updates codeowners
> [SVLS] add ONE to flare helpers

- package.json
- yarn.lock
The `4.10.2` patch version of `@azure/identity` dropped support for Node 18, which datadog-ci still supports.
See https://github.com/Azure/azure-sdk-for-js/pull/34773#issuecomment-3175073616.
Downgrade to the last version that supports Node 18.
> [dep] Downgrade @azure/identity from to `4.10.2` to `4.10.1`

- src/commands/gate/renderer.ts
We mistakingly started url-encoding the Details URL on the CLI which is already url-encoded by the API, resulting on double-encoding issues.
The encoding was added as an attempt to fix an edge case with Azure DevOps repositories, but ended up affecting the majority of customers. The edge case will be fixed server-side. 
Rollback changes from #1639
> [SCICM-4946] Rollback "Escape Details URL in Quality Gates Response"

- src/commands/cloud-run/__tests__/__snapshots__/instrument.test.ts.snap
- src/commands/cloud-run/instrument.ts
- Add `DD_SERVERLESS_LOG_PATH` to app containers. Before, we were only adding it to the sidecar container
- Although it's not required, it's useful for the user to have in the main app. Because if they have a mismatch between the log path they try to write to and the log path defined in the sidecar env var, they will have dropped logs.
- In https://github.com/DataDog/serverless-gcp-sample-apps, we want to use best practices and have the sample logging libraries write to the file defined in `DD_SERVERLESS_LOG_PATH` to prevent customers from having mismatched log path values and losing logs
> [Cloud Run] Add DD_SERVERLESS_LOG_PATH to app containers

- src/commands/coverage/README.md
- src/commands/coverage/__tests__/api.test.ts
- src/commands/coverage/__tests__/upload.test.ts
- src/commands/coverage/api.ts
- src/commands/coverage/interfaces.ts
- src/commands/coverage/renderer.ts
- src/commands/coverage/upload.ts
This PR adds `--base-path` parameter to `coverage upload` command.
> Add --base-path parameter to coverage upload command

- package.json
- src/commands/cloud-run/__tests__/flare.test.ts
- src/commands/cloud-run/utils.ts
- yarn.lock
Related to https://github.com/DataDog/datadog-ci/issues/1283
- https://github.com/googleapis/google-auth-library-nodejs/releases/tag/v10.0.0
Bump the dependency. None of the breaking changes impacted us. And our minimal Node.js version (18) is still supported  by the library.
> [dep] Bump `google-auth-library` to 10.2.1

- packages/datadog-ci/src/commands/cloud-run/README.md
- packages/datadog-ci/src/commands/cloud-run/__tests__/instrument.test.ts
- packages/datadog-ci/src/commands/cloud-run/instrument.ts
- packages/datadog-ci/src/constants.ts
Add a `--language` flag, which sets the `DD_SOURCE` flag in the sidecar container, allowing for Log Pipeline Parsing.
The goal here is to just make it easier for people to setup log/trace correlation and other log parsing features.
> Cloud Run Instrument Language Flag

- yarn.lock
When https://github.com/DataDog/datadog-ci/pull/1841 was merged all pipelines were green, but on `master` [they are failing](https://github.com/DataDog/datadog-ci/actions/runs/17738382739/job/50405889387).
This PR is the result of running `yarn` and committing the updated `yarn.lock` file.
> Run yarn to fix broken pipelines

- packages/base/src/cli.ts
- packages/plugin-aas/src/__tests__/instrument.test.ts
- packages/plugin-aas/src/__tests__/uninstrument.test.ts
- packages/plugin-aas/src/cli.ts
- packages/plugin-aas/src/commands/instrument.ts
- packages/plugin-aas/src/commands/uninstrument.ts
I forgot to add aas to base `cli.ts`, so we need to do that
To do that we need to fix the path mappings by moving the command logic under the command directory in the plugin.
> [SVLS] fix aas path mappings

- .github/workflows/ci.yml
- .github/workflows/publish-prerelease.yml
- .github/workflows/publish-release.yml
- .yarn/patches/@yao-pkg-pkg-fetch-npm-3.5.24-3b96980136.patch
- .yarn/patches/@yao-pkg-pkg-npm-6.6.0-d4777368b9.patch
- bin/compare-binary-size.js
- eslint.config.mjs
- package.json
- packages/datadog-ci/scripts/esbuild.mjs
- packages/datadog-ci/shims/intl-collator.js
- yarn.lock
This PR patches `@yao-pkg/pkg` and `@yao-pkg/pkg-fetch` to use precompiled binaries without `Intl` support with the `--sea` option.
See https://github.com/Drarig29/pkg-fetch#this-project-is-a-fork-used-by-datadogdatadog-ci-see-1858 for the big picture.
| Before      | After       |
| ----------- | ----------- |
| <img width="735" height="364" alt="image" src="https://github.com/user-attachments/assets/210eea10-9db2-40e4-a151-a2a294676ca2" />         | <img width="725" height="365" alt="image" src="https://github.com/user-attachments/assets/62efe32c-1ec4-4bc8-b8d4-5fa171148252" />         |
| [**Link**](https://github.com/DataDog/datadog-ci/actions/runs/17949601069/job/51045668951?pr=1858#step:9:5) | [**Link**](https://github.com/DataDog/datadog-ci/actions/runs/17949673652/job/51045754438?p …
> [chore] Decrease standalone binary size

- packages/plugin-deployment/package.json
* [packages-migration] Move root package to packages dir by @Drarig29 in https://github.com/DataDog/datadog-ci/pull/1815
* [packages-migration] Create `@datadog/datadog-ci-base` package by @Drarig29 in https://github.com/DataDog/datadog-ci/pull/1804
* [chore] Use Node.js SEA for standalone binary by @Drarig29 in https://github.com/DataDog/datadog-ci/pull/1835
* [chore] Decrease standalone binary size by @Drarig29 in https://github.com/DataDog/datadog-ci/pull/1858
* [chore] Symlink README and duplicate LICENSE files by @Drarig29 in https://github.com/DataDog/datadog-ci/pull/1859
* [dep] Bump axios to `1.12.1` by @Drarig29 in https://github.com/DataDog/datadog-ci/pull/1839
* Update Software Delivery ownership by @GabrielAnca in https://github.com/DataDog/datadog-ci/pull/1818
* Fix isFile …
> v3.21.1 (redo)

- package.json
This flag is a leftover from before we used `--sea` (introduced in #1835).
The `--compress` flag is used to [compress files in `pkg`'s **virtual filesystem**](https://github.com/vercel/pkg/pull/1115), and `--sea` does not use the virtual filesystem.
Removing this flag is a no-op and won't affect our binaries' size.
Remove `--compress GZip` flag.
> [chore] Remove unused `--compress` flag for `pkg`

- packages/datadog-ci/README.md
- packages/datadog-ci/src/cli.ts
- packages/plugin-dora/README.md
The DORA Metrics product has gone out of beta, so the command should be generally available too
Remove the need for `DD_BETA_COMMANDS_ENABLED` environment variable to run the command
> Release dora command

- packages/plugin-deployment/src/__tests__/__snapshots__/gate.test.ts.snap
- packages/plugin-deployment/src/commands/gate.ts
The `deployment gate` command considers timeouts or datadog errors as a passed gate by default. This is done to prevent datadog failures from blocking customers pipelines. However, it's possible to override this behavior.
This PR adds an extra log line after this happens explaining how this behavior can be overriden
> Add hint about --fail-on-error param on deployment gate unexpected failures

- packages/base/src/helpers/plugin.ts
**Related PRs:**
- https://github.com/DataDog/datadog-ci/pull/1887
- https://github.com/DataDog/datadog-ci/pull/1886
- https://github.com/DataDog/datadog-ci/pull/1890
- https://github.com/DataDog/datadog-ci/pull/1891
This PR adds a notice in the CLI to inform customers about next major release.
**Example output:**
- Update `plugin.ts` to handle the notice
> [chore] Add notice for next major release
