DataDog/datadog-ci

.github/CODEOWNERS, src/commands/lambda/README.md
Updates to the documentation for the serverless configs so that we can pull it into the main documentation site.
=> documentation updates for the serverless functions

.github/workflows/ci.yml, .github/workflows/publish.yaml, README.md, package.json
Add instructions to release `datadog-ci` package.
=> [README] add release process

.github/workflows/publish.yml
We want to make it as automatic as possible to release the package.
Add a github actions script to release the package.
=> Add Publish Script

.github/workflows/publish.yml, package.json
Publishing job is failing.
- using `NPM_AUTH_TOKEN`
- bump to `0.8.2`
=> Fix publish

.github/CODEOWNERS
=> CODEOWNERS change.

src/commands/trace/command.ts, src/helpers/__tests__/ci.test.ts, src/helpers/ci.ts, src/helpers/interfaces.ts
Update naming of `commit_sha` to keep consistency. 
Change `commit_sha` to `commitSha`
=> Fix Naming of Commit SHA

src/commands/synthetics/__tests__/fixtures.ts, src/commands/synthetics/interfaces.ts, src/commands/synthetics/renderer.ts
This PR improves the rendering of synthetics results for synthetics API SSL/TCP and DNS tests.
=> [synthetics] improve synthetics API results rendering

src/commands/lambda/README.md
Add slack community link to encourage community feedback.
=> Add slack community link

package.json
Alpha release including the changes from https://github.com/DataDog/datadog-ci/pull/158
=> Release v0.10.4-alpha

src/commands/sourcemaps/__tests__/upload.test.ts, src/commands/sourcemaps/upload.ts
Upload any file ending with `js.map` to accommodate for more extensions.
=> Allow additional extensions to be uploaded

src/commands/sourcemaps/README.md
Documentation about this parameter is not very clear, trying to improve it.
=> Make documentation clearer.

package.json, src/commands/synthetics/README.md, src/commands/synthetics/__tests__/tunnel.test.ts, src/commands/synthetics/__tests__/utils.test.ts, src/commands/synthetics/interfaces.ts, src/commands/synthetics/renderer.ts, src/commands/synthetics/tunnel.ts, src/commands/synthetics/utils.ts, src/commands/synthetics/websocket.ts, src/commands/trace/command.ts, src/helpers/tags.ts, yarn.lock
Merge latest master (v0.11.3) in the alpha channel to be able to benefit from bugfixes while also testing new features.
=> [alpha] merge latest master

src/commands/synthetics/README.md, src/commands/synthetics/__tests__/run-test.test.ts, src/commands/synthetics/run-test.ts
Reverts DataDog/datadog-ci#205
Forgot about the node version discussion.
=> Revert "[synthetics] Add --files parameter"

package.json, src/commands/synthetics/README.md, src/commands/synthetics/__tests__/run-test.test.ts, src/commands/synthetics/run-test.ts, testEnvironment.js, yarn.lock
=> v0.11.6-alpha

package.json, src/helpers/__tests__/ci-env/circleci.json, src/helpers/ci.ts, src/helpers/interfaces.ts, src/helpers/tags.ts, yarn.lock
Merge latest master into alpha and bump version to `v0.13.2-alpha`.
=> v0.13.2-alpha

src/helpers/__tests__/git.test.ts, src/helpers/git.ts, src/helpers/tags.ts
We want the full CI App experience even for CIs that are not instrumented. This allows for that. 
* Add extra git metadata to the git extraction.
=> [ci-app] Add Rich Commit Metadata

src/commands/synthetics/__tests__/crypto.test.ts, src/commands/synthetics/__tests__/run-test.test.ts, src/commands/synthetics/__tests__/utils.test.ts
=> [synthetics-test] clean tests

package.json, testEnvironment.js, yarn.lock
* Keep `dd-trace` up to date. 
* Mainly fix bugs, like instrumentation of snapshot errors and retries in timeouts.
=> [ci-app] Bump `dd-trace`

src/commands/synthetics/__tests__/run-test.test.ts, src/commands/synthetics/interfaces.ts, src/commands/synthetics/run-test.ts, src/helpers/__tests__/utils.test.ts, src/helpers/utils.ts
Merge https://github.com/DataDog/datadog-ci/pull/271 in alpha
=> Yeramian/sw 1193/add parameters cli alpha

src/helpers/__tests__/git.test.ts, src/helpers/git.ts
We were getting git diffs as part of commit messages and commit author / committer.
* Use `-s` correctly to remove git diff.
=> [ci-app] Fix Bug in Git Extraction

package.json, src/commands/junit/api.ts, src/commands/sourcemaps/README.md, src/helpers/__tests__/git.test.ts, src/helpers/git.ts
Ship latest changes from master to `alpha`.
=> 0.13.6-alpha

package.json, src/commands/commit/README.md, src/commands/commit/git.ts, src/commands/sourcemaps/git.ts, src/commands/synthetics/__tests__/run-test.test.ts, src/commands/synthetics/run-test.ts
Merge the latest master into alpha which includes:
* #302
* #275
Also includes the latest #264.
=> release v0.13.8-alpha

src/commands/sourcemaps/README.md
A small update to the readme to specify how the git data is actually gathered.
- #267
=> Adjust wording to specify how git data is gathered

src/commands/commit/README.md
Updates the README to specify that using command right now will not unlock any feature in Datadog.
=> [commit] README update

package.json
=> Update alpha version.

README.md
This step is required to release on the alpha channel.
=> Add required steps for alpha release in docs.

src/commands/commit/README.md, src/commands/sourcemaps/README.md
=> Fix sourcemaps/commit readme

src/commands/junit/api.ts, src/commands/junit/utils.ts
Current DNS and URL are deprecated
=> [CIAPP-2679] Update DNS and url for junit upload with v2 API

package.json, yarn.lock
=> Fix version of proxy lib.

LICENSE-3rdparty.csv, package.json, src/commands/junit/api.ts, src/commands/junit/upload.ts, src/commands/junit/utils.ts, src/commands/lambda/README.md, src/commands/lambda/__tests__/instrument.test.ts, src/commands/lambda/instrument.ts, src/commands/synthetics/README.md, src/commands/synthetics/__tests__/run-test.test.ts, src/commands/synthetics/__tests__/utils.test.ts, src/commands/synthetics/interfaces.ts, src/commands/synthetics/reporters/default.ts, src/commands/synthetics/run-test.ts, src/commands/synthetics/utils.ts, src/commands/trace/README.md, src/commands/trace/__tests__/trace.test.ts, src/commands/trace/api.ts, src/commands/trace/index.ts, src/commands/trace/interfaces.ts, src/commands/trace/trace.ts, src/helpers/__tests__/tags.test.ts, src/helpers/__tests__/utils.test.ts, src/helpers/tags.ts, src/types/proxy.d.ts, yarn.lock
Alpha release that includes the new `trace` command.
=> [alpha] 0.17.0 – New `trace` command

src/commands/trace/trace.ts
Add support for `--tags` to the `trace` command
Same as in the `junit` command
=> Add --tags to trace command

src/commands/trace/__tests__/trace.test.ts, src/commands/trace/interfaces.ts, src/commands/trace/trace.ts
Add support for custom spans in Jenkins
Gather the necessary env vars so the backend can create the span
=> Add Jenkins support for custom spans

package.json
Release version `0.17.2`
- https://github.com/DataDog/datadog-ci/pull/377
- https://github.com/DataDog/datadog-ci/pull/381
=> Release v0.17.2

package.json
=> Release v0.17.3

package.json
=> Release v0.17.4

src/commands/lambda/README.md
Add documentation for #436.
Updating `README.md`.
N/A
=> [lambda][docs] Add documentation for us5 site

src/commands/lambda/README.md
Add documentation for `DD_CAPTURE_LAMBDA_PAYLOAD` option.
Updating `README.md`
N/A
=> [lambda] Add documentation for `DD_CAPTURE_LAMBDA_PAYLOAD`

package.json, src/commands/lambda/__tests__/instrument.test.ts
Release `v1.3.0`: 
* #510
* #512 
* #515 
* #516 
* #513
=> Release v1.3.0

package.json, src/commands/dsyms/interfaces.ts, src/commands/git-metadata/interfaces.ts, src/commands/sourcemaps/interfaces.ts
Alpha release with changes from https://github.com/DataDog/datadog-ci/pull/560
=> Alpha release for v2 upload API

package.json, src/commands/synthetics/__tests__/utils.test.ts, src/commands/synthetics/interfaces.ts, src/commands/synthetics/utils.ts
Release v1.7.4-alpha with:
- https://github.com/DataDog/datadog-ci/pull/571
=> Alpha 1.7.4

.github/CODEOWNERS
Update repository CODEOWNERS
`@DataDog/ci-app-tracers` -> `@DataDog/ci-app-libraries`
- Add `metric` command
- Add `tag` command
- Add `trace` command
- Add `react-native` command
- CI: `@DataDog/ci-app-tracers`, `@DataDog/synthetics-worker`
- Git: `@DataDog/ci-app-tracers`, `@DataDog/source-code-integration`
`@DataDog/datadog-ci`: general fallback, overwrite all `.md` files with `@DataDog/documentation`
=> [github] Update CODEOWNERS

src/commands/lambda/prompt.ts
=> Fix a typo

src/commands/tag/README.md
=> Remove tag beta warning

src/commands/synthetics/__tests__/api.test.ts, src/commands/synthetics/api.ts
[Card](https://datadoghq.atlassian.net/browse/SYM-327)
- Add getTunnelPresignedURL endpoint to get pre-signed url to upload mobile application in the CI.
=> synthetics: Add getTunnelPresignedURL endpoint

src/commands/synthetics/__tests__/api.test.ts, src/commands/synthetics/api.ts
- Add `uploadMobileApplication` endpoint
- Update mobile pre-signed test
=> Synthetics: Add `uploadMobileApplication` endpoint

src/commands/sourcemaps/upload.ts
Example text is misleading 😄 
Updated example command usage to match description
=> fix: update usage example for sourcemaps upload

.github/PULL_REQUEST_TEMPLATE.md
Update PR template to include Azure DevOps extension requirement
=> Add ADO requirement to PR template

src/commands/synthetics/__tests__/utils.test.ts, src/commands/synthetics/utils.ts
The `file` property of the JUnit report (path of a suite file) is shown as a hyperlink on GitLab, and it must be a file path relative to the root of the repository. If `datadog-ci` is run from a subdirectory, the link will be broken.
This PR ensures the file path is relative to the root of the repository.
Use a combination of `git rev-parse --show-toplevel` and `path.relative()` to get the corrected file path.
=> [synthetics] Ensure suite file path is relative to repo

package.json
Adds `--remove-sources-content` argument to react-native commands.
=> Release v1.17.0

src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap, src/commands/synthetics/reporters/default.ts
Improved wordings of references to a single test result and a batch results, as they were a bit fuzzy
=> [SW-2489] Improve logs output

package.json, yarn.lock
=> upgrading inquirer (closes #708)

src/commands/lambda/__tests__/functions/uninstrument.test.ts, src/commands/lambda/functions/uninstrument.ts
Users realized that AWS_LAMBDA_EXEC_WRAPPER environment variable is not being removed when using lambda uninstrument
This variable is being set for .NET and Java environments.
Uninstrument properly for the specified runtimes by updating `calculateUpdateRequest` under `functions/uninstrument.ts`.
=> [lambda] Properly uninstrument `AWS_LAMBDA_EXEC_WRAPPER`

README.md
Minor formatting update.
Chat with Beth
=> Datadog CI README Doc Edit

src/commands/synthetics/README.md
Slack conversation with Etienne and Beth
**Preview**: https://docs-staging.datadoghq.com/alai97/continuous-testing-configuration-readme-preview/continuous_testing/cicd_integrations/configuration/
=> Synthetics Command README Code Formatting Update

src/commands/synthetics/tunnel/tunnel.ts
Change tunnel connections error to warnings.
=> [Synthetics] Tunnel: Downgrade connection error logs to warnings

package.json, yarn.lock
Closes #752 
Bump inquirer-checkbox-plus-prompt from `1.0.1` to `1.4.2`
=> [deps] Bump `inquirer-checkbox-plus-prompt`

.github/workflows/ci.yml, LICENSE-3rdparty.csv, package.json, yarn.lock
This PR modifies the GitHub Action to add a SARIF format report from ESLint. The report is uploaded as an artifact.
=> Add SARIF report to datadog-ci

src/commands/lambda/__tests__/loggroup.test.ts, src/commands/lambda/loggroup.ts
Fixes https://github.com/DataDog/datadog-ci/issues/699 by adding support for 2 log group subscriptions
* Considers a log group to still have an "Empty" subscription state if there is at least 1 empty slot in the 2 allocated by AWS
* Fixes existing tests and add 2 more for cases with unowned subscriptions
=> [lambda] Add Datadog forwarder subscription alongside existing filter

package.json, yarn.lock
Keep up with latest features and bug fixes.
Bump `dd-trace` to `3.13.2`
=> [ci-visibility] Bump `dd-trace`

src/commands/synthetics/README.md
Just noticed some inconsistencies.
=> [docs] Consistency and fix typos

src/commands/synthetics/README.md, src/commands/synthetics/__tests__/api.test.ts, src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap, src/commands/synthetics/__tests__/reporters/default.test.ts, src/commands/synthetics/__tests__/run-test.test.ts, src/commands/synthetics/__tests__/utils.test.ts, src/commands/synthetics/api.ts, src/commands/synthetics/command.ts, src/commands/synthetics/interfaces.ts, src/commands/synthetics/reporters/default.ts, src/commands/synthetics/reporters/junit.ts, src/commands/synthetics/run-test.ts, src/commands/synthetics/utils.ts
Amend the synthetics-test report so it shows up the possibility to speed up tests execution through parallelisation.
=> SYNTH-8640-adapt-report-summary

src/helpers/__tests__/ci-env/codefresh.json, src/helpers/ci.ts
Create tags based on env vars from the CodeFresh CI provider.
=> Add support for Codefresh env vars

src/commands/synthetics/README.md
Adds a link to an example global configuration file.
Hotjar feedback in DOCS-5128
=> DOCS-5128 Continuous Testing and CI/CD Configuration Doc Edit

package.json
Release this fix: https://github.com/DataDog/datadog-ci/pull/813/files
=> Bump to v2.5.2-alpha2 release.

.github/workflows/ci.yml, package.json, yarn.lock
Keep up with latest changes.
Bump `dd-trace` to `3.16.0`
=> Bump `dd-trace`

src/commands/git-metadata/__tests__/gitdb.test.ts, src/commands/git-metadata/gitdb.ts, src/commands/git-metadata/upload.ts, src/helpers/logger.ts, src/helpers/utils.ts
I want to reuse those in a different command.
I moved the code to the common `helpers` directory.
=> Refactor git-metadata/utils

src/commands/metric/__tests__/metric.test.ts, src/commands/tag/__tests__/tag.test.ts, src/helpers/__tests__/ci.test.ts, src/helpers/ci.ts
Add Azure to supported CI for custom tags and custom metrics commands
=> Add env vars for custom tags command in Azure

src/commands/lambda/__tests__/functions/instrument.part2.test.ts, src/commands/lambda/constants.ts
Adds support for python 3.10
Updates constants and adds test
=> [lambda] Add python 3.10 instrumentation support

src/helpers/__tests__/ci-env/buddy.json, src/helpers/__tests__/ci-env/buildkite.json, src/helpers/__tests__/ci-env/codefresh.json, src/helpers/__tests__/ci-env/gitlab.json, src/helpers/__tests__/ci-env/jenkins.json, src/helpers/__tests__/ci.test.ts, src/helpers/ci.ts, src/helpers/interfaces.ts, src/helpers/tags.ts
Keep up to date with CI Visibility spec.
* Add codefresh support
* Read `CI_NODE_LABELS` and `CI_NODE_NAME` from certain CI providers.
=> [ci-visibility] Update CI Visibility spec

src/commands/junit/README.md
Expose in the junit upload command readme two missing arguments introduced here https://github.com/DataDog/datadog-ci/pull/836
=> Update junit upload README.md

src/cli.ts
=> Include `BETA_COMMANDS` 

src/commands/synthetics/README.md
Add an Example Test File link.
DOCS-5436
https://docs-staging.datadoghq.com/alai97/continuous-testing-anchor-link-cleanup/continuous_testing/cicd_integrations/configuration
=> DOCS-5436 Configuration Edits

src/commands/gate/api.ts, src/commands/gate/evaluate.ts, src/commands/gate/interfaces.ts, src/commands/gate/renderer.ts
Based on gate evaluation response returned, we log important information to customers. 
Example of logs:
=> Logging useful information based on gate evaluation response

.gitignore, src/commands/sarif/__tests__/fixtures/another_subfolder/valid-results.sarif, src/commands/sarif/__tests__/upload.test.ts, src/commands/sarif/renderer.ts, src/commands/sarif/upload.ts
This PR improves the error message when the SARIF report files are not found or are invalid.
=> [static-analysis] Improve error messages when report files not found or invalid.

src/commands/synthetics/README.md
Updates the description for two flags on the [Configuration doc page](https://docs.datadoghq.com/continuous_testing/cicd_integrations/configuration/).
Chat with Corentin on Slack
=> CI/CD Integrations Configuration Doc Edit

src/commands/synthetics/README.md
=> CI/CD Integrations Configuration Edit

src/commands/gate/README.md, src/commands/gate/evaluate.ts
Adding usage and README for gate command
=> Adding usage and README for gate command

src/commands/gate/README.md, src/commands/gate/evaluate.ts, src/commands/gate/renderer.ts
Add waiting time to gate evaluate command
=> Add waiting time to gate evaluate command

src/commands/gate/interfaces.ts, src/commands/gate/renderer.ts
=> Add details URL to rule logs

LICENSE-3rdparty.csv, package.json, yarn.lock
Fixes https://github.com/DataDog/datadog-ci/issues/948
Add the dependency explicitly.
=> Add `@aws-sdk/property-provider` to dependencies

src/commands/lambda/flare.ts
Forgot to remove unused constants in this PR: https://github.com/DataDog/datadog-ci/pull/978
No tests needed
=> [lambda][flare] Remove unused constants

src/commands/lambda/README.md
We need to add documentation for the `lambda flare` before official release.
Update the README file located in `src/commands/lambda/README.md`
No tests needed
=> [lambda][flare] Add lambda flare documentation

src/commands/flutter-symbols/renderer.ts
Added a few sentences to shed more light on what might prevent the symbolication process from working on Flutter Symbols. 
=> [RUMM-3400] Improve output of flutter symbols upload process

package.json
This PR bumps the package to v2.18.1
- #1014 
- #1011 
- #1010 
- #1007
- #977 
- #1006
=> release 2.18.1

src/commands/gate/evaluate.ts
Add DD_APP_KEY to gate command.
JIRA issue: https://datadoghq.atlassian.net/browse/CIAPP-7352
=> Add DD_APP_KEY to gate command

.github/workflows/ci.yml, .github/workflows/e2e/sbom-reports/sbom.json, src/commands/sbom/protobuf/bom-1.4.ts, src/commands/sbom/protobuf/sbom_intake.ts, src/commands/sbom/upload.ts
1. Update the protobuf definition
2. Add e2e tests
1. We need to add the `CI_PIPELINE` as a source, which has been specified in the server protobuf recently
2. We want to make sure that at each commit, SBOM are being correctly processed.
1. Updating the protobuf definition and their TS definition
2. Adding a new e2e test in the GitHub actions
=> Add e2e tests and update protobuf definition

src/commands/git-metadata/gitdb.ts
We lost it in https://github.com/DataDog/datadog-ci/pull/1076#discussion_r1347005786
By using `Promise.all`
=> Improve parallelism in git unshallow

src/helpers/__tests__/ci-env/awscodepipeline.json, src/helpers/ci.ts
Add code to extract env vars & spec test.
=> Add support for AWSCodePipeline

src/commands/dora/interfaces.ts, src/helpers/git/__tests__/format-git-span-data.test.ts
This slipped in #1112 not sure how.
The tests I think were introduced in parallel so we could not catch the error until the merge
=> Fix lint warning on Axios imports and 2 failing tests

src/commands/synthetics/utils.ts
Refactor `waitForBatchToFinish` because it could be easier to read.
- Change `do {} while ()` to `while () {}`
- Generally in `while (true)` loops, it's clearer to have a condition for `break`ing or `return`ing, rather than `continue`ing.
=> [synthetics] Refactor `waitForBatchToFinish`

package.json, yarn.lock
=> [dep] Bump `@google-cloud/logging` to `v11`

.github/workflows/ci.yml, src/commands/sbom/upload.ts
Re-enabled SBOM e2e test with staging.
=> Add SBOM checker in CI/CD pipeline

src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap, src/commands/synthetics/reporters/default.ts
=> Update wording for "your total test duration"

.gitignore, .vscode/extensions.json, .vscode/settings.json
Useful for people onboarding on the repo with VS Code.
Add `.vscode/settings.json` and `.vscode/extensions.json` files
=> [dev] Commit vscode settings and suggested extensions

README.md
I don't know what happened during #1143, but some `/` and `?` are missing...
FIx the links
=> [doc] Fix broken links in readme

package.json
This PR changes the Node version used for development and local IDE tools.
The codebase is **still unit tested against Node 14, 16, 18 and 20**. (#1166)
Change the Node version used with volta.
=> [dev] Use Node 20 for development

.github/workflows/ci.yml, bin/check-junit-upload.js, src/commands/junit/README.md, src/commands/junit/__tests__/upload.test.ts, src/commands/junit/api.ts, src/commands/junit/interfaces.ts, src/commands/junit/renderer.ts, src/commands/junit/upload.ts, src/commands/tag/README.md
This PR implements the same thing as the reverted https://github.com/DataDog/datadog-ci/pull/1203, but with the regression fixed
=> [CIVIS-9031] Deprecate 'metrics' naming in favour of 'measures' in junit cmd

.github/CODEOWNERS, .github/advanced-issue-labeler.yml, .github/workflows/pr-required-labels.yml, .github/workflows/release.yml
This PR updates labels with our new commands in order to label issues **and PRs**.
Labelling PRs will categorize the PRs when using [automatic release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).
- Update `.github/advanced-issue-labeler.yml`
- Create `.github/workflows/pr-required-labels.yml`
- Add `changelog` configuration in `.github/workflows/release.yml`
=> [chores] Update labels and setup automatic release notes

src/commands/react-native/__tests__/xcode.test.ts, src/commands/react-native/xcode.ts
Our `react-native xcode` command does not match the logic from the `react-native-xcode.sh` [script](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react-native-xcode.sh) from React Native.
In particular, bundling the code is required when building an iOS debug app for a real device.
This triggered this issue: https://github.com/DataDog/expo-datadog/issues/31
Implement similar logic from the `react-native-xcode.sh` into our `react-native xcode` command.
=> Bundle React Native code when building debug app for iOS device

CONTRIBUTING.md
This PR documents things to do when creating a new command.
Add instructions to `CONTRIBUTING.md`.
=> [docs] Instructions for creating new commands

.github/release.yml, CONTRIBUTING.md
Fix link in release process, and fix categories in release notes.
Fix link.
=> [chores] Fix link in release process

src/commands/dora/renderer.ts
Fix a typo (`Successfuly` instead of `Successfully`)
Fix the typo
=> [dora] Fix typo in message

package.json
* Fix DD-EVP-ORIGIN header values by @0xnm in https://github.com/DataDog/datadog-ci/pull/1279
* [STAL-1744] Add new validation logic by @juli1 in https://github.com/DataDog/datadog-ci/pull/1278
**Full Changelog**: https://github.com/DataDog/datadog-ci/compare/v2.33.0...v2.33.1
[STAL-1744]: https://datadoghq.atlassian.net/browse/STAL-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prepare version v2.33.1

src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap, src/commands/synthetics/reporters/default.ts
In #1253 I forgot to change this other part in the Continuous Testing Summary.
Update wording.
=> [synthetics] Adjust selective re-run wording

README.md, src/commands/synthetics/README.md
As we rolled out our new product navigation update, we are updating elements in the UI in the related doc pages.
=> DOCS-7748 Continuous Testing and CI/CD Configuration Edits

src/commands/git-metadata/upload.ts
git sync is available in Gov DC so this PR reverts the changes introduced [here](https://github.com/DataDog/datadog-ci/pull/852/files#diff-c8befdef69d86f6e17529292b68860f4b4f89def439f2ed33c80f5d1703c8f6aR128-R133)
=> [SCICM-1184] git sync is now available in Gov DC

src/commands/trace/interfaces.ts, src/commands/trace/trace.ts, src/helpers/tags.ts
Add measure support to custom commands. Fixes https://github.com/DataDog/datadog-ci/issues/1261
Send new field to backend.
=> Add measures for custom commands

src/commands/synthetics/__tests__/mobile.test.ts
=> Change the name of the describe block in mobile test

.gitlab-ci.yml
Change the registry used to build the Docker image internally to avoid permission issues.
- Change the registry URL
- [Failing GitLab job](https://gitlab.ddbuild.io/DataDog/datadog-ci/-/jobs/521139685)
- [Passing GitLab job](https://gitlab.ddbuild.io/DataDog/datadog-ci/-/jobs/521799619)
=> [ci] Change registry for docker image

src/commands/react-native/xcode.ts
Semi-colon broke lint formatting
=> [lint] Fix semi-colon

src/commands/synthetics/README.md
Remove reference to "Continuous Testing Tunnel" for "Local and Staging Environments".
=> DOCS-8127 Continuous Testing and CI/CD Configuration Edit

src/commands/synthetics/__tests__/run-tests-lib.test.ts
We deprecated `global` and `config` in favor of `defaultTestOverrides` and `testOverrides` (#1285 and #1306), and we still want to unit test the old usage.
Instead of duplicating some unit tests, we are using `test.each()` to test the deprecated and current behaviors.
Use `test.each()` and computed object properties
=> [synthetics] Parameterize unit tests for deprecated usages

src/commands/lambda/README.md
Fixing a problem on this page with the TOC not rendering due to a broken closing comment
=> Fix broken closing comment

src/commands/synthetics/README.md
The use of proxy was a bit unclear and did not include how to configure it using a ENV variable, so i've updated that.
Updated README
=> [SYNTH-12979] Document the use of proxy

src/commands/trace/trace.ts
The URL needs to have the API prefix and it does not.
=> [ci-visibility] Fix bug on trace command URL

src/commands/sarif/__tests__/fixtures/test_validation/invalid-sarif-no-rule.sarif, src/commands/sarif/__tests__/upload.test.ts, src/commands/sarif/__tests__/validation.test.ts, src/commands/sarif/renderer.ts, src/commands/sarif/upload.ts, src/commands/sarif/validation.ts
We want to check if the SARIF file has error that will prevent us from processing the file in the backend.
Checking that the file has the appropriate key and values before sending it to our backend.
=> Add SARIF validation

package.json, src/commands/synthetics/__tests__/api.test.ts, src/commands/synthetics/__tests__/fixtures.ts, yarn.lock
Closes https://github.com/DataDog/datadog-ci/security/dependabot/45
- Bump the dependency
=> [dep] Bump axios to `1.7.4`

src/commands/stepfunctions/helpers.ts
Closes https://github.com/DataDog/datadog-ci/issues/1429
=> Fix Step Functions context injection

src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap, src/commands/synthetics/reporters/default.ts
"Success" was supposed to mean "done retrying"
Change 1 word
=> [synthetics] Fix retry attempt wording

src/commands/stepfunctions/helpers.ts
Refactors some code by changing:
```
if (<condition>) {
// do a lot of things
}
return false;
```
to
```
if (!<condition>) {
return false;
}
// do a lot of things
```
Make code more readable in that:
- the "if" block is shorter so the reader won't need to take time to find where the `}` is
- it's more clear that we don't cover the case when `<condition>` is false
This is a simple change, so just `npm test`
=> Refactor step function code by flipping if-condition

src/commands/deployment/__tests__/correlate.test.ts
The tests fails if you make some commits and don't push them making it a flaky test since it depends on the state of the runner in order for the test to pass.
We will remove the test for now. We may want to look into how to mock the git client.
=> [SDCI] Remove correlate command flaky test

CONTRIBUTING.md
Minor adjustments to the release process doc.
=> [chores] Adjustments in release process

src/commands/synthetics/README.md
This PR adds more information about how to use `testSearchQuery`, following a discussion in https://github.com/DataDog/datadog-ci/issues/1511#issuecomment-2557173795.
Update the docs
=> [docs] More info about `testSearchQuery`

src/commands/dsyms/README.md, src/commands/flutter-symbols/README.md
Updates some of the documentation around setting `DATADOG_SITE`.
Fixes #1530.
=> Update docs for dSYMs and flutter-symbols

MIGRATING.md, README.md
This PR creates a migration guide.
Followed the same template as https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md.
=> [docs] Add migration guide for major version `3.0`

src/commands/sarif/validation.ts
We want to push the limit of a SARIF file to 10MB
Bump the constants
=> bump file size for SARIF file

src/helpers/__tests__/ci-env/drone.json, src/helpers/ci.ts
Be able to tell that `datadog-ci` commands are running in Drone CI. 
Read environment variables provided by Drone CI: https://docs.drone.io/pipeline/environment/reference/
=> [SDTEST-1714] Add Drone CI support

src/commands/synthetics/__tests__/build-and-test.test.ts, src/commands/synthetics/build-and-test.ts
This PR adds better error handling for build-and-test, and also more unit test cases.
=> [SYNTH-19229] Add error handling and unit tests to build-and-test

src/commands/synthetics/__tests__/cli.test.ts, src/commands/synthetics/upload-application-command.ts
A customer is having a unhandled error for which we don't have any error message.
Log something for unexpected errors.
=> [synthetics] Improve error handling in mobile upload command

src/commands/sbom/__tests__/payload.test.ts, src/commands/sbom/constants.ts, src/commands/sbom/payload.ts, src/helpers/interfaces.ts, src/helpers/tags.ts
See https://github.com/DataDog/datadog-ci/pull/1598#discussion_r2027252008
Fix build issue caused by `import {...} from 'src/commands/sbom/constants'`
=> [sbom] Fix build issue with import

package.json
* chore: Document IAM permissions needed for Lambda Flare by @lym953 in https://github.com/DataDog/datadog-ci/pull/1605
* [MLOB-2522] Add `--llmobs` flag for instrumenting Lambdas with LLM Observability by @sabrenner in https://github.com/DataDog/datadog-ci/pull/1603
* Make code coverage upload command non-beta by @nikita-tkachenko-datadog in https://github.com/DataDog/datadog-ci/pull/1616
* [feature] Custom span command by @CelianR in https://github.com/DataDog/datadog-ci/pull/1580
* [RN CODEPUSH] Sanitize Upload Release Version by @marco-saia-datadog in https://github.com/DataDog/datadog-ci/pull/1614
* [K9VULN-4382] Parse, validate, and propagate reachability info by @dastrong in https://github.com/DataDog/datadog-ci/pull/1599
* [Synthetics] Redesign build-and-test command to spawn the …
=> Release v3.4.0

.eslintrc.js, .gitignore, package.json
- https://github.com/DataDog/datadog-ci/pull/1620 (← **you are here**)
- https://github.com/DataDog/datadog-ci/pull/1622
- https://github.com/DataDog/datadog-ci/pull/1623
- https://github.com/DataDog/datadog-ci/pull/1624
This PR fixes minor things in various configurations.
Config changes
=> [chores] Fix lint and `.gitignore` file

src/commands/synthetics/__tests__/utils/public.test.ts
This PR fixes flaky retry unit tests in Windows.
Use fake timers.
=> [chores] Fix flaky retry unit tests

src/commands/unity-symbols/renderer.ts
Fix a typo in one of the console messages.
=> Fix error message typo.

src/commands/sbom/renderer.ts, src/commands/sbom/upload.ts
> Reported in https://github.com/DataDog/datadog-ci/issues/1638
The notice displayed when a duplicate upload is detected is outdated and not very helpful.
We're updated the text that's rendered when this duplicate upload error occurs to be more accurate and forthcoming with what actions are needed.
=> [K9VULN-5404] Update duplicate upload notice

src/commands/git-metadata/git.ts
When creating a git client, adds current folder as a `safe.directory` in git config.
Some CI providers check out repository as one user, then run the CI jobs as a different user.
When trying to use git CLI in a folder that belongs to a different user, the `detected dubious ownership in repository at ...` error occurs.
To avoid this, the repo folder needs to be added a safe directory.
=> Add current folder as a safe.directory in git config

src/commands/aas/__tests__/instrument.test.ts, src/commands/aas/instrument.ts
Fixes an issue where settings would not be properly set in the sidecar, since the values are not actually the values, but rather keys to the application settings keys 
Fixes the check and creation to be in the correct format. Validated and was finally able to see traces in datadog
=> [SVLS-6923] fix sidecar application settings

src/commands/aas/__tests__/instrument.test.ts, src/commands/aas/instrument.ts
=> [chore] improve test coverage of helper methods

package.json, yarn.lock
Fixes a warning in Node.js 22: https://github.com/form-data/form-data/issues/563
Bump the dependency
=> [dep] Upgrade form-data to `4.0.3`

CONTRIBUTING.md
`yarn install` step is added to `CONTRIBUTING.md`
=> yarn install step added to CONTRIBUTING.md

README.md, src/commands/cloud-run/README.md, src/commands/cloud-run/cli.ts, src/commands/cloud-run/instrument.ts, src/commands/cloud-run/uninstrument.ts
Feature is ready to be shipped!
=> [Cloud Run] Enable and document instrument & uninstrument commands

src/commands/deployment/__tests__/gate.test.ts, src/commands/deployment/api.ts, src/commands/deployment/gate.ts, src/commands/deployment/interfaces.ts
Renaming this option to make it clearer, but keeping it undocumented for now. This option is unused so it's safe to rename.
=> Replace monitors_variable with monitors_query_variable in deployment gate command

packages/base/package.json, packages/datadog-ci/src/index.ts
Towards https://github.com/DataDog/datadog-ci/issues/1871
This import was outdated
Update it with the correct path
=> Fix git metadata import
